### ISSUE TITLE
jqueryrotate

### ISSUE THREAD

**Issue by xstable** [cdnjs/cdnjs#10271]
**Library name:** jqueryrotate
**Git repository url:** https://github.com/wilq32/jqueryrotate/
**License(s):** MIT
**Official homepage:** http://jqueryrotate.com/

**Comment by sashberd** [comment]
@PeterDaveHello Shoudl we add this lib. It has low popularuty. 
See [here ](https://github.com/cdnjs/cdnjs/issues/5528)the request was closed bu low popularity

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
