### ISSUE TITLE
[Request] Add mateagar/progressStep

### ISSUE THREAD

**Issue by frankyso** [cdnjs/cdnjs#10471]
**Library name:progressStep** 
**Git repository url: https://github.com/mateagar/progressStep**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @frankyso,
We're sorry that we can't host this library since it doesn't have enough notable popularity (100 stars on github / npm 500 downloads per month). If you think this is a great library we should include to our service, please contact PeterDaveHello, the maintainer of cdnjs.

Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by PeterDaveHello** [comment]
@hare1039 please review PR first

**Comment by hare1039** [comment]
Close due to no response. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Let's host this one :)

**Comment by frankyso** [comment]
:D thankyou

Thanks,
Franky So

2017-03-31 2:17 GMT+07:00 Peter Dave Hello <notifications@github.com>:
