### ISSUE TITLE
[Request] Add HyperApp

### ISSUE THREAD

**Issue by jbucaran** [cdnjs/cdnjs#10524]
Library name: **HyperApp**
Git repository url: https://github.com/hyperapp/hyperapp
npm package url: https://www.npmjs.com/package/hyperapp
License(s): **MIT**
Official homepage: https://github.com/hyperapp/hyperapp
Wanna say something? **Hi!**
As requested by @happierall in https://github.com/hyperapp/hyperapp/issues/15 🎉

Can you offer guidance on how to submit HyperApp correctly?

**Comment by hare1039** [comment]
@sufuf3 duplicate #10498 .

**Comment by jbucaran** [comment]
Thanks. Closing in favor of #10498

**Comment by hare1039** [comment]
Hi @jbucaran,
Since PR #10608 run into some problem, I think you can make your library hosted faster if you can send a pull request to add.

The simplest way is to send a single `package.json`.
Please read the guide [adding-a-library-by-a-single-packagejson](https://github.com/cdnjs/cdnjs#adding-a-library-by-a-single-packagejson).

P.S. I think you can copy the `ajax/libs/hyperapp/package.json` from PR #10608 and do some small fix.

**Comment by jbucaran** [comment]
@hare1039 Thanks. Here you go.
https://github.com/cdnjs/cdnjs/pull/10613
