### ISSUE TITLE
[Request] Add JsToUseful

### ISSUE THREAD

**Issue by programmer5000-com** [cdnjs/cdnjs#10527]
# jsToUseful
### GNU GPL v3
JsToUseful is a small (298 bytes minified) library for stringifying data in a more useful way. [See the readme](https://github.com/programmer5000-com/JsToUseful/) for more info.

**Comment by hare1039** [comment]
Hi @programmer5000-com,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs.
Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no response. cc @PeterDaveHello
