### ISSUE TITLE
[Request] Sudo Slider jQuery Plugin

### ISSUE THREAD

**Issue by carlosrdv** [cdnjs/cdnjs#10530]
**Library name:** 
Sudo Slider jQuery Plugin

**Git repository url:**
https://github.com/webbiesdk/SudoSlider

**npm package url(optional):** 

**License(s):**

**Official homepage:**
http://webbies.dk/SudoSlider/

**Wanna say something? Leave message here:**
Love you <3

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @carlosrdv,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs.
Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no responses. cc @PeterDaveHello.
