### ISSUE TITLE
[Request] Add schemapack 

### ISSUE THREAD

**Issue by mwcz** [cdnjs/cdnjs#10549]
**Library name:** schemapack
**Git repository url:** https://github.com/phretaddin/schemapack
**npm package url(optional):** https://www.npmjs.com/package/schemapack
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**

"The fastest and smallest JavaScript object serialization library. Efficiently encode your objects in to compact byte buffers and then decode them back in to objects on the receiver. Integrates very well with WebSockets."

schemapack is typically used in both client and server.  I think it would be very convenient to have a copy on cdnjs for client use!  Thank you for running this fantastic service.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@sajochiu 
Please add this library, thanks.

**Comment by qwe19272375** [comment]
Sorry, it was an accident.

**Comment by PeterDaveHello** [comment]
We'll only host library once there is response from its author: https://github.com/phretaddin/schemapack/issues/24

**Comment by mwcz** [comment]
Thanks @PeterDaveHello, I gave a +1 to phretaddin/schemapack#24

**Comment by PeterDaveHello** [comment]
@mwcz thanks!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
