### ISSUE TITLE
[Request] Add tongwen 

### ISSUE THREAD

**Issue by JackieKu** [cdnjs/cdnjs#10553]
**Library name:** tongwen
**Git repository url: https://github.com/stevendaniels/New-Tongwen-Tang
**npm package url(optional):** 
**License(s): GNU GPL version 2
**Official homepage: https://github.com/stevendaniels/New-Tongwen-Tang
**Wanna say something? Leave message here:**

This is a JavaScript to convert between traditional Chinese and simplified Chinese.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @JackieKu,
This is a great library but we're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs. Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no response.

**Comment by PeterDaveHello** [comment]
@hare1039 you should cc for me if it's non-empty issue.
