### ISSUE TITLE
[Request] Add ng-ck

### ISSUE THREAD

**Issue by jziggas** [cdnjs/cdnjs#10566]
**Library name:** 
ng-ck
**Git repository url:**
https://github.com/jziggas/ng-ck
**npm package url(optional):** 
https://www.npmjs.com/package/ng-ck
**License(s):**
MIT
**Official homepage:**
https://github.com/jziggas/ng-ck
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @jziggas,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs. 
Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by PeterDaveHello** [comment]
Hi @jziggas, as you are the author of this lib, if you'd like to send a PR directly, we'll be happy to help you host it, please let us know what do you think, thanks.
