### ISSUE TITLE
[Request] Add jquery-xmlrpc

### ISSUE THREAD

**Issue by KSoto** [cdnjs/cdnjs#10575]
**Library name:** jquery-xmlrpc
**Git repository url:** https://github.com/timheap/jquery-xmlrpc
**npm package url(optional):** 
**License(s):** unlicense - https://github.com/timheap/jquery-xmlrpc/blob/master/LICENCE
**Official homepage:** http://jquery-xml-rpc.readthedocs.io/en/latest/
**Wanna say something? Leave message here:**

**Comment by hare1039** [comment]
Hi @KSoto,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of CDNJS.
Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by KSoto** [comment]
Dang, not again! K ty :)

**Comment by PeterDaveHello** [comment]
This one looks close the the minimum requirement, we can wait for it.
