### ISSUE TITLE
[Request] Add js-storage

### ISSUE THREAD

**Issue by KSoto** [cdnjs/cdnjs#10574]
**Library name:** js-storage
**Git repository url:** https://github.com/julien-maurel/js-storage
**npm package url(optional):** https://www.npmjs.com/package/js-storage
**License(s):** MIT
**Official homepage:** https://github.com/julien-maurel/js-storage

**Comment by hare1039** [comment]
Hi @KSoto,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs. 
Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by KSoto** [comment]
Oh, ok. No prob, thank you!
