### ISSUE TITLE
[Request] Add jquery-textareaPreview 

### ISSUE THREAD

**Issue by CodeOptimist** [cdnjs/cdnjs#10595]
**Library name:** jquery-textareaPreview
**Git repository url:** https://github.com/andreyfedoseev/jquery-textareaPreview
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://andreyfedoseev.name/blog/articles/34/jquery-textareapreview/
**Wanna say something? Leave message here:**
My GreasyFork script can't go public without this at an authorized host. 😢 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @CodeOptimist,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs.

Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by CodeOptimist** [comment]
That's okay, thanks for the reply @hare1039 . :)
