### ISSUE TITLE
[Author][Request] Add embedo

### ISSUE THREAD

**Issue by shobhitsharma** [cdnjs/cdnjs#10596]
**Library name:**  embedo
**Git repository url:** https://github.com/shobhitsharma/embedo
**npm package url(optional):** https://www.npmjs.com/package/embedo
**License(s):** MIT
**Official homepage:** https://shobhitsharma.github.io/embedo/

**Comment by hare1039** [comment]
Hi @shobhitsharma,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs.

Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by shobhitsharma** [comment]
Its pretty new library and I havent promoted it that much. But since jsdelivr merged my pull, I no longer need cdnjs.

**Comment by PeterDaveHello** [comment]
Hey let's host this library

**Comment by PeterDaveHello** [comment]
@shobhitsharma would you like to send us a pull request?

**Comment by shobhitsharma** [comment]
@PeterDaveHello Thanks for the response. I'll send a pull tonight.

**Comment by PeterDaveHello** [comment]
@shobhitsharma Nice, thanks. BTW, sice the repo is really huge, I will respectfully suggest you to read our doc first, please feel free to ask for help if you need, thank you.

**Comment by shobhitsharma** [comment]
@PeterDaveHello Hey Peter, here https://github.com/cdnjs/cdnjs/pull/10798. Thanks in advance.

**Comment by hare1039** [comment]
I think this issue can be close.

**Comment by PeterDaveHello** [comment]
@hare1039 comment a reason when you say that.

**Comment by hare1039** [comment]
Sorry, I mean https://github.com/cdnjs/cdnjs/pull/10798 had been merged. So this issue can be closed.
