### ISSUE TITLE
[Request] Add mag.js 

### ISSUE THREAD

**Issue by sajochiu** [cdnjs/cdnjs#10603]
**Library name:** mag.js
**Git repository url:**https://github.com/magnumjs/mag.js
**License(s):**MIT
@x09326 please help me review it, thanks! #10165

**Comment by x09326** [comment]
@sajochiu remember remove the field under the `========` line.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
