### ISSUE TITLE
[Request] Add gesco

### ISSUE THREAD

**Issue by zaclummys** [cdnjs/cdnjs#10636]
**Library name:** gesco
**Git repository url:** https://github.com/zaclummys/gesco
**npm package url(optional):** https://www.npmjs.com/package/gesco
**License(s):** MIT
**Official homepage:** https://github.com/zaclummys/gesco#readme
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @zaclummys,
We're sorry that we can't host this library since it doesn't have enough notable popularity boundaries we set in the [readme](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) (100 stars on github / npm 500 downloads per month). 
As you are the author, I recommend you to discuss with the maintainer of cdnjs, PeterDaveHello, to host this library.

Thanks for being interested in CDNJS.
Note: This issue will be closed if no response in 7 days.

**Comment by extend1994** [comment]
Close this issue because of no response and insufficient popularity, cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@hare1039 please assign the issues waiting for response to yourself and don't forget to close them if there is no response.
