### ISSUE TITLE
IE parse issues for fetch v2.0.2 fetch.min.js

### ISSUE THREAD

**Issue by btakita** [cdnjs/cdnjs#10637]
https://github.com/github/fetch/issues/477

https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.2/fetch.js has

```
  Headers.prototype['delete'] = function(name) {
    delete this.map[normalizeName(name)]
  }
```

https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.2/fetch.min.js has

`n.prototype.delete=function(t){delete this.map[e(t)]}`

**Comment by PeterDaveHello** [comment]
Since GitHub didn't provide the minified distribution file officially, the file was minified by [uglify-js](https://github.com/mishoo/UglifyJS2), I'll suggest you to report the issue directly to uglify-js, and maybe suggest GitHub to provide officially minified release file.

cc authors: @josh @mislav @dgraham

**Comment by mislav** [comment]
It's likely that the minification process with `uglify-js` needs an extra flag like `--support-ie8` to opt-in for legacy IE support.

Yes, we don't provide an official minified file. Instead, we delegate minification to our users and other systems that re-distribute our library. What that means is that _they_ choose the tools and the parameters for minification based on their needs. We can't tell you what your own needs are.

The person who opened this bug was trying to load `fetch.js` on IE8. Our polyfill can't possibly work on IE8, even if it was properly minified. Therefore, this whole endeavor is a moot point.

**Comment by PeterDaveHello** [comment]
Hi @mislav , thank you very much for your help and explanation, I jut wondering if it's possible to provide officially minified file? So that we make have more confidence on its integrity by its hash or SRI(https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), thanks!

**Comment by mislav** [comment]
It's definitely possible for us to provide a minified file when we publish a npm package. But we're not terribly motivated to do so, especially because then people could come up to us and say “but please, enable option X in the minifier because I need that”. The library is already tiny and if anyone needs minification on top of that, they're welcome to do so.

**Comment by PeterDaveHello** [comment]
Thanks @mislav, so I think there is nothing we can do on this issue, I'll close it now, thanks.

**Comment by btakita** [comment]
@mislav FYI, I was testing this on IE11.
