### ISSUE TITLE
[Request] Add ResponsifyJS

### ISSUE THREAD

**Issue by webuniverseio** [cdnjs/cdnjs#10644]
**Library name:** ResponsifyJS
**Git repository url:** https://github.com/wentin/ResponsifyJS/
**License(s):** MIT
**Official homepage:** http://responsifyjs.space/

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mercyg** [comment]
@szarouski  I would like to this library!

**Comment by mercyg** [comment]
Hi @pvnr0082t I wanted to add this library but since it doesn't have package.json, I can't add it using cdnjs-importer. My question is where to create the package.json?

**Comment by pvnr0082t** [comment]
@mercyg I suggest you pick other issue first because there is no git tag on GitHub repo of the lib. I have already open an issue for this. ref: https://github.com/wentin/ResponsifyJS/issues/6.
Answer to your question, if there is no package.json of the lib, you can
1. copy the existence package.json in cdnjs and fill the necessary infomation 
2. run `$ npm init` and it will lead you to fill some information and then automatically create a package.json file.

**Comment by mercyg** [comment]
@pvnr0082t thanks

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
