### ISSUE TITLE
[Request] Add chartjs-plugin-zoom.js

### ISSUE THREAD

**Issue by marthieme** [cdnjs/cdnjs#10680]
**Library name:** chartjs-plugin-zoom.js
**Git repository url:**  https://github.com/chartjs/chartjs-plugin-zoom
**npm package name or url** (if there is one): chartjs-plugin-zoom
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @marthieme,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs.

Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no response in 7 days, cc @PeterDaveHello.

**Comment by PeterDaveHello** [comment]
We can add it but with lower priority.

**Comment by sufuf3** [comment]
duplicate with #9445
close and move to #9445
cc @PeterDaveHello
