### ISSUE TITLE
[Request] Add angular2-disqus

### ISSUE THREAD

**Issue by pedrohills** [cdnjs/cdnjs#10687]
**Library name:** angular2-disqus
**Git repository url:** https://github.com/Useful-Software-Solutions-Ltd/angular2-disqus
**npm package name or url** (if there is one): https://www.npmjs.com/package/angular2-disqus
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/Useful-Software-Solutions-Ltd/angular2-disqus
**Wanna say something? Leave message here:**

**Comment by hare1039** [comment]
Hi @pedrohills,
We're sorry that we can't host this library since it doesn't have enough notable popularity (100 stars on github / npm 500 downloads per month). If you think this is a great library we should include to our service, please contact PeterDaveHello, the maintainer of cdnjs.

Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no response. cc @PeterDaveHello
