### ISSUE TITLE
[Request] Add Awkward Showcase

### ISSUE THREAD

**Issue by fverry** [cdnjs/cdnjs#10776]
**Library name:** Awkward Showcase
**Git repository url:** https://github.com/06b/Awkward-Showcase
**Official homepage:** http://www.awkwardgroup.com/sandbox/awkward-showcase-a-jquery-plugin/

**Comment by hare1039** [comment]
Hi @fverry,
We're sorry that we can't host this library since it doesn't have enough notable popularity (100 stars on github / npm 500 downloads per month). If you think this is a great library we should include to our service, please contact PeterDaveHello, the maintainer of cdnjs.

Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no response. cc @PeterDaveHello
