### ISSUE TITLE
[Request] Add candy chat

### ISSUE THREAD

**Issue by leif81** [cdnjs/cdnjs#10789]
**Library name:**  Candy
**Git repository url:**  https://github.com/candy-chat/candy
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://candy-chat.github.io/candy/
**Wanna say something? Leave message here:** As a stretch goal, there are a number of useful plugins for Candy (https://github.com/candy-chat/candy-plugins) that would be useful to have in cdnjs too.

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Looks like the main file is not inside its repo: https://github.com/candy-chat/candy/blob/v2.2.0/bower.json#L11, @leif81 would you like to help confirm if they can provide the files need to be hosted in the repo? Thanks.

**Comment by leif81** [comment]
@PeterDaveHello I found the main file in the zip under the GitHub releases tab:

https://github.com/candy-chat/candy/releases/download/v2.2.0/candy-2.2.0.zip

The main file references the contents of the "res/" folder. Is that possible to host too?

**Comment by PeterDaveHello** [comment]
We don't support to download files from the GitHub download feature yet, and would hope to use auto-update feature, which needs the files to be inside the repository, they don't need to be in the `master` or `dev` branch, just need to be in the tagged commit, like v2.2.0, thanks.

**Comment by leif81** [comment]
If it were published to npmjs would that work for you?

**Comment by PeterDaveHello** [comment]
@leif81 could be an option :)

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
