### ISSUE TITLE
[Request] Add pull-to-reload

### ISSUE THREAD

**Issue by ErlendEllingsen** [cdnjs/cdnjs#10807]
**Library name:** pull-to-reload
**Git repository url:** https://github.com/ErlendEllingsen/pull-to-reload
**npm package name or url** (if there is one): https://www.npmjs.com/package/pull-to-reload
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/ErlendEllingsen/pull-to-reload
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
