### ISSUE TITLE
[Request] Add GetGridy

### ISSUE THREAD

**Issue by JeffreySlabbekoorn** [cdnjs/cdnjs#10819]
**Library name:**  GetGridy
**Git repository url:** https://github.com/JeffreySlabbekoorn/GetGridy.git
**npm package name or url** (if there is one): None
**License (List them all if it's multiple):** MIT License
**Official homepage:** http://getgridy.us/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @JeffreySlabbekoorn,
We're sorry that we can't host this library since it doesn't have enough notable popularity according to the boundaries we set in the [readme](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) (100 stars on github / npm 500 downloads per month). 
As you are the author, I recommend you to discuss with the maintainer of cdnjs, PeterDaveHello, to host this library.

Thanks for being interested in CDNJS.
Note: This issue will be closed if no response in 7 days.

**Comment by PeterDaveHello** [comment]
@hare1039 let's review the PRs first, you have many pending ones.

**Comment by hare1039** [comment]
Close due to no response. cc @PeterDaveHello
