### ISSUE TITLE
[Request] Add flexicious-react-datagrid

### ISSUE THREAD

**Issue by flexicious** [cdnjs/cdnjs#10849]
**Flexicious React DataGrid:** 
**https://github.com/flexicious/react-datagrid** 
**https://www.npmjs.com/package/flexicious-react-datagrid** (if there is one): 
**Commercial** 
**http://www.reactdatagrid.com/** 
**Would like to host the React DataGrid component developed by our company.** 

=====================

**Comment by flexicious** [comment]
Last request was closed because of lack of popularity, but we are now at 2k downloads/month

**Comment by PeterDaveHello** [comment]
I doubt if the download status has been manipulated ...

**Comment by flexicious** [comment]
Not sure what you mean? A couple of large organizations just started using it and they have many developers/CI servers - may be thats what is causing the spike?

**Comment by PeterDaveHello** [comment]
Just as the meaning of the words, the status looks abnormal ... we'll keep eyes on it, thanks.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this.

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time.
