### ISSUE TITLE
[Request] Add smallipop

### ISSUE THREAD

**Issue by ArianeNubee** [cdnjs/cdnjs#10859]
**Library name:** smallipop
**Git repository url:**  https://github.com/Sebobo/jquery.smallipop
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://projects.sebastianhelzle.net/jquery.smallipop/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@ArianeNubee this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our README.md. Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Let's give it a lower priority to add it.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
