### ISSUE TITLE
[Request] Add jQuery.initialize

### ISSUE THREAD

**Issue by m47730** [cdnjs/cdnjs#10911]
**Library name:** jQuery.initialize
**Git repository url:** https://github.com/pietrasiak/jquery.initialize.git
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** The MIT License (MIT)
**Official homepage:** https://github.com/pietrasiak/jquery.initialize
**Wanna say something? Leave message here:** Seems UNIX philosophy compliant, one thing done right

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @m47730  
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can add this one, just give it a lower priority.

**Comment by iivmok** [comment]
+1, very usefull library, was surprised to not see it on cdnjs.

**Comment by PeterDaveHello** [comment]
@iivmok @m47730 you can send a pull request if you'd like to make it on cdnjs sooner :)

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
