### ISSUE TITLE
[Request] Add actioncable-js

### ISSUE THREAD

**Issue by WriteCodeEveryday** [cdnjs/cdnjs#10913]
**Library name:** actioncable-js
**Git repository url:** https://raw.githubusercontent.com/mwalsher/actioncable-js/master/
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** Would be awesome for the dist version to be available.

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@WriteCodeEveryday Do you mean this library?
https://github.com/mwalsher/actioncable-js
https://www.npmjs.com/package/actioncable-js

**Comment by WriteCodeEveryday** [comment]
Yes, I must have grabbed a direct link to the inbrowser version.                                                                                                                                                                            From: notifications@github.comSent: March 25, 2017 7:38 AMTo: cdnjs@noreply.github.comReply-to: reply@reply.github.comCc: lherr012@fiu.edu; mention@noreply.github.comSubject: Re: [cdnjs/cdnjs] [Request] Add actioncable-js (#10913)  @WriteCodeEveryday Do you mean this library?
https://github.com/mwalsher/actioncable-js
https://www.npmjs.com/package/actioncable-js

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
