### ISSUE TITLE
[Request] Add webcam-directive

### ISSUE THREAD

**Issue by hare1039** [cdnjs/cdnjs#11071]
**Library name:** webcam
**Git repository url:** https://github.com/jonashartmann/webcam-directive
**npm package name or url** (if there is one): https://www.npmjs.com/package/webcam-directive
**License (List them all if it's multiple):** MIT https://github.com/jonashartmann/webcam-directive/blob/master/bower.json#L23
**Official homepage:** https://jonas.hartmann.site/webcam-directive/#/

**Comment by PeterDaveHello** [comment]
@hare1039 why didn't you label old issue(s) before to open new one?

**Comment by hare1039** [comment]
I was writing a website assignment, than I found out this library can be added into cdnjs. So I opened this issue and back to my work.
I will add old issue next time.

**Comment by ajay2507** [comment]
Is it open. Can I make this change?

**Comment by PeterDaveHello** [comment]
@ajay2507 you mean you want to take it? It's fine to take it.

**Comment by ajay2507** [comment]
okay:) @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@ajay2507 :+1:

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
