### ISSUE TITLE
[Important] Stop working on non-high-priority library adding issues.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11170]
As you guys can see, we have many *dropped* pull requests in the list:

https://github.com/cdnjs/cdnjs/pulls?utf8=%E2%9C%93&q=is%3Aopen%20is%3Apr%20sort%3Aupdated-asc%20s

The author or the pull requests just leaved, dropped the PRs, no matter what the reasons are, I think it's time to clean them up! From now on, we'll stop working on non-high-priority issues, focus on the  high-priority issues, and take care of the old pull requests.

The first stage, we target on the pull requests:
1. not authored by the assignees in this issue
2. not in status need response from the upstream
3. not respond after two pings from @PeterBot

Not that the "wait for response" may be not that reliable especially if the waiting is longer than a month.

What we are going to do on the *dropped* pull requests, is to use new and working pull requests to close the old, dropped ones, for these kind of libraries, we treat them as High Priority issues, do our best to host them, try to manually fix the problems as those pull requests are pending so long, maybe more than 50% of have problems need to be solved manually. To prevent wasting and overlap on the effort, please leave a comment to tell everybody that you're going to pick and fix that pull request.

#4686 & eee3ed4630aa9151f7d1ceabee51e6538ea862a8 is an example of how would we deal with it.

Suggestions, discussions are very welcome.
Thank you all!

**Comment by sufuf3** [comment]
May I take #10248 ?

**Comment by PeterDaveHello** [comment]
Isn't #10248 assigned to @pvnr0082t ?

**Comment by sufuf3** [comment]
Yes, it is.

**Comment by PeterDaveHello** [comment]
@sufuf3 so why don't you pick up some others?

**Comment by sufuf3** [comment]
OK! May I take #9777 ?

**Comment by PeterDaveHello** [comment]
@sufuf3  Sure.

**Comment by sufuf3** [comment]
The PR #9777 I think it can close because the repo is a lightweight commenting server written in Python and JavaScript. And it's not the JavaScript or CSS library which can use in front-end.

May I take another PRs as the followings?
- [ ] #10086
- [ ] #10133 
- [ ] #10640
- [ ] #7268

**Comment by PeterDaveHello** [comment]
@sufuf3 go ahead.

**Comment by sufuf3** [comment]
1. I think the PR #10631 (issue: #10312) can close.
Because the lib team of one of member didn't answer your question and I take a look about the repo, it's can't use in front-end still.
I think this PR can close now. If someone wants to add this library, and it supports Html's script tag, then just send another PR to do this.

2. I think the PR #8377 can close because I can't find any repo about this. (Neither GitHub, npm and Google) 

3. I think #6894 (https://cdnjs.com/libraries/10up-sanitize.css) and #10592 (https://cdnjs.com/libraries/scrolldir) can close because we hosted them.

4. [Author] not popular, not respond after two pings from @PeterBot
The PR #10708 (issue: #10638) was created by the author. 
The PR #10414 was created by the author. 
The PR #8388 was created by the author. 
The PR #7355 was created by the author. 
I found these libraries are not popular. And the author didn't maintain these PRs. Should we help fix these PRs?

When I fix the PR of No. 10133 , may I take PRs as the followings?
 - [ ] #10573
 - [ ] #10587
 - [ ] #10546
 - [ ] #10547
 - [ ] #10709
 - [ ] #9904  (This PR I think can help the contributor fix it. maybe just need to rebase master. It's LGTM.)
 - [ ] #10141
 - [ ] #8360
 - [ ] #9369
 - [ ] #5367
 - [ ] #6687

**Comment by PeterDaveHello** [comment]
@sufuf3 please don't pick so many PRs at a time, you did a good job but a little bit too greedy.

**Comment by PeterDaveHello** [comment]
@extend1994 @hare1039 @clairetsai818 do you have related progress on this part?

**Comment by clairetsai818** [comment]
I'm still working on the high-priority issue assigned to me.

**Comment by sufuf3** [comment]
#6687 is not enough popularity. should we work on it?
Or maybe we can close this PR?
This PR sent by the author, I think he uses another way to host his library.

**Comment by extend1994** [comment]
Not yet, mostly working on reviews recently.

**Comment by PeterDaveHello** [comment]
@sufuf3 https://github.com/cdnjs/cdnjs/pull/6687#issuecomment-263104358

**Comment by sufuf3** [comment]
So we still need to add this one, is it? (as the comment)
If it is, I got it.
And this PR not respond after two pings from @PeterBot
So we should take this PR.

Is my understanding correct?

**Comment by PeterDaveHello** [comment]
Doesn't the reference explain to add or not?

**Comment by sufuf3** [comment]
Sorry I can't understand.
1. As "the https://github.com/cdnjs/cdnjs/pull/6687#issuecomment-263104358" we should help the author to add this one.
2. As "not respond after two pings from @PeterBot and it's created by author" we should ask the author, if there is no response, we help to take the PR.
3. As " not enough popularity (Just 42 stars)" we don't add it.

There are three situations in this PR.
I don't know what should I do. It's conflict.

**Comment by PeterDaveHello** [comment]
@sufuf3 did I throw you three situations?

**Comment by sufuf3** [comment]
Through the past until now, yes.
 https://github.com/cdnjs/cdnjs/issues/11170#issuecomment-304336335 this time, no.

**Comment by PeterDaveHello** [comment]
@sufuf3 don't play with text

**Comment by sufuf3** [comment]
I'm sorry. I just need to make a confirm, to make sure that my understanding is correct.
I really afraid that I understand the wrong direction.

**Comment by PeterDaveHello** [comment]
@sufuf3 you asked about popularity, doesn't the comment anwser you?

**Comment by sufuf3** [comment]
Yes, I will just follow the comment of this PR to add it.
Thanks.

**Comment by hare1039** [comment]
I haven't started on this yet.

**Comment by sufuf3** [comment]
1. #9276 (relate issue:#8189)  --> I don't think this library can use in front-end.
2. #8148 I think this PR can close because the file remove dependencies field and updated (https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/angucomplete-alt/package.json)

3. May I take PRs as the followings? (If members want to join this, it's wellcome.)
- [ ] #10183
- [ ] #9760
- [ ] #9726
- [ ] #9711
- [ ] #8973
- [ ] #8927
- [ ] #8901
- [ ] #8539
- [ ] #8530
- [ ] #8453
- [ ] #8444
- [ ] #7646 (The licence is MIT since https://github.com/leafo/sticky-kit/pull/154)
- [ ] #7628
- [ ] #7604
- [ ] #7590
- [ ] #6575
- [ ] #6572
- [ ] #6571
- [ ] #6537
- [ ] #5846

[Author]

4. #6687 --> May I take this PR because the author doesn't reply for 11 days?
5. #7439 Waiting for response from author

**Comment by dakshshah96** [comment]
Working on the following PRs from @sufuf3's list. Marked them as done in the above list so there's only one place (this comment) to track them:

- [ ] #5846 
- [ ] #7628
- [ ] #8973
- [x] #10183
- [ ] #9760

**Comment by dakshshah96** [comment]
@PeterDaveHello How do we handle `wait for response` PRs? There are several pull requests which are in that status for more than a couple of months.

**Comment by PeterDaveHello** [comment]
@dakshshah96 good questions, I've told the other members that we'll try to manually add those library unless they're not popular enough.

**Comment by PeterDaveHello** [comment]
Guys I think we don't need to pick up those PRs for beginners issue like #11299, just leave them for their next picker.

**Comment by extend1994** [comment]
Working on
 - [ ] #10707
 - [ ] #10578

**Comment by sufuf3** [comment]
## The list of PRs need to be solved:
- [ ] cdnjs/cdnjs#6084 (npm is OK)
