### ISSUE TITLE
[Author][Request] Add Instafetch.js

### ISSUE THREAD

**Issue by thomasvaeth** [cdnjs/cdnjs#11190]
**Library name:** Instafetch.js
**Git repository url:** https://github.com/thomasvaeth/instafetch.js
**npm package name or url (if there is one):** https://www.npmjs.com/package/instafetch.js
**License (List them all if it's multiple):** MIT
**Official homepage:** http://thomasvaeth.com/instafetch.js/
**Wanna say something? Leave message here:**

**Comment by PeterDaveHello** [comment]
Hi @thomasvaeth, sorry for the late reply, just asking: if you'd be interested in sending us a pull request? It'll be great if you can send us a pull request, so that we can host it faster! There are some references in beginner issues like #11291 may help, please let me know that if you need any help 😄

**Comment by thomasvaeth** [comment]
Submitted PR #11687. I just noticed the contributing guidelines got bumped from 100 to 200 stars. Is that going to apply for this library since I took so long to submit the PR?

**Comment by sufuf3** [comment]
I think it's fine.
Because the https://github.com/cdnjs/cdnjs/commit/c484b8b1bdfaaf32e742a1687e927afe2de710c0 commit message said it's for the new issues, use the new standard. :)
I'll help you review the PR, later. 😃 
Thank you.
