### ISSUE TITLE
[Request] Add gifplayer

### ISSUE THREAD

**Issue by pramyogo** [cdnjs/cdnjs#11192]
**Library name:** gifplayer
**Git repository url:** https://github.com/rubentd/gifplayer
**License (List them all if it's multiple):** MIT License (https://github.com/rubentd/gifplayer/blob/master/LICENSE)
**Official homepage:** http://rubentd.com/gifplayer

=====================

Thanks

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
