### ISSUE TITLE
[Request] Add pixel-grid

### ISSUE THREAD

**Issue by BitVortex** [cdnjs/cdnjs#11207]
**Library name:** pixel-grid
**Git repository url:** https://github.com/freeman-lab/pixel-grid
**npm package name or url** (if there is one): [pixel-grid](https://www.npmjs.com/package/pixel-grid)
**License (List them all if it's multiple):** MIT License
**Official homepage:** https://github.com/freeman-lab/pixel-grid
**Wanna say something? Leave message here:** Nice little module to easily render and animate pixel grids using webgl and regl.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
