### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by dakshshah96** [cdnjs/cdnjs#11270]
Just like how cdnjs has a template users need to fill out before opening a pull request, I think we should have a template for issues as well.

Majority of the issues opened are those for addition of a new library. Template for those can be something like this:

```
<!-- cdnjs Issue Template -->

<!-- Please provide as much detail as possible for us to fix your issue -->
<!-- Remove any heading sections you did not fill out -->

<!-- NOTE: Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) documents first. -->

#### Add new library
<!-- Fill out the details below -->

* **Library name:**
* **GitHub URL:** 
* **npm package name or URL** (if there is one): 
* **License (List them all if there are multiple):** 
* **Official homepage:** 
* **Optional message:** 

#### Bug fix
<!-- Found a bug? Describe below when the issue happens and how to reproduce it -->
```

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Actually that's something we were doing before, but was removed, as you can see, there are too many request issues that we can't handle, also, too many people don't know how to use it properly and then created many empty issues, that's why I removed it, for now people will only get the link/template when they searching on cdnjs.com, the link will be the bottom of the page, before we have enough time/review/contributor, I'll not add it back, thanks for your suggestion @dakshshah96 👍
