### ISSUE TITLE
[Request] Add t-scroll

### ISSUE THREAD

**Issue by ProfitCreations** [cdnjs/cdnjs#11328]
**Library name:** t-scroll
**Git repository url:** https://github.com/crazychicken/t-scroll
**npm package name or url** (if there is one): https://www.npmjs.com/package/t-scroll
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@ProfitCreations any details about this library like git repository or npm package?

**Comment by sufuf3** [comment]
@ProfitCreations Did you want to CDNJS host this library?
https://www.npmjs.com/package/t-scroll
https://github.com/crazychicken/t-scroll

**Comment by ProfitCreations** [comment]
@sufuf3 Yes thanks

**Comment by sufuf3** [comment]
@ProfitCreations OK. But this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? 

Or we encourage you to add a library via sending pull request, it'll be faster than just opening a request issue, since there are tons of issues, please wait with patience, and please don't forget to read the guidelines for contributing, thanks!!

If there are no response in 7 days, I will close this issue. 
Thanks for your great work and contribution.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
