### ISSUE TITLE
[Request] Add jquery.counterup

### ISSUE THREAD

**Issue by dev-seahouse** [cdnjs/cdnjs#11325]
**Library name:** jquery.counterup
**Git repository url:** https://github.com/ciromattia/jquery.counterup
**npm package name or url** (if there is one):  jquery.counterup
**License (List them all if it's multiple):** GNU General Public License v2.0
**Official homepage:**  https://github.com/ciromattia/jquery.counterup/blob/master/LICENSE**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@dev-seahouse I found this library fork from https://github.com/bfintal/Counter-Up

Is there any reason that we need to host `ciromattia/jquery.counterup`?
Because this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). (Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). )

And CDNJS host [Counter-Up](https://cdnjs.com/libraries/Counter-Up) already.

Thanks for your great work and contribution.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
