### ISSUE TITLE
[Request] Add http://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/mode-csv.js

### ISSUE THREAD

**Issue by krunal221291** [cdnjs/cdnjs#11347]
**Library name:** http://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/mode-csv.js
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

Hello , first i am very thankful to you for sharing this kind of awesome libraries, 
I am using http://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/mode-csv.js JS file but right now its not available on the server, Kindly please share that file with me or share the file in email ,

Please solve this issue As soon as possible
=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@krunal221291 could you discuss with the author of upstream?
I found that the `mode-csv.js` file does not exist in https://github.com/ajaxorg/ace-builds/tree/v1.2.6/src-min .

**Comment by krunal221291** [comment]
I didnt know that. 
But Now that Domain has been changed to

**Comment by sufuf3** [comment]
@krunal221291 the link you want to use is mean you want to use `mode-csv.js` file from ace@v1.2.6.
And CDNJS host this library from this GitHub repo [ace](https://github.com/ajaxorg/ace-builds).
And there is no `mode-csv.js` file in this repo, so the link https://cdnjs.com/ajax/libs/ace/1.2.6/mode-csv.js is not available.
That's why you can't get the `mode-csv.js` JS file.

I think if you want to use `mode-csv.js` file from ace@v1.2.6, maybe you could discuss with the author of origin upstream GitHub repo [ace](https://github.com/ajaxorg/ace-builds).
Maybe you will get the `mode-csv.js` JS file which you want after you discuss with the author of upstream.

**Comment by PeterDaveHello** [comment]
@krunal221291 there url is not valid, we don't have the file ever, may I know that how/where did you get it? Thanks.
