### ISSUE TITLE
[Request] Add TodoMVC common assets

### ISSUE THREAD

**Issue by kumarshantanu** [cdnjs/cdnjs#11395]
Project URLs:
https://github.com/tastejs/todomvc-common (MIT license)
https://github.com/tastejs/todomvc-app-css (CC BY 4.0 license)

There are not too many stars for these repos, but it would be great to have them on a CDN as it would help developers refer to these resources.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
