### ISSUE TITLE
[Request] Add hyperform-l10n

### ISSUE THREAD

**Issue by evromalarkey** [cdnjs/cdnjs#11435]
**Library name:** hyperform-l10n
**Git repository url:** https://github.com/hyperform/hyperform-l10n
**npm package name or url** (if there is one): https://www.npmjs.com/package/hyperform-l10n
**License (List them all if it's multiple):** MIT
**Official homepage:** http://hyperform.github.io/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by qwe19272375** [comment]
@evromalarkey this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our README.md. Would you mind to open an issue again when the library has more popularity?

**Comment by evromalarkey** [comment]
obviously because it's localization module for the main library - https://github.com/hyperform/hyperform/ which has 500 stars and it's already on cdnjs

**Comment by PeterDaveHello** [comment]
@evromalarkey thanks!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄

**Comment by evromalarkey** [comment]
This is ridiculous, but no problem. I'll use rather jsdelivr or unpkg ;)
