### ISSUE TITLE
[Request] Update infinite-scroll to v3

### ISSUE THREAD

**Issue by shinoamakusa** [cdnjs/cdnjs#11463]
Infinite-Scroll (https://cdnjs.com/libraries/jquery-infinitescroll) plugin has a new home and developer (https://github.com/metafizzy/infinite-scroll) and new homepage (https://infinite-scroll.com/)

Would it be possible to update the existing plugin to v3 or does it need to be a brand new project if a new developer is creating new versions?

Thanks

**Comment by sufuf3** [comment]
@shinoamakusa Thank you for notice.
Because the link(github.com/infinite-scroll/infinite-scroll) always redirect to (https://github.com/metafizzy/infinite-scroll).
I think just need to update the [package.json](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery-infinitescroll/package.json).
Thanks a lot.

**Comment by PeterDaveHello** [comment]
@sufuf3 any updates?
