### ISSUE TITLE
[Request] Add circular-progress

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11507]
**Library name:** circular-progress
**Git repository url:** https://github.com/neoziro/circular-progress
**License:** MIT

=====================

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by poldiwa** [comment]
@PeterDaveHello hello it's going to be my first attempt to contribute on open source, is there anything else I need to do, before I start diving in?

**Comment by NicBonetto** [comment]
Hello, I would like to take this issue on :)
So for what I understand, circular-progress already has a minified .js and .map file. It also has a package.json file. All this request requires is copying their minified files and adding auto-update config to the package.json file correct?

**Comment by PeterDaveHello** [comment]
@NicBonetto Sorry for the late response, dealing with too many issues 😅 You are correct! Just need to make few changes like auto-update config in `package.json`, and also, you can submit the pull request on GitHub web gui, so that you don't need to clone and checkout the repository locally(you can still do that if you are not so familiar with git and wanna learn something), which would be faster! I'll assign @extend1994 to help you finish the pull request, good luck!

**Comment by extend1994** [comment]
Hi @NicBonetto 😄 
Here are the steps you can follow to add this library:
1. [Fork](https://github.com/cdnjs/cdnjs/fork) the cdnjs repo and do the following steps on your forked repo.
2. Create a new, non-master branch by clicking the "Branch: master" dropdown and enter the name of the library being added.
3. Create the file `<lib_name>/package.json` (here would be `circular-progress`) under `ajax/libs` directory by clicking "Create new file" button. You will see the part of the screen like this image <img width="477" alt="2017-09-01 1 39 56" src="https://user-images.githubusercontent.com/13430892/29956675-18f5eb68-8f1b-11e7-896b-7f595cba0181.png">
Find the package.json (or bower.json if there is no package.json) in source repo. Please copy it and modify it if it doesn't match the format of package.json in cdnjs. There are 9 fields we may need in total here. Other than these fields, please remove them.
* Necessary ones: `name`, `filename`, `description`, `keywords`, `repository`, `author`, `license` and "npm auto-update" (or "git auto-update")
  * `name`: library name, please use the GitHub repo name if the source is GitHub, please use npm package name if the source is npm.
  * `filename`: Find the main file of this library, you might be able to find it after reading its documentation. If the main file is not minified, please still use `<filename>.min.js` or `<filename>.min.css` structure naming, we'll do the minify job.
  * `author`: There might be more than one author. Please use `authors` instead when there are multiple authors.
  * `license`: There also might be more than one license. Please use `licenses` when there are multiple licenses.
  * npm auto-update or git auto-update: Please follow https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md. There are a few rules to help you choose GitHub or npm to be the source. The simplest rule you can use here is to choose the one with more versions. If the number of versions are the same, please use npm because we prefer it.
* Unnecessary: `homepage` if it's the same as the source repo or just a demo page with no link to its source repo.

  Last, please use [JSONLint](http://jsonlint.com/) to validate your package.json. 
  Here is the package.json as the reference for you:
  ```
  {
    "name": "circular-progress",
    "filename": "circular-progress.min.js",
    "description": "A JavaScript circular progress widget, dependency-free and configurable.",
    "author": "Bergé Greg <berge.greg@gmail.com>",
    "license": "MIT",
    "keywords": [
      "circular",
      "progress",
      "JavaScript",
      "widget",
      "dependency-free",
      "configurable"
    ],
    "repository": {
      "type": "git",
      "url": "https://github.com/neoziro/circular-progress.git"
    },
    "autoupdate": {
      "source": "git",
      "target": "git://github.com/neoziro/circular-progress.git",
      "fileMap": [
        {
          "basePath": "",
          "files": [
            "circular-progress*"
          ]
        }
      ]
    }
  }
  ```
4. Commit new file: 
* The heading of the commit message: `Add circular-progress w/ git auto-update via single package.json`
* The body of the commit message: `close #11507, cc @neoziro`
5. Submit the pull request in cdnjs repo and fill out the asked information to make sure that everything you can do is good.
[Example 1](https://github.com/extend1994/cdnjs/blob/99b1a5ca8de29b6fa96468d417befa093841bba7/ajax/libs/videojs-ima/package.json), [Example 2](https://github.com/extend1994/cdnjs/blob/91d227960987d08efadc95f7719cb2ab5b9614f7/ajax/libs/gotem/package.json), [Official document](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson)

**Comment by PeterDaveHello** [comment]
@extend1994 don't forget to use syntax highlight in the codeblock.
