### ISSUE TITLE
[Request][Author] Add pozition.js

### ISSUE THREAD

**Issue by cezarsmpio** [cdnjs/cdnjs#11586]
**Library name:** pozition.js
**Git repository url:** https://github.com/cezarlz/pozition.js
**npm package name or url** (if there is one): pozition.js
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/cezarlz/pozition.js

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @cezarlz 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: However, you are welcome to send a pull request to add your library, we will assist you if you want!

This issue will be closed if there is no any response in next 7 days. 

Thank you for your contribution!

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can host this.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
