### ISSUE TITLE
jquery.hoverIntent.js is not updated

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#11656]
I just worked with this library and I think that the file in cdnjs is not latest or updated, nevertheless the versions in the files are the same
You can compare this [file](https://github.com/briancherne/jquery-hoverIntent/blob/master/jquery.hoverIntent.js) with one stored at cdnjs

FYR

**Comment by PeterDaveHello** [comment]
Master branch will of course be different with the others, if there is any version update, then we should update it.

**Comment by sashberd** [comment]
@PeterDaveHello So what usually we should do at such problem. Should I ask author to upgrade plugin?

**Comment by PeterDaveHello** [comment]
@sashberd I haven't diggit yet, you can see if it's auto-update enabled on its page on CDNJS first.

**Comment by sashberd** [comment]
@PeterDaveHello I think no, there is no auto-update
![image](https://user-images.githubusercontent.com/11975561/28886626-da06b762-77c2-11e7-9f7b-69f03b0052fd.png)

**Comment by PeterDaveHello** [comment]
@sashberd so, of course, it needs manual updates.

**Comment by sashberd** [comment]
@PeterDaveHello Would you like I will update package js to auto update?

**Comment by PeterDaveHello** [comment]
@sashberd oops, I think are looking at a wrong page, that's not the page I mentioned. Looks like it has auto-update config.

**Comment by sashberd** [comment]
@PeterDaveHello I am new here. I think you are talking about old process of auto update, are you? Where I should check it?

**Comment by PeterDaveHello** [comment]
@sashberd I mean its page on cdnjs.com, where you find the library.

**Comment by PeterDaveHello** [comment]
@sashberd As you can see here https://cdnjs.com/libraries/jquery.hoverintent, the lable shows "git autoupdate enabled", so the reason maybe 1) the author released a new version but forgot to add a git tag for its version, 2) the auto-update config is dated

**Comment by usmonster** [comment]
Hello! This is because we indeed haven't tagged the version that's currently on master. You can see on [the project's Milestones page](https://github.com/briancherne/jquery-hoverIntent/milestone/1) that there are still a couple of small issues to close before we officially release version v1.9.0. This should be done within the next day or so—thanks for the poke!

In the meantime, feel free to close this issue, as it's not for the CDNJS folks to fix. ;)

**Comment by sashberd** [comment]
@PeterDaveHello FYI

**Comment by usmonster** [comment]
FYI v1.9.0 is out, and I see it was auto-updated in CDNJS in a168be04442c2d92af0cbea52f15d17bd8c776ac (🎉) , though there are still some small things that might need to be manually updated on the CDNJS side.

For example, it would be nice to synchronize [the listed name and url](https://cdnjs.com/libraries/jquery.hoverintent) (etc.) with what's in [the official package.json](https://github.com/briancherne/jquery-hoverIntent/blob/master/package.json). I also wonder if it's possible for CDNJS to use the [official minified version](https://github.com/briancherne/jquery-hoverIntent/blob/master/jquery.hoverIntent.min.js), even though this comes without a sourcemap.

Thanks!

**Comment by sashberd** [comment]
@PeterDaveHello 
Can we do improves by @usmonster  asked?
Thanks

**Comment by sufuf3** [comment]
@sashberd as https://github.com/cdnjs/cdnjs/commit/a168be04442c2d92af0cbea52f15d17bd8c776ac#commitcomment-24072925 said,  Would you help this issue?
the reason is https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery.hoverintent/package.json#L24 we just get the `"jquery.hoverIntent.js"` so we need to modify to `"jquery.hoverIntent*"` to get `jquery.hoverIntent.min.js` and `jquery.hoverIntent.js`.

So first commit, you could update the `package.json` and the commit message as the followings:
```
Update jquery.hoverintent auto-update config, close #11656
```

The second commit need to remove the `jquery.hoverIntent.min.js.map` and `jquery.hoverIntent.min.js` from CDNJS added, and add `jquery.hoverIntent.min.js` from https://github.com/briancherne/jquery-hoverIntent/blob/v1.9.0/jquery.hoverIntent.min.js


Thank you.

**Comment by sashberd** [comment]
@sufuf3 
I made first commit 
I did not understand what should be changed for second commit
Can you explain in details
Thanks

**Comment by sufuf3** [comment]
Un.. actually you made three commits, and the first commit seems very OK.
let's remove `0dcbcb2` and `5de1b1b`.
It's easy just type `git reset --hard befcd1607d3020469a2c9e962c9c74a14e1b03d8`.
After this command, we have to do as followings:
1. delete `jquery.hoverIntent.min.js.map` and `jquery.hoverIntent.min.js` which under `ajax/libs/jquery.hoverintent/1.9.0`.
2. download https://github.com/briancherne/jquery-hoverIntent/blob/v1.9.0/jquery.hoverIntent.min.js this file and add it under `ajax/libs/jquery.hoverintent/1.9.0`.

**Comment by sashberd** [comment]
@sufuf3 
Ok no problem
Today we have to continue conversation about my git problem, After this I will do above commits

**Comment by sufuf3** [comment]
OK!
I just found you sent a PR #11785 on this issue.
But there are some git issues to solve.
We can deal with step by step.
