### ISSUE TITLE
jquery.easyui 

### ISSUE THREAD

**Issue by liuyun025** [cdnjs/cdnjs#11697]
more and more people are using jquery.easyui, but cdnjs don't have jquery.easyui

**Comment by sufuf3** [comment]
@liuyun025 Do you mean CDNJS need to host this lib https://github.com/waylau/jquery-easyui?
Thank you.

**Comment by liuyun025** [comment]
yes, i think so. 
we have been told jquery easyui is a good lib for new UI learners in the college. but i can not find jquery easyui in cdnjs. is jquery easyui not so good as the teacher said?

**Comment by sufuf3** [comment]
@liuyun025 because `jquery easyui` just publish on GitHub and use git tag `v1.5.2` in the release version. It's not very famous in GitHub.
And CDNJS use git or npm apto-update to get the release versions, if the versions released from other webpages, CDNJS can't host it automatically.

@PeterDaveHello I know this lib is not reaching 200 stars, but I google this lib and found it popular, many people share how to use it in many articles.
Can we add it?

v1.5.2 release from https://github.com/waylau/jquery-easyui
And need to manually add old versions from http://www.jeasyui.com/download/list.php

**Comment by liuyun025** [comment]
can we host `jquery` `easyui` from the release version published on GitHub?

**Comment by PeterDaveHello** [comment]
@sufuf3 how do you define popular? Isn't popularity try to define the popularity?

**Comment by sufuf3** [comment]
Sorry, this lib https://github.com/waylau/jquery-easyui is not reaching 200 stars, so it's not popular.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
