### ISSUE TITLE
[Request][Author] Add us-util

### ISSUE THREAD

**Issue by fengpan23** [cdnjs/cdnjs#11734]
**Library name:** us-util
**Git repository url:** https://github.com/fengpan23/us-util
**npm package name or url** (if there is one): us-util

**Comment by sufuf3** [comment]
@fengpan23 Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
I think its npm looks good?
https://www.npmjs.com/package/us-util

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
