### ISSUE TITLE
[Request] Add vm-markdown

### ISSUE THREAD

**Issue by luosijie** [cdnjs/cdnjs#11774]
**Library name:** vm-markdown
**Library desctiption:** Markdown for Vue
**Git repository url:** https://github.com/luosijie/vm-markdown
**npm package name or url** : https://www.npmjs.com/package/vm-markdown
**License :** MIT
**Official homepage:** https://luosijie.github.io/vm-markdown/
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
