### ISSUE TITLE
[Request][Author] Add react-jplayer

### ISSUE THREAD

**Issue by MartinDawson** [cdnjs/cdnjs#11834]
**Library name:** react-jplayer
**Library desctiption:** Html5 audio and video player library for React
**Git repository url:** https://github.com/jplayer/react-jPlayer
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-jplayer
**License (List them all if it's multiple):** MIT
**Official homepage:** http://jplayer.org/
**Wanna say something? Leave message here:** 

Not quite hit 800 downloads/month yet but it's based on the original jPlayer and endorsed by it on the main page: https://github.com/jplayer/jPlayer

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
