### ISSUE TITLE
Create a debug flow when getting issues on CDN

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11861]
Which can help users get the issues solved faster.

Basic steps:
 - Test with different browsers, devices
 - Show the result of cdnjs.com/cdn-cgi/trace cdnjs.cloudlfare.com/cdn-cgi/trace 
 - Show traceroute result to cdnjs.com / cdnjs.cloudflare.com

etc.

**Comment by MattIPv4** [comment]
I think better steps would involve the following:

 - Basic browser/device testing
 - Alternative network testing if possible (mobile data connection instead of local network)
 - Results from https://cdnjs.cloudflare.com/cdn-cgi/trace
 - Traceroute to cdnjs.cloudflare.com results
 - If a failed request, FULL request/response headers & resource URL

@PeterDaveHello thoughts?

**Comment by xtuc** [comment]
Users that notice an issue with cdnjs library should open an issue or reach out on twitter. We can ask for me info based on the error
