### ISSUE TITLE
[Request] Add t-scroll

### ISSUE THREAD

**Issue by fawmi** [cdnjs/cdnjs#11891]
**Library name:** t-scroll
**Library description:A modern reveal-on-scroll library with useful options and animations. (Animate Elements On Reveal)
**Git repository url:https://github.com/crazychicken/t-scroll
**npm package name or url** (if there is one): https://www.npmjs.com/package/t-scroll
**License (List them all if it's multiple):MIT License
**Official homepage:https://t-scroll.com/
**Wanna say something? Leave message here:** 

=====================

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
