### ISSUE TITLE
[Request] Add roosterjs

### ISSUE THREAD

**Issue by adriantran** [cdnjs/cdnjs#11983]
**Library name:** roosterjs
**Library description:** roosterjs is a framework-independent javascript rich text editor.
**Git repository url:** https://github.com/Microsoft/roosterjs
**npm package name or url** (if there is one): https://www.npmjs.com/package/roosterjs
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/Microsoft/roosterjs
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ajay2507** [comment]
Can I take this change??

**Comment by sufuf3** [comment]
@adriantran this library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.
this library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

@ajay2507 I think this issue need to be discussed. Because the popularity issue.
Maybe we can wait for the result of this popularity issue?
What do you think?
Many thanks.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days and the lib doesn't have enough notable popularity. cc @PeterDaveHello
