### ISSUE TITLE
[Request][Author] Add ng-virtual-keyboard

### ISSUE THREAD

**Issue by antonio-spinelli** [cdnjs/cdnjs#11997]
**Library name:** ng-virtual-keyboard
**Library description:** An AngularJs Virtual Keyboard Interface
**Git repository url:** https://github.com/antonio-spinelli/ng-virtual-keyboard/
**npm package name or url:** https://www.npmjs.com/package/ng-virtual-keyboard/
**License:** MIT
**Official homepage:** http://antonio-spinelli.github.io/ng-virtual-keyboard/

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
