### ISSUE TITLE
[request] Add wheelzoom

### ISSUE THREAD

**Issue by CharlesNepote** [cdnjs/cdnjs#12018]
The project is well supported since 2012.

- It has a web page: http://www.jacklmoore.com/wheelzoom
- A github repo: https://github.com/jackmoore/wheelzoom
- It's on NPM: https://www.npmjs.com/package/wheelzoom

And the code is clean, thanks @jackmoore.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
