### ISSUE TITLE
[Request] Add bitsharesjs

### ISSUE THREAD

**Issue by ruslansalikhov** [cdnjs/cdnjs#12015]
**Library name:** bitsharesjs
**Library description:** Pure JavaScript Bitshares library for node.js and browsers. Can be used to construct, sign and broadcast transactions in JavaScript, and to easily obtain data from the blockchain via public apis.
**Git repository url:** https://github.com/bitshares/bitsharesjs
**npm package name or url** (if there is one): https://www.npmjs.com/package/bitsharesjs
**License (List them all if it's multiple):** MIT License
**Official homepage:** https://bitshares.org/
**Wanna say something? Leave message here:**

**Comment by sufuf3** [comment]
@ruslansalikhov Many thanks.
Fell free to send a pull request, if you'd like to let this lib be added quickly.
And if you have any question, please let me know. 😃 
Thanks.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
