### ISSUE TITLE
[author] CDNjs seems to have wrong version stored for showdown 1.8.0

### ISSUE THREAD

**Issue by tivie** [cdnjs/cdnjs#12089]
When requesting https://cdnjs.cloudflare.com/ajax/libs/showdown/1.8.0/showdown.min.js the first line of the file tells it actually is version v 1.7.6:

    /*! showdown v 1.7.6 - 24-10-2017 */

see https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/showdown/1.8.0/showdown.js

On further inspection, it's neither version 1.7.6 nor 1.8.0 but an intermediate commit that CDNjs, for some reason, wrongly tagged as v 1.8.0

Original issue: https://github.com/showdownjs/showdown/issues/452

**Comment by sufuf3** [comment]
@tivie Thanks for response.
I found you has added v1.8.0 git tag on https://github.com/showdownjs/showdown/commit/e862e242f7b9186d14b82289828fa099ff799c04 this commit.
And the file https://github.com/showdownjs/showdown/blob/e862e242f7b9186d14b82289828fa099ff799c04/dist/showdown.min.js which as the same with https://cdnjs.cloudflare.com/ajax/libs/showdown/1.8.0/showdown.min.js is in this commit too.

And CDNJS's bot @PeterBot added the release version of the lib so quickly, so that's why CDNJS host the first v1.8.0 git tag not add the files from  [`release v1.8.0`](https://github.com/showdownjs/showdown/commit/13c1766b94828719dc63f15b96d03cc94e446cc3) this commit. (The bot check the new version from new git tag)

Maybe add another git tag and let CDNJS's bot add the new version can solve this issue.
What do you think?
Not sure it's a good solution, but maybe we can discuss about how to deal with this.
If you have any question, please let me know.
I'll do my best to help it.

Many thanks.

@PeterDaveHello would you help out? 
My english is still poor, even if I improve my english recently. 
Hope this comment can be understood.
Thank you very much.

**Comment by PeterDaveHello** [comment]
@tivie we just fetch the versions by tags, so as you can see, the file is in the v1.8.0 tag, that's the reason why.

**Comment by tivie** [comment]
Aww blast! Yeah. I fixed that really quickly, seems @PeterBot is even faster.

> Maybe add another git tag and let CDNJS's bot add the new version can solve this issue.
Well, version 1.8.0 would still be a missmatch in relation to github(bower and stuff) and NPM. 

@sufuf3  Would a pull request with the "fixed" versions be okay? Since the CDNjs repository is HUGE and my PC complained a lot I would have to manually copy/paste the code into github... 

which would result in a PR of 4 commits (instead of one as required in your contributing guide). You could, of course, squash/merge though.

**Comment by tivie** [comment]
@PeterDaveHello I see. Well, seems the only solution is to bump showdown's version and inform users not to use the CDNjs version 1.8.0.

And thanks for the quick reply! :smile:

**Comment by tivie** [comment]
Published version [1.8.1](https://github.com/showdownjs/showdown/releases/tag/1.8.1) which should fix the issue. Feel free to close the issue when you feel it's appropriate

**Comment by sufuf3** [comment]
@tivie Thank you very much.
@PeterDaveHello Thanks a lot.

**Comment by PeterDaveHello** [comment]
@tivie looks added in https://github.com/cdnjs/cdnjs/commit/aecb36a5d40afd09ce72ecde74c2a86e5b89d5aa 👍
