### ISSUE TITLE
[Request] Add luxon

### ISSUE THREAD

**Issue by tuananh** [cdnjs/cdnjs#12220]
**Library name:** luxon
**Library description:** A powerful, modern, and friendly wrapper for Javascript dates and times.
**Git repository url:** https://github.com/moment/luxon
**npm package name or url** (if there is one): https://www.npmjs.com/package/luxon
**License (List them all if it's multiple):** MIT
**Official homepage:** http://moment.github.io/luxon/
**Wanna say something? Leave message here:**

**Comment by sufuf3** [comment]
@tuananh Thank you for your suggestion.
I found this lib provide http://moment.github.io/luxon/global/luxon.js and http://moment.github.io/luxon/global/luxon.min.js which CDNJS can host.
But there is no `luxon.js` and `luxon.min.js` in GitHub repo or npm.
It's a little bit hard for us to add this lib, because we use git auto-update or npm auto-update to get the files from upstream.
Could you discuss with the author to help add these files in GitHub repo or npm?
This will be a great work for us.
Thanks.

**Comment by tuananh** [comment]
@icambron is it possible?

**Comment by icambron** [comment]
I really don't want to put the built files in Github. As for NPM, the CJS "build" is not the same as the one pointed to here.

An idea, though: use the `gh-pages` branch: https://github.com/moment/luxon/tree/gh-pages/global. That branch is what backs the website and I push to it when I release. Right now those aren't tagged with the release numbers, but if I figured out how to add that, would that suffice?
