### ISSUE TITLE
[Request][Author] Add js-fixerr

### ISSUE THREAD

**Issue by anujsinghwd** [cdnjs/cdnjs#12267]
Lightweight and fast validation library for javascript

github Repo - https://github.com/anujsinghwd/js-fixerr
src url - [http://apnanews.co.in/js-fixerr/js-fixerr.min.js](url)
npm link - https://www.npmjs.com/package/js-fixerr

**Comment by anujsinghwd** [comment]
@sufuf3  thanks but still not added

**Comment by sufuf3** [comment]
@anujsinghwd Sorry about that.
As you can see, our team members maintain this open source project by our free time.
And there are not so many people in our team.

Also, there are too many libs waiting for being added.
If you'd like to let your library be added soon.
Maybe sending a pull request could help you solve your expectation.

What do you think?

Really sorry.
But this way may be faster than just opening a request issue, since there are tons of issues.

If you'd like to send a PR, you can refer to the guidelines for contributing.

Many thanks.

**Comment by anujsinghwd** [comment]
thanks for replting @sufuf3. i am waiting to update

**Comment by sufuf3** [comment]
@anujsinghwd I saw there are over 800 downloads in a month two weeks ago.
But now the downloads not reach our popularity. (200 stars on GitHub and 800 downloads in a month) Here is the adding library requirement: https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library

I think we need to waiting for awhile to reach the goal.

Sorry about that.
