### ISSUE TITLE
[Request] Add canvas2image

### ISSUE THREAD

**Issue by AndreCapelache** [cdnjs/cdnjs#12290]
**Library name:** canvas2image
**Library description:** a tool for saving or converting canvas as img
**Git repository url:** https://github.com/hongru/canvas2image
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/hongru/canvas2image
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Hi @AndreCapelache ,
Thanks our suggestion.
But there is no git tag on this repo of lib.

The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on [**git tags**](https://github.com/hongru/canvas2image/tags) so that it can recognize the correct version and automatically update the repo.
Would you discuss with the upstream to add git tags for the repo?

Thank you.
