### ISSUE TITLE
[Request][Author] Add nanoSQL

### ISSUE THREAD

**Issue by ClickSimply** [cdnjs/cdnjs#12358]
Library name: nanoSQL
Library description: A super flexible database/datastore for the client & server.
Git repository url: https://github.com/ClickSimply/Nano-SQL
npm package name or url https://www.npmjs.com/package/nano-sql
License (List them all if it's multiple): MIT
Official homepage: https://nanosql.io
Wanna say something? Leave message here:

Browser friendly builds are always located here:
https://github.com/ClickSimply/Nano-SQL/blob/master/dist/nano-sql.min.js

**Comment by sufuf3** [comment]
Memo: 972 downloads in the last month from npm

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
