### ISSUE TITLE
[Request] Add schnack

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12366]
**Library name:** schnack
**Library description:** Simple node app for Disqus-like drop-in commenting on static websites
**Git repository url:** https://github.com/gka/schnack
**npm package name or url** (if there is one): https://www.npmjs.com/package/schnack
**License (List them all if it's multiple):** [Lil](https://github.com/gka/schnack/blob/master/LICENSE) :https://github.com/jashkenas/lil-license

PS. This is a new license which not in SPDX License List. Also, this should be discussed because this license not in CDNJS's license-list.
Except the license problem, this library is good for beginner to add.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
