### ISSUE TITLE
[Request] Add luxbar

### ISSUE THREAD

**Issue by samvdkris** [cdnjs/cdnjs#12387]
**Library name:** luxbar
**Library description:** Featherweight, Responsive, CSS Only Navigation Bar
**Git repository url:** https://github.com/balzss/luxbar
**npm package name or url** (if there is one): luxbar
**License (List them all if it's multiple):** MIT
**Official homepage:** https://balzss.github.io/luxbar/
**Wanna say something? Leave message here:** I'd really appreciate it if luxbar was added to cdnjs. I currently use rawgit.com, but it's a bit slower than cdnjs. Also, I prefer to just use one cdn for all my CSS and JS frameworks/libraries.

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
