### ISSUE TITLE
[Request] Add react-md-editor

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12383]
**Library name:** react-md-editor
**Library description:** React.js Markdown Editor Component
**Git repository url:** https://github.com/JedWatson/react-md-editor
**npm package name or url** (if there is one):** None
**License (List them all if it's multiple):** MIT
**Official homepage:** https://jedwatson.github.io/react-md-editor/

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
