### ISSUE TITLE
Edit

### ISSUE THREAD

**Issue by pmuia** [cdnjs/cdnjs#12400]
How can I edit this css file

**Comment by sufuf3** [comment]
@pmuia Could you please mention more detail?
What css file you want to edit?
If you want to use the lib's files and edit it, the best way is copy the file and save to your host.
You can edit locally and host the file in your server.

CDNJS is a free and open source project to organize and provide popular front-end web development resources to developers via a fast CDN infrastructure without usage limitations and fees. 
We host the trust libs which have popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.
If you want to know more CDNJS, please take a look the [README](https://github.com/cdnjs/cdnjs#introduction)
Thank you.

**Comment by pmuia** [comment]
Thank you, the file am to edit is hosted on CDNJS is the a way to edit it
from there?

**Comment by sufuf3** [comment]
Let me see if I understand you correctly.

CDNJS doesn't provide the service which can let people modify the lib's files.
Because every lib's files are trusted and all the files are from upstream. (the files is the same as upstream)
So you can't modify the files from CDNJS.
the host of the file in every CDN edge node, if someone touches it, then everyone's web service which using  CDNJS's lib URL will effect in the whole world.

If you want your own front-end file host on CDN service, you could please find other CDN service.
This way, you can copy the code of the lib's file, modify it, and push on other CDN service.

Many thanks.

**Comment by pmuia** [comment]
Thank you we on the same page now

**Comment by extend1994** [comment]
Close the issue since the problem had been solved.
