### ISSUE TITLE
[Request] Add react-big-calendar

### ISSUE THREAD

**Issue by dtmunir** [cdnjs/cdnjs#12401]
**Library name:** react-big-calendar
**Library description:** A power calendar library built in react
**Git repository url:** https://github.com/intljusticemission/react-big-calendar
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-big-calendar
**License (List them all if it's multiple):** MIT
**Official homepage:** http://intljusticemission.github.io/react-big-calendar/
**Wanna say something? Leave message here:** Would love to see this library be served by CDNJS. Right now it's served by jsdlvr, but in a way that I can't use it inside jsfiddle or Codepen

**Comment by sufuf3** [comment]
@dtmunir Cool.
May I ask you that do you want to use js file in front-end?
Because the file of this lib which can be added is `react-big-calendar/lib/css/react-big-calendar.css`, now. (refer from: https://github.com/intljusticemission/react-big-calendar#use-and-setup)
But if you want to add the js file, this lib need to provide the bundle file.
I saw the lib used webpack to generate the `examples/bundle.js`, if this lib can provide the files officially(not just examples), this will be a good news for us.
If the compressed files can be added under `dist` or `build` of the lib's repo, then I think we can add this lib more smooth.

Would you please discuss the issue of js file with the author?
This will be a great work.

Many thanks.
