### ISSUE TITLE
[Request] Add primereact

### ISSUE THREAD

**Issue by hashir-uh** [cdnjs/cdnjs#12470]
**Library name:** primereact
**Library description:** 
**Git repository url:** https://github.com/primefaces/primereact
**npm package name or url** (if there is one): https://www.npmjs.com/package/primereact
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 
any cdn link for adding prime react library in html file

**Comment by extend1994** [comment]
Hi @hashir55 
Do you mean this one?
https://github.com/primefaces/primereact
https://www.npmjs.com/package/primereact

**Comment by hashir55** [comment]
Thanks for the reply.
I would like to include one more question
How can we customize the data table in react js.

On 1 Feb 2018 6:32 p.m., "LboAnn" <notifications@github.com> wrote:

Hi @hashir55 <https://github.com/hashir55>
Do you mean this one?
https://github.com/primefaces/primereact
https://www.npmjs.com/package/primereact

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cdnjs/cdnjs/issues/12470#issuecomment-362259313>, or mute
the thread

**Comment by extend1994** [comment]
@hashir55 So are the urls I proposed what you want?
cdnjs only provide the library from the projects owners, if you want to know how to use the library, go to that repository and ask them would be a good idea. 😉

**Comment by hashir55** [comment]
Yes, thanks a lot.

On 2 Feb 2018 12:31 p.m., "LboAnn" <notifications@github.com> wrote:

@hashir55 <https://github.com/hashir55> So are the urls I proposed what you
want?
cdnjs only provide the library from the projects owners, if you want to
know how to use the library, go to that repository and ask them would be a
good idea. 😉

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cdnjs/cdnjs/issues/12470#issuecomment-362503616>, or mute
the thread
