### ISSUE TITLE
[Request] Add webdnn

### ISSUE THREAD

**Issue by JenGL** [cdnjs/cdnjs#12616]
**Library name:** webdnn
**Library description:**  
WebDNN is an open source software framework for executing deep neural network (DNN) pre-trained model on web browser.
**Git repository url:**  https://github.com/mil-tokyo/webdnn
**npm package name or url:** https://www.npmjs.com/package/webdnn
**License (List them all if it's multiple):**  MIT License
**Official homepage:**  https://mil-tokyo.github.io/webdnn/

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
