### ISSUE TITLE
[Request] Add docson

### ISSUE THREAD

**Issue by thjaeckle** [cdnjs/cdnjs#12752]
**Library name:** docson
**Library description:** Give Docson a JSON schema and it will generate a beautiful documentation.
**Git repository url:** https://github.com/lbovet/docson
**npm package name or url** (if there is one): https://www.npmjs.com/package/docson
**License (List them all if it's multiple):** Apache License 2.0
**Official homepage:** 
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
