### ISSUE TITLE
[Request] Add walkway

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12783]
**Library name:** walkway
**Git repository url:** https://github.com/ConnorAtherton/walkway
**npm package name or url** (if there is one): https://www.npmjs.com/package/walkway.js
**License (List them all if it's multiple):** [MIT](https://github.com/ConnorAtherton/walkway/blob/master/LICENSE.md)
**Official homepage:** http://connoratherton.com/walkway

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
