### ISSUE TITLE
[Author][Request] Add Box-shadows.css

### ISSUE THREAD

**Issue by madeas** [cdnjs/cdnjs#13067]
Library name: Box-shadows.css
Repository: https://github.com/madeas/box-shadows.css
NPM: https://www.npmjs.com/package/box-shadows-css
Homepage: https://madeas.github.io/box-shadows
Licence: MIT

Git stars: 270

**Comment by andrejsharapov** [comment]
Как узнать о результате? Когда будет/или не будет размещена библиотека?

**Comment by andrejsharapov** [comment]
Oh, yeah. How to find out about the result? When the library be placed? Or not be placed.

**Comment by PeterDaveHello** [comment]
@andrejsharapov this library hasn't been added yet, as it's still opened, and without associate pull requests.

Pull requests are always welcome to help add new libraries ;)

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
