### ISSUE TITLE
Update for melonjs

### ISSUE THREAD

**Issue by mrmcgriddles** [cdnjs/cdnjs#13089]
Can there be an update for melonjs?

Latest version is 6.1.0 but the one on the cdnjs is 1.0.1
https://cdnjs.com/libraries/melonjs
vs
https://github.com/melonjs/melonJS/tags

**Comment by sashberd** [comment]
@mrmcgriddles As I understand this lib was added manually each version according to lib build [documentation](https://github.com/melonjs/melonJS/tree/0.9.9#building-melonjs)
@PeterDaveHello Correct me if I wrong.
@mrmcgriddles You are welcome to add version 1.0.2~6.1.0 manually in PR in order to fetch you request.
I will open an issue in cdnjs issues.

**Comment by xtuc** [comment]
melonjs is not configured to be automatically updated. Feel free to send a PR to add the configuration.
