### ISSUE TITLE
Add SPMagic.js

### ISSUE THREAD

**Issue by Sandun-Isuru-Niraj** [cdnjs/cdnjs#13092]
This Library is helpful when you developing the Sharepoint Hosted Addin inside the Sharepoint 2013, 2016 or Sharepoint Online. All necessary functions and operations are bundled into callback requests apart from the traditional Ajax calls.

**Comment by MattIPv4** [comment]
Looks to be https://www.npmjs.com/package/spmagicjs

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
