### ISSUE TITLE
[Request] Add hlsjs-p2p-engine

### ISSUE THREAD

**Issue by snowinszu** [cdnjs/cdnjs#13099]
Library name: hlsjs-p2p-engine
Git repository url: https://github.com/cdnbye/hlsjs-p2p-engine
npm package name or url (if there is one): https://www.npmjs.com/package/cdnbye
License (List them all if it's multiple): MIT
Homepage: https://docs.cdnbye.com/#/en/

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
