### ISSUE TITLE
[Request] Add kinkajs library

### ISSUE THREAD

**Issue by js2me** [cdnjs/cdnjs#13096]
Library name: kinka
Git repository url: https://github.com/acacode/kinka
npm package url(optional): https://www.npmjs.com/package/kinka
Official homepage: https://acacode.github.io/kinka/
Description: web http-client

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
