### ISSUE TITLE
[Request] Add Nimiq Style Library

### ISSUE THREAD

**Issue by MatthewDLudwig** [cdnjs/cdnjs#13104]
Library name: nimiq-style
Git repository url: https://github.com/nimiq/nimiq-style
npm package name or url (if there is one): https://www.npmjs.com/package/@nimiq/style
License (List them all if it's multiple): MIT
Homepage: https://www.nimiq.com

While this individual repository may not meet the requirements of watches / stars the core repository for Nimiq blows the requirement out of the park (https://github.com/nimiq-network/core).  I don't believe the core repository belongs on CDNjs (crypto related so it's best if served from the team's CDN or hosted locally imo) but I imagine the styles will see a great number of downloads in the coming weeks and even more when Nimiq gains any real public attention.  The styles were recently added and are hosted on both NPM and JSDeliver but I prefer CDNjs over JSDeliver.  If there's any chance the core repositories fame could overflow onto the style repository I'd greatly appreciate it.  If not I'll simply reply to this issue when it does meet requirements.

Thanks for the consideration and I appreciate the service you provide!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
