### ISSUE TITLE
Add bootstrap SCSS files

### ISSUE THREAD

**Issue by drauch** [cdnjs/cdnjs#13120]
Although SCSS files will never be served directly to end users, you should seriously consider adding Bootstrap SCSS files to your service.

Tools based upon cdnjs (most prominently Microsoft's [LibMan](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/?view=aspnetcore-2.2)) would then allow to include the SCSS files into an ASP.NET Core Visual Studio project with ease.

If you need more background information on LibMan feel free to ask me anything.

**Comment by PeterDaveHello** [comment]
@drauch thanks for the suggestion, I'm not sure if we can or we will do that, one the problems to have this, is we don't have control on cdnjs.cloudflare.com, due to security reason and ownership, everything on Cloudflare side needs their approvement and implementation, for example, scss is not on the file extention whitelist on the server side, even we add them into the repository, they'll never be served, users will only get 403 denied message, I think @ryankirkman and @terinjokes may be able to help about this part, but I can't guarantee that.

**Comment by MattIPv4** [comment]
Hi there, I have added this file extension request to #13145 where I am keeping track of them all.

**Comment by jerchap** [comment]
> I understand, I recently learned that LibMan is now supporting unpkg as well. Maybe that's the alternative people should use instead of cdnjs.

I have a need for the boostrap scss files as well.  LibMan is so far the only really viable package manager tool because we're doing ASP.Net Core.  I'll have to look into unpkg

**Comment by MattIPv4** [comment]
@jerchap SCSS files show now be served (see #13145) - I'll reopen this so we can track adding them to bootstrap on cdnjs.

**Comment by MattIPv4** [comment]
@jerchap You are welcome to open a PR that updates https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/twitter-bootstrap/package.json to work from the root of the bootstrap repo and then pulls in everything in dist and scss.
