### ISSUE TITLE
[Request] Snackbar

### ISSUE THREAD

**Issue by abdulwaheedsyed** [cdnjs/cdnjs#13188]
Hi, please add this in cdnjs. I think it will be helpful for all.

Library name: Google Material Design Inspired SnackBar Plugin
Git repository url: https://github.com/polonel/SnackBar
npm package url: https://www.npmjs.com/package/node-snackbar
License(s): MIT

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
