### ISSUE TITLE
[Request] Add OpenSheetMusicDisplay

### ISSUE THREAD

**Issue by sebastianhaas** [cdnjs/cdnjs#13183]
Hi! I would like to propose OpenSheetMusicDisplay to be added to cdnjs. It is licensed under MIT license and has more than 200 stars on Github.

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay

Cheers!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
