### ISSUE TITLE
[Request] Please add GitZip

### ISSUE THREAD

**Issue by ttodua** [cdnjs/cdnjs#13205]
Library name: GitZip
Git repository url: https://github.com/KinoLien/gitzip
License (List them all if it's multiple): MIT
Homepage: https://kinolien.github.io/gitzip/

Description: JS library to download GitHub subfolders (and folders of course) as zip (using client-side JS). There is only 1 file, that needs to be put on cdn:
`gitzip/js/API.js`

(  All other files are just 3rd party available libraries, already on cdnjs:
`
https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js
https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js
https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.5/jszip.min.js
`
)

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
