### ISSUE TITLE
[Request] Add next.js

### ISSUE THREAD

**Issue by Potapy4** [cdnjs/cdnjs#13218]
**Library name:** Next.js
**Description:** "Next.js is a minimalistic framework for server-rendered React applications."
**Git repository URL:** https://github.com/zeit/next.js
**npm package name or url (if there is one):** https://www.npmjs.com/package/next
**License:** MIT
**Demo:** https://nextjs.org/

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by LuckyPigeon** [comment]
@Potapy4 I am working on this PR now, but I couldn't find the main js file. Do you have any idea?

**Comment by MattIPv4** [comment]
I'm unsure how this would be hosted on a CDN, a key part of working with next is your local build process?

**Comment by MattIPv4** [comment]
Closing. This doesn't seem like a sensible request at all.
