### ISSUE TITLE
[Request] Add CSV to HTML Table

### ISSUE THREAD

**Issue by ivanhercaz** [cdnjs/cdnjs#13214]
- Library name: CSV to HTML Table
- Description: "Display any CSV file as a searchable, filterable, pretty HTML table".
- Git repository URL: https://github.com/derekeder/csv-to-html-table
- License: MIT
- Demo: http://derekeder.github.io/csv-to-html-table/
----
First of all, thank you very much to the team and contributors of CDNJS! About this library I want to highlight that it has 378 stars in GitHub, so I think it could be added to the CDN if you think it meets the technical requirements.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by ivanhercaz** [comment]
All right, @MattIPv4! I will try to do what you suggest :smile:.

Thank you to all of you for your work to maintain CDNJS.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
