### ISSUE TITLE
[Request] Add create-react-class

### ISSUE THREAD

**Issue by Almo7aya** [cdnjs/cdnjs#13223]
**Library name**: create-react-class
**Description**: "A drop-in replacement for React.createClass."
**npm package name or url** (if there is one): [create-react-class](https://www.npmjs.com/package/create-react-class)
**License**: MIT
**Demo**: [React Docs](https://facebook.github.io/react/docs/react-without-es6.html)

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
