### ISSUE TITLE
[Request] Update graingert-wow

### ISSUE THREAD

**Issue by smkn** [cdnjs/cdnjs#13278]
I'd like you to update graingert-wow.

graingert-wow (https://cdnjs.com/libraries/graingert-wow) has not been updated to the latest version.
Latest version is 1.3.0
https://github.com/graingert/WOW/releases/tag/1.3.0

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by smkn** [comment]
@MattIPv4 I tried but clone too slowly(1% per 1 hour). Really sorry.

**Comment by MattIPv4** [comment]
We update this library through NPM, which does not have the 1.3.0 release: https://www.npmjs.com/package/wow.js

Closing.
