### ISSUE TITLE
[Request] Add Boosted

### ISSUE THREAD

**Issue by ShadCanard** [cdnjs/cdnjs#13289]
**Library name**: Boosted
**Library description**: A rework from Bootstrap with Orange colors, Improved accessibility and custom components
**Git repository url**: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap
**npm package name or url (if there is one)**: npm install boosted
**License (List them all if it's multiple)**: MIT ( https://raw.githubusercontent.com/Orange-OpenSource/Orange-Boosted-Bootstrap/v4-dev/LICENSE )
**Official homepage**: https://boosted.orange.com/
**Wanna say something? Leave message here**:

I'm not a part of their team even though I work for Orange, but their website have some difficulties running their libraries stretch from their sources, so it would help everyone using Boosted to have it hosted on a CDN like yours.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
