### ISSUE TITLE
[Request] emoji-datasource*

### ISSUE THREAD

**Issue by wis** [cdnjs/cdnjs#13291]
here's the package/s' repo: [iamcal/emoji-data](https://github.com/iamcal/emoji-data) it has 1430 stars currently.
emoji-datasource* packages:
```
emoji-datasource
emoji-datasource-apple
emoji-datasource-google
emoji-datasource-twitter
emoji-datasource-facebook
emoji-datasource-messenger
```

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by wis** [comment]
because they're asset packages, they could add up to a 150MB is that an issue/not-ideal with source control?
unpkg already has them, because their system automatically uploads from npm w/o source control.
I found out after that unpkg also depend on Cloudflare, so I can expect the same performance/latency and bandwidth?

**Comment by MattIPv4** [comment]
> because they're asset packages, they could add up to a 150MB is that an issue/not-ideal with source control?

the cdnjs repo is about 200GB in size already, adding new stuff isn't an issue from a size perspective.

> I found out after that unpkg also depend on Cloudflare, so I can expect the same performance/latency and bandwidth?

I am unsure of how unpkg operates, but cdnjs is run directly by Cloudflare on their edge network.

**Comment by xmsz-stu** [comment]
需求更新版本
现在版本已经是15.1.2了
