### ISSUE TITLE
Later I'd like some one to add my library, when I'm done with it.

### ISSUE THREAD

**Issue by prolightHub** [cdnjs/cdnjs#13292]
I'm making a space coordinate library. I'd like some one to put it on here when I'm done.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by prolightHub** [comment]
Hmm, may take me a while actually due to school and such. I bet I'll get around to it eventually.

**Comment by prolightHub** [comment]
Also, I wonder if cdnjs already contains a sort of coordinate library. In that case it wouldn't need to be added...

**Comment by prolightHub** [comment]
Engine Nearing Completion!

**Comment by prolightHub** [comment]
Okay, I think I have it!
https://github.com/prolightHub/CartesianSystemLite

**Comment by prolightHub** [comment]
Yeah, I don't think I'll get enough of popularity right now for it to be added but anyways. I'm out of here.

**Comment by MattIPv4** [comment]
No further progress, closing.
