### ISSUE TITLE
[request] Add coolprop

### ISSUE THREAD

**Issue by doomiris** [cdnjs/cdnjs#13317]
CoolProp is a thermophysical property database and wrappers for a selection of programming environments. It offers similar functionality to REFPROP, but CoolProp is open-source and free. 

Github URL [https://github.com/CoolProp/CoolProp](https://github.com/CoolProp/CoolProp) , currently the project has 236 stars.

please add javascript wrapper, which include below files:
[https://sourceforge.net/projects/coolprop/files/CoolProp/6.2.1/Javascript/](https://sourceforge.net/projects/coolprop/files/CoolProp/6.2.1/Javascript/)
```
coolprop.js
coolprop.wasm
```

Thanks

**Comment by jowr** [comment]
Hi, I am one of the developers (Ian did not work alone) and I was wondering whether you picked the correct URLs. We use sourceforge to distribute binaries and the Javascript files can be found at https://sourceforge.net/projects/coolprop/files/CoolProp/__version_number__/Javascript/, look for example at https://sourceforge.net/projects/coolprop/files/CoolProp/6.2.1/Javascript/, which is the latest release (unfortunately with broken Javascript, but that has been fixed already). The URLs posted above link directly to our build infrastructure and the URLs might change without warning and the server is not available at all times. 

It would be very nice to include this in place for our upcoming release of v6.3.0. Maybe one of the persons following https://github.com/CoolProp/CoolProp/issues/1754 might have an opinion as well. All comments and help are much appreciated.

**Comment by doomiris** [comment]
@jowr I modified the description.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
