### ISSUE TITLE
[Request]  Add vectormap.js

### ISSUE THREAD

**Issue by Johnny-ThinkGeo** [cdnjs/cdnjs#13348]
**Library name:** VectorMap-js
**Git repository url:** https://github.com/ThinkGeo/VectorMap-js
**npm package name or url** (if there is one):  https://www.npmjs.com/package/vectormap-js
**Official homepage:** https://github.com/ThinkGeo/VectorMap-js
**Wanna say something? Leave message here:** N/A

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
