### ISSUE TITLE
SignalR.js update to 2.4.1

### ISSUE THREAD

**Issue by MatthewSteeples** [cdnjs/cdnjs#13370]
Related to #8702. It looks like the bower repository is no longer updated, so the auto update functionality is now broken.

cc @bradygaster 

Please note: Not related to #13198 (that's SignalR for ASP.NET Core)

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Looks like this is now published via NPM, see https://www.npmjs.com/package/signalr
Feel free to PR a change to autoupdate so that it pulls from NPM :)

**Comment by bradygaster** [comment]
Will do @MattIPv4. i'll try to find that file in the long list and update it.

**Comment by PeterDaveHello** [comment]
This is not a bug of us but changes from upstream.

**Comment by MattIPv4** [comment]
@PeterDaveHello What should this be labelled as then? I would consider this a bug in the current configuration of autoupdate for this package?

**Comment by PeterDaveHello** [comment]
I thought we have "request for update" label? Don't know it was removed.

**Comment by MattIPv4** [comment]
@PeterDaveHello Never seen that label, I'll just flag it as a library request.

**Comment by PeterDaveHello** [comment]
I'll add it back, let's not mix different issue the same label.

**Comment by bradygaster** [comment]
@xtuc - i'm waiting on some feedback from cdnjs on how to get our new packages published. ATM it doesn't seem like any of our packages are being updated even when we've submitted months-old pull requests, so i'd like to concentrate on our new APIs before we set up auto-updating on our old ones. open to discussion if you have a need for it to be updated, but atm I don't know how to get anything on cdnjs updated.

**Comment by MattIPv4** [comment]
Hey @bradygaster - the current auto-update bot doesn’t work with new single package.json libraries, not sure why really, it just doesn’t :(

We’re working really hard on a migration of the package.json for cdnjs to a new repository with a new auto-update bot that’ll resolve this ongoing issue.

As such, the best thing to do for now is to submit any PRs as if single package.hson submissions are working, with auto-update etc. and as soon as we get the migration working the new auto-update system will kick in and pick all these up, adding the versioned library files.

**Comment by xtuc** [comment]
Also note that npm works currently with the new autoupdater. If you move your package to autoupdate via npm we can enable the new bot
