### ISSUE TITLE
Auto-update should work when library file structure changes

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13392]
## Idea

Currently, @PeterBot will fail to auto-update a library even if the file map is correct but if the file structure has changed (new files/directories picked up by the file map or files that no longer exist).

This requires manual intervention where a maintainer will need to manually update the library version on cdnjs so that @PeterBot can then automatically update new versions again.

It would be awesome if the auto-update scripts could be updated so that they handle new files/directories and any files/directories that get removed without issue.

 - Auto-update should work with new files/directories in the existing file map
 - Auto-update should work with removed files/directories from the file map

## Relevant Scripts

Overall update bot script: https://github.com/cdnjs/bot/blob/master/bot
NPM auto-update script: https://github.com/cdnjs/cdnjs/blob/master/auto-update.js
Git auto-update script: https://github.com/cdnjs/autoupdate/blob/master/autoupdate.js (https://github.com/cdnjs/autoupdate/blob/master/updaters/git.js)

**Comment by Jitsusama** [comment]
Hello @MattIPv4;

I’m willing to give this a go, but I’m not at all familiar with how cdnjs works. Is there any documentation that I can read through so that I can better understand the problem and how it relates to how these scripts interact with each other today? Even some details on how I could setup my environment to replicate the issue and test possible solutions against?

**Comment by MattIPv4** [comment]
Unfortunately, I'm not aware of any docs relating to these scripts, though I defer to @PeterDaveHello as he's the one that runs them normally.

**Comment by MattIPv4** [comment]
🎉
