### ISSUE TITLE
[Request] Add Betterial

### ISSUE THREAD

**Issue by TheComputerM** [cdnjs/cdnjs#13395]
Library name : Betterial
Repository url: [https://github.com/TheComputerM/betterial](https://github.com/TheComputerM/betterial)
NPM Package: [https://www.npmjs.com/package/betterial](https://www.npmjs.com/package/betterial)
Homepage: [https://thecomputerm.github.io/betterial/](https://thecomputerm.github.io/betterial/)

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
