### ISSUE TITLE
[Request] Add SimpleLightbox

### ISSUE THREAD

**Issue by vlasscontreras** [cdnjs/cdnjs#13396]
**Library Name:** SimpleLightbox
**Git Repository URL:** https://github.com/dbrekalo/simpleLightbox
**NPM Package URL:** https://www.npmjs.com/package/simple-lightbox
**License(s):** MIT
**Official Homepage:** https://dbrekalo.github.io/simpleLightbox/

_Not to be confused with [andreknieriem's Simple Lightbox](https://github.com/andreknieriem/simplelightbox) which is [already issued](https://github.com/cdnjs/cdnjs/issues/6690) and [published](https://cdnjs.com/libraries/simplelightbox)._

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by xtuc** [comment]
the PR has been merged. The package should be available on the cdn.
