### ISSUE TITLE
[Request] Upgrade mermaid to 8.2.3

### ISSUE THREAD

**Issue by jackycute** [cdnjs/cdnjs#13416]
Library name: mermaid
Git repository url: knsv/mermaid
npm package name or url (if there is one): npmjs.com/package/mermaid
License (List them all if it's multiple): MIT knsv/mermaid:LICENSE@master 
Official homepage: mermaidjs.github.io
Wanna say something? Please upgrade this lib from 8.2.2 to 8.2.3

Thank you!

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by jackycute** [comment]
Hi @MattIPv4, I've opened a PR for this, please take a look.
Thanks!

**Comment by jackycute** [comment]
Close since it has been added.
