### ISSUE TITLE
[Request] Add ckeditor5

### ISSUE THREAD

**Issue by programad** [cdnjs/cdnjs#13414]
**Library name:** https://cdn.ckeditor.com/ckeditor5/10.0.0/classic/ckeditor.js
**Library description:** A set of ready-to-use rich text editors created with a powerful framework. Made with real-time collaborative editing in mind.
**Git repository url:** https://github.com/ckeditor/ckeditor5
**npm package name or url (if there is one):** https://www.npmjs.com/package/ckeditor5
**License (List them all if it's multiple):** https://github.com/ckeditor/ckeditor5/blob/master/LICENSE.md
**Official homepage:** https://ckeditor.com/ckeditor-5/
**Wanna say something? Leave message here:** The ckeditor5 package is just the evolution of ckeditor witch changed major version. it is natural to include it on cdnjs.

@PeterDaveHello @extend1994 please, review this request.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by LuckyPigeon** [comment]
@programad I want to work on this PR, and I want to know the name of main javascript file, thanks!

**Comment by programad** [comment]
> @programad I want to work on this PR, and I want to know the name of main javascript file, thanks!

Thank you for this, sir. The main javascript is ckeditor.js

The latest version is v15: https://github.com/ckeditor/ckeditor5/releases/tag/v15.0.0
