### ISSUE TITLE
[Request] Add jsonwebtoken

### ISSUE THREAD

**Issue by antoniogott** [cdnjs/cdnjs#13421]
**Library name**: jsonwebtoken
**Library description**: An implementation of JSON Web Tokens. This was developed against draft-ietf-oauth-json-web-token-08. It makes use of node-jws.
**Git repository url**: https://github.com/auth0/node-jsonwebtoken
**npm package name or url (if there is one)**: jsonwebtoken
**License (List them all if it's multiple)**: MIT
**Official homepage**: https://github.com/auth0/node-jsonwebtoken#readme
**Wanna say something? Leave message here**: This is a very popular and useful library for dealing with JWT, including signing them, and I was surprised to not see it already on cdnjs.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by LuckyPigeon** [comment]
@antoniogott Are you working on this? I need this library as well, if it is same to you, I can work on this library.

**Comment by antoniogott** [comment]
Currently I do not have the time to spare, I just thought it should be added since it's very popular. Feel free to do it!
