### ISSUE TITLE
[Request] Add vue-clipboard2

### ISSUE THREAD

**Issue by reefqi037** [cdnjs/cdnjs#13434]
**Library name:**
vue-clipboard2

**Library description:**
A simple vuejs 2 binding for clipboard.js

**Git repository url:**
[vue-clipboard2](https://github.com/Inndy/vue-clipboard2)

Dist files for inclusion:
[vue-clipboard2/dist/](https://github.com/Inndy/vue-clipboard2/tree/master/dist)

**npm package name or url:**
[vue-clipboard2](https://www.npmjs.com/package/vue-clipboard2)

**Homepage:**
https://vue-clipboard2.inndy.tw

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/vue-clipboard2
