### ISSUE TITLE
[Request][Author] Add loading-attribute-polyfill

### ISSUE THREAD

**Issue by mfranzke** [cdnjs/cdnjs#13441]
Library name: loading-attribute-polyfill
Library description: Fast and lightweight vanilla JavaScript polyfill for the native behaviour to load elements right before they enter the viewport.
Git repository url: https://github.com/mfranzke/loading-attribute-polyfill
npm package name or url (if there is one): https://www.npmjs.com/package/loading-attribute-polyfill
License: MIT

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
