### ISSUE TITLE
[Request] Add smc-fonts

### ISSUE THREAD

**Issue by subins2000** [cdnjs/cdnjs#13443]
**Library name**: smc-fonts
**Library description**: Web fonts made by Swathanthra Malayalam Computing Team to be used in websites
**Git repository url**: https://gitlab.com/smc/fonts
**npm package name or url (if there is one)**:
**License (List them all if it's multiple)**: SIL Open Font License 1.1
**Official homepage**: https://smc.org.in/fonts
**Wanna say something? Leave message here**: SMC is the largest Free Software community project in India. Its fonts are used by millions around the world.

**Comment by MattIPv4** [comment]
I do not see how the is a valid JS/CSS package that we can host @subins2000 ?

**Comment by subins2000** [comment]
@MattIPv4 It's a font CSS package like https://cdnjs.com/libraries/hack-font

**Comment by MattIPv4** [comment]
@subins2000 What you've linked to is a GitLab projects group, I don't see how that is a single package that we could host. It also does not appear to meet our popularity criteria.

**Comment by subins2000** [comment]
@MattIPv4 We will make a package that will contain all those fonts there in that project group. I can make a PR to cdnjs with the package. Would like to know if it'd be accepted.

Here's SMC's old GitHub org (for the popularity reference) : https://github.com/smc?tab=repositories

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄

**Comment by subins2000** [comment]
@MattIPv4 Hi

To prove popularity of the SMC fonts package, here's the [one hosted in JSDELIVR](https://www.jsdelivr.com/package/gh/kollavarsham/smc-webfonts). It has 7k hits/month.
