### ISSUE TITLE
[Requst] Add webcodecamjs

### ISSUE THREAD

**Issue by ihsinhw** [cdnjs/cdnjs#13456]
Library name: webcodecamjs
Library description: 1d barcode webrtc reader
Git repository url: https://github.com/andrastoth/webcodecamjs
npm package name or url (if there is one): 
License (List them all if it's multiple): MIT
Official homepage: http://atandrastoth.co.uk/

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
