### ISSUE TITLE
[Requst] Add embetty

### ISSUE THREAD

**Issue by theel0ja** [cdnjs/cdnjs#13454]
**Library name:** Embetty
**Library description:** Embetty displays remote content like tweets or YouTube videos without compromising your privacy.
**Git repository url**: https://github.com/heiseonline/embetty
**npm package name or url** (if there is one): https://www.npmjs.com/package/@heise/embetty
**License (List them all if it's multiple):** MIT
**Official homepage:** https://www.heise.de/embetty (in German)

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by ByrenHiggin** [comment]
Working on it now! 😊

**Comment by xtuc** [comment]
@ByrenHiggin did you send a PR? do you need help?

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/Embetty
