### ISSUE TITLE
Update jQuery Backstretch

### ISSUE THREAD

**Issue by sam327** [cdnjs/cdnjs#13478]
Can we get the main version of jquery backstretch updated to the very last release, which is v2.1.17?

There's the v2.0.4 of jquery backstretch here: https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js

And a 2.1.15 fork here: https://cdnjs.cloudflare.com/ajax/libs/danielgindi-jquery-backstretch/2.1.15/jquery.backstretch.min.js

But last Nov, the 2.1.15 edits got rolled into the main line. So I think 2.1.17 is the very latest (and last) version of the plugin.

Library name: jquery.backstretch
Git repository url: https://github.com/jquery-backstretch/jquery-backstretch
License(s): MIT

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by sam327** [comment]
No worries. Thank you.

Um, update this though. Looks like backstretch just updated to **2.1.18** in the last week (after years of nothing). So let's please go with THAT. Whatever the absolute latest happens to be if/when you get there.

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/jquery-backstretch
