### ISSUE TITLE
[Request] Add vue-multiselect

### ISSUE THREAD

**Issue by cdukes** [cdnjs/cdnjs#13475]
Library name: vue-multiselect
Library description: Universal select/multiselect/tagging component for Vue.js 
Git repository url: https://github.com/shentao/vue-multiselect
npm package name or url (if there is one): https://www.npmjs.com/package/vue-multiselect
License (List them all if it's multiple): https://github.com/shentao/vue-multiselect/blob/master/LICENSE
Official homepage: https://vue-multiselect.js.org/

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/vue-multiselect
