### ISSUE TITLE
IView 4.0 has been released, hope to join in

### ISSUE THREAD

**Issue by jzsjiale** [cdnjs/cdnjs#13518]
IView 4.0 has been released, hope to join in。

Aresn, author of iView, founded Beijing view Update Technology Co., Ltd. in 2019, and started to maintain iView and its related software freely and full-time. The view UI is the original iView, officially renamed view UI from October 2019, and uses a new logo. The author of iView will continue to develop iView 4.0 and subsequent versions in the new warehouse **[https://github.com/view-design/viewui](https://github.com/view-design/viewui)**, as well as maintenance work. The original warehouse iView author no longer submits content.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
