### ISSUE TITLE
datatables has a new version

### ISSUE THREAD

**Issue by cybernet** [cdnjs/cdnjs#13519]
1.19.20 has been released, please update :)

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Please see #13524

**Comment by xtuc** [comment]
Closing in favor of https://github.com/cdnjs/cdnjs/issues/13667

**Comment by cybernet** [comment]
thanks 🙏
