### ISSUE TITLE
popper.js 1.16.0 missing

### ISSUE THREAD

**Issue by XhmikosR** [cdnjs/cdnjs#13606]
I've seen #13524, just wanted to track this.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by XhmikosR** [comment]
Err it's not a new library request. Popper js already is on cdnjs but it's
outdated

**Comment by MattIPv4** [comment]
I use the same macro response for both as the same principles apply. It needs a PR to manually bring in the missing versions and to update whatever auto-update config may be present on the library to ensure it is correct for the recent versions.

**Comment by XhmikosR** [comment]
We'll see then. I'm having trouble cloning th4 repo and I'm unfamiliar with
the process. Also I thought the process was automatic?

**Comment by MattIPv4** [comment]
If you wish to contribute the change yourself, I would suggest doing it through the GitHub website as the repository is in excess of 200GB to clone.

Yes, the entire concept of auto-update is that it is automatic, but if the file structure of the library changes, then the auto-update config will no longer be valid and so a human will need to step in to rectify this by manually adding the recent versions and correctly the config.

**Comment by XhmikosR** [comment]
NP, I will give it a go via the web interface and see how it goes although I'm definitely not familiar with the process.

**Comment by XhmikosR** [comment]
Unfortunately, I can't seem to be able to make it work via the Web interface...

Searching for "popper" in my fork returns zero results and the ajax/libs folder is limited: `Sorry, we had to truncate this directory to 1,000 files. 2,462 entries were omitted from the list.`

I'm unsure how to do it via the web interface which I personally have not used before.

**Comment by MattIPv4** [comment]
Once you're in the ajax/libs folder, you should just be able to stick `/popper` on the end of the URl in the browser to get into the folder.

**Comment by XhmikosR** [comment]
So, it seems the new versions are uploaded, they are just not on the live site

https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/popper.js
