### ISSUE TITLE
Dash.js 3.0.1 missing

### ISSUE THREAD

**Issue by olafcm** [cdnjs/cdnjs#13638]
npm autoupdate is enabled, see: https://cdnjs.com/libraries/dashjs
but version 3.0.1 (https://www.npmjs.com/package/dashjs) is missing, see: https://github.com/cdnjs/cdnjs/tree/5eba365ae67cfa323dbb69fe0c77cfc7eabb1955/ajax/libs/dashjs

Can this be resolved?
How does that work with the new cdnjs bot?

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by olafcm** [comment]
I think this library should just auto-update, how to analyze why the new cdnjs bot failed to add the new version of this library?

**Comment by MattIPv4** [comment]
Auto-update config: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/dashjs/package.json#L18-L25

Files in 3.0.0:
```
dash.all.debug.js             dash.all.min.js.map           dash.mediaplayer.debug.js.map dash.mss.debug.js             dash.mss.min.js.map           dash.protection.min.js        dash.reporting.debug.js.map
dash.all.debug.js.map         dash.d.ts                     dash.mediaplayer.min.js       dash.mss.debug.js.map         dash.protection.debug.js      dash.protection.min.js.map    dash.reporting.min.js
dash.all.min.js               dash.mediaplayer.debug.js     dash.mediaplayer.min.js.map   dash.mss.min.js               dash.protection.debug.js.map  dash.reporting.debug.js       dash.reporting.min.js.map
```

Files in 3.0.1:
```
dash.all.debug.js             dash.all.min.js.map           dash.mediaplayer.debug.js.map dash.mss.debug.js             dash.mss.min.js.map           dash.protection.min.js        dash.reporting.debug.js.map
dash.all.debug.js.map         dash.d.ts                     dash.mediaplayer.min.js       dash.mss.debug.js.map         dash.protection.debug.js      dash.protection.min.js.map    dash.reporting.min.js
dash.all.min.js               dash.mediaplayer.debug.js     dash.mediaplayer.min.js.map   dash.mss.min.js               dash.protection.debug.js.map  dash.reporting.debug.js       dash.reporting.min.js.map
```

These actually appear to be identical, so there is no reason the auto-update bot should've failed here and it shouldn't require manual intervention to resolve.

Any ideas @xtuc?

**Comment by xtuc** [comment]
The bot addedd `v3.0.1`

**Comment by olafcm** [comment]
Perfect :-)
