### ISSUE TITLE
Git auto-update: OpenPGP.js not updating

### ISSUE THREAD

**Issue by saulchristie** [cdnjs/cdnjs#13634]
OpenPGP.js seem to have done some refactoring when moving from 4.6.2 to 4.7.0 so the automated updates at cdnjs.com have stopped. Presumably needs a PR.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by xtuc** [comment]
The bot added
```
    Add openpgp v4.6.2
    Add openpgp v4.6.1
    Add openpgp v4.6.0
```

but no v4.7 so far

**Comment by MattIPv4** [comment]
@xtuc this might need some more digging. v4.7.0 any many subsequent versions are tagged, with the `dist` dir present: https://github.com/openpgpjs/openpgpjs/tree/v4.7.0/dist

The auto-update config is set to pull in everything from `dist`, so it seems like its the bot that's getting stuck somewhere? https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/openpgp/package.json

**Comment by xtuc** [comment]
I moved the package to the new bot. It pushed new versions
