### ISSUE TITLE
hls.js 0.13.0 missing

### ISSUE THREAD

**Issue by olafcm** [cdnjs/cdnjs#13645]
npm autoupdate is enabled, see: https://cdnjs.com/libraries/hls.js
but version 0.13.0 (https://www.npmjs.com/package/hls.js) is missing, see: https://github.com/cdnjs/cdnjs/tree/9b5c639c91417de6cb5c80090b5759649ef49135/ajax/libs/hls.js

Can this be resolved?
How does that work with the new cdnjs bot?

**Comment by MattIPv4** [comment]
Auto-update config: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/hls.js/package.json#L20-L28

Files in 0.12.4:
```
hls-demo.js          hls-demo.js.map      hls.js               hls.js.map           hls.light.js         hls.light.js.map     hls.light.min.js     hls.light.min.js.map hls.min.js           hls.min.js.map
```

Files in 0.13.0:
```
config.d.ts          errors.d.ts          hls-demo.js          hls.d.ts             hls.js.map           hls.light.js.map     hls.light.min.js.map hls.min.js.map       loader               task-loop.d.ts       utils
controller           event-handler.d.ts   hls-demo.js.map      hls.js               hls.light.js         hls.light.min.js     hls.min.js           is-supported.d.ts    observer.d.ts        types
```

The file structure has changed, so this will require a manual pull request to add the new version and ensure the file map is correct.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by olafcm** [comment]
I created a pull request.
This is a top 10 npm package, hopefully it can be updated soon now.
Thank you :-)

**Comment by xtuc** [comment]
The bot added the following versions
```
    Add hls.js v0.13.1
    Add hls.js v0.13.0-beta.1

```

**Comment by olafcm** [comment]
Great, thank you!
