### ISSUE TITLE
vue 2.6.11 missing

### ISSUE THREAD

**Issue by Mister-Hope** [cdnjs/cdnjs#13643]
Links are unavilable

https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.common.prod.js

while 

https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.common.prod.js

working

**Comment by MattIPv4** [comment]
Files in 2.6.11:

```
vue.common.js              vue.esm.browser.js         vue.esm.js                 vue.min.js                 vue.runtime.common.js      vue.runtime.esm.js         vue.runtime.min.js
vue.common.dev.js          vue.common.prod.js         vue.esm.browser.min.js     vue.js                     vue.runtime.common.dev.js  vue.runtime.common.prod.js vue.runtime.js
```

Files in 2.6.10:
```
vue.common.js              vue.esm.browser.js         vue.esm.js                 vue.min.js                 vue.runtime.common.js      vue.runtime.esm.js         vue.runtime.min.js
vue.common.dev.js          vue.common.prod.js         vue.esm.browser.min.js     vue.js                     vue.runtime.common.dev.js  vue.runtime.common.prod.js vue.runtime.js
```

Seem to be identical, auto-update config seems fine still: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/vue/package.json#L13-L21

Any ideas @xtuc?

**Comment by Mister-Hope** [comment]
Excuse me, since vue is popular, and 2.6.11 has a security fix, could you update it manually fist?

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by xtuc** [comment]
The bot committed the version `v2.6.11`
