### ISSUE TITLE
AngularJS 1.7.9 is missing

### ISSUE THREAD

**Issue by wolfet** [cdnjs/cdnjs#13648]
AngularJS version 1.7.9 was released on 11/19, but is not available at https://cdnjs.com/libraries/angular.js.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by chinjon** [comment]
Is there an ETA on this? Thanks in advance.

**Comment by MattIPv4** [comment]
cc @xtuc - I think this will be one of the issues that should resolve itself when we remove the auto-update checks. Do you have a rough eta that you could share on that?

**Comment by xtuc** [comment]
The lib is not configured to automaticaly update.

Please check https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md, https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md and send a PR
