### ISSUE TITLE
dc.js not updating anymore

### ISSUE THREAD

**Issue by gordonwoodhull** [cdnjs/cdnjs#13657]
Ever since the CDNJS crisis a few months ago, `dc` has stopped updating.

Since then we have released 3.1.9, some 4.0 betas, and I'm releasing 4.0 today. These do not appear on cdnjs.com.

I am the maintainer. What do I need to do to get dc published automatically when I publish to npm?

Thanks so much!

**Comment by MattIPv4** [comment]
dc@3.1.8: `22 directories, 269 files`
dc@3.1.9: `22 directories, 271 files`

Looks like some extra files were published in 3.1.9, which will cause the current auto-update bot to simply refuse to update. We're looking to fix this but you can submit a PR to manually add the missing versions.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by xtuc** [comment]
Since the bot added `v3.1.9`, but no `v4` were committed.

**Comment by xtuc** [comment]
```
4.0.0-beta.1: no files matched the pattern
4.0.0-beta.2: no files matched the pattern
4.0.0-beta.3: no files matched the pattern
4.0.0-beta.4: no files matched the pattern
4.0.0-beta.5: no files matched the pattern
4.0.0: no files matched the pattern
```

Please update the pattern in https://github.com/cdnjs/packages/blob/master/packages/d/dc.json#L30-L36
```

**Comment by gordonwoodhull** [comment]
Thanks for your help getting dc.js back into CDNJS.

Indeed the build artifacts moved as of release 4.0. But we are still maintaining 3.x. Is there a way to have a different `npmFileMap` for different versions?

**Comment by xtuc** [comment]
If you change the `npmFileMap`, only new versions will have the map applied. Existing versions on the cdnjs will never get changed. Would you mind sending a PR?

**Comment by gordonwoodhull** [comment]
Right, but I’m trying to say that we will continue to create 3.x releases. 3.x is the last to support IE.

I will be glad to do a PR once I figure out the right way to do this. Thanks!!

**Comment by MattIPv4** [comment]
We can use multiple file maps to pull in both 3.x & 4.x :)
