### ISSUE TITLE
[request][author] infinite ajax scroll 3

### ISSUE THREAD

**Issue by fieg** [cdnjs/cdnjs#13655]
**Library name**: Infinite Ajax Scroll
**Library description**: Turn your existing pagination into infinite scrolling pages with ease
**Git repository url**: https://github.com/webcreate/infinite-ajax-scroll
**Npm package url**: https://www.npmjs.com/package/@webcreate/infinite-ajax-scroll
**License**: AGPL, Commercial License
**Official homepage**: https://infiniteajaxscroll.com

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by xtuc** [comment]
The bot published new versions
