### ISSUE TITLE
Add mmenu.js (replacement for jQuery.mmenu)

### ISSUE THREAD

**Issue by FrDH** [cdnjs/cdnjs#13651]
Hi,
Some time ago the jQuery.mmenu plugin changed its name to mmenu.js (it no longer uses jQuery).

**Comment by MattIPv4** [comment]
As cdnjs has no process in place for setting up redirects, I think it'd be best to treat this as a new library request for mmenu.js instead of the existing jQuery.mmenu

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
