### ISSUE TITLE
layer v3.1.1 is missing

### ISSUE THREAD

**Issue by treadstoner** [cdnjs/cdnjs#13656]
Layer version 3.1.1 was released for almost three years, but is not available at [https://cdnjs.com/libraries/layer](https://cdnjs.com/libraries/layer). You can download the new version of "Layer" by [this link](http://res.layui.com/static/download/layer/layer-v3.1.1.zip), Hope the "Layer" will be updated in the near future, thank you!

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by xtuc** [comment]
`layer` isn't configured to autoupdate automaticaly. Please send a PR to add the autoupdate (preferably via npm)
