### ISSUE TITLE
Library Update Request - PrismJs

### ISSUE THREAD

**Issue by DM2489** [cdnjs/cdnjs#13664]
Hi,

The CDN version for PrismJs is a few versions behind now. Would it be possible to get it updated?

https://cdnjs.com/libraries/prism/

https://github.com/PrismJS/prism/releases

**Comment by MattIPv4** [comment]
Version 1.17.1 (last version cdnjs has): `24 directories, 438 files`
Version 1.18.0 (next version after 1.17.1): `28 directories, 479 files`

The file structure of the library has changed, which means that the auto-update bot will refuse to update to this version. Hopefully, this will be fixed in the near future, but for now the solution is a manual PR to this repository to add the correct files for the new versions.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by xtuc** [comment]
Prism v1.19.0 was addedd in 61aba0dd0085fb32681b3b1863986a0790897b61 and will be available on the cdn shortly.
