### ISSUE TITLE
billboard.js is not updating

### ISSUE THREAD

**Issue by netil** [cdnjs/cdnjs#13661]
The [`billboard.js`](https://cdnjs.com/libraries/billboard.js) (added by #11413) library stopped updating since `v1.10.2` release. (The latest is `v1.11.1`)

Do I make some updates or some configuration request?

Thanks!

**Comment by MattIPv4** [comment]
billboard.js @ 1.10.2: `18 directories, 103 files`
billboard.js @ 1.11.0-next.1 `20 directories, 109 files`

Looks like some extra files were published in 1.11.0-next.1, which will cause the current auto-update bot to simply refuse to update. We're looking to fix this but you can submit a PR to manually add the missing versions.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by netil** [comment]
Thank @MattIPv4 for the follow-up.

> Looks like some extra files were published in 1.11.0-next.1, which will cause the current auto-update bot to simply refuse to update.

The auto-update will refuse when `dist` files count aren't same with the previous version?
Because according the new release, new files can be added and it will be an tedious task if need to send manual PR whenever file number changes.

BTW, following the guideline, added `npmName` and `npmFileMap` key to project's package.json.
- https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md#23-auto-update-example

**Comment by MattIPv4** [comment]
This is something that we're looking to change soon, so that auto-update won't care about changes to the file structure and will always update libraries.

**Comment by xtuc** [comment]
The bot added the following versions
```
    Add billboard.js v1.12.0-next.1
    Add billboard.js v1.11.0-next.1
    Add billboard.js v1.11.0-next.2
    Add billboard.js v1.11.0-next.3
    Add billboard.js v1.11.0-next.4
    Add billboard.js v1.11.0-next.5
    Add billboard.js v1.11.0-next.6
    Add billboard.js v1.11.0-next.7
    Add billboard.js v1.11.0
    Add billboard.js v1.11.1
```
