### ISSUE TITLE
Add QCObjects framework

### ISSUE THREAD

**Issue by jeanmachuca** [cdnjs/cdnjs#13679]
Add QCObjects framework

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Ah, looks like you already have a PR open!

**Comment by jeanmachuca** [comment]
Hello, I can see the PR was merged but QCObjects is still not being yet shown by Algolia search results. Is it needed any internal process pending ?

**Comment by MattIPv4** [comment]
As mentioned in https://github.com/cdnjs/cdnjs/pull/13658#issuecomment-584048082, single package.json additions aren't currently being picked up by the auto-update bot.  We're currently working to get this running again :)

**Comment by MattIPv4** [comment]
Closing this as the library has been added in https://github.com/cdnjs/cdnjs/pull/13680
