### ISSUE TITLE
Add forked jQuery UI Layout for jQuery 3

### ISSUE THREAD

**Issue by tliron** [cdnjs/cdnjs#13688]
Unfortunately, the main jQuery Layout plugin has ceased development in 2016 and the "official" version at 1.4.3 is stuck at requiring jQuery 2.

Please consider adding the [fork](https://github.com/GedMarc/layout). The fork has continued the original version scheme and is now at 1.7.0.2. I'm not sure if it's best to continue using the same name here or a different name, possibly "jquery-ui-layout" instead of "jquery-layout".

Thank you for this excellent service!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄

**Comment by tliron** [comment]
It is not my work, it is someone else's...
