### ISSUE TITLE
OpenLayers has stopped autoupdating

### ISSUE THREAD

**Issue by Tugzrida** [cdnjs/cdnjs#13701]
cdnjs currently has both openlayers and ol3 pointing to the same deprecated [`openlayers` package on NPM](https://www.npmjs.com/package/openlayers).

ol3 is an older name, so I don't think fixing ol3 in cdnjs is needed, but fixing openlayers most certainly is - the current release is 6.2.1 and cdnjs is stuck at 4.6.5.

The new npm package is just called `ol`, and I would've just submitted a pull request to fix that, however the packaging has changed and the dist files (ol.js and ol.css) are no longer in the npm package, as the project is now modular.

The compiled dist files are still available in the dist zip on [Github releases for openlayers](https://github.com/openlayers/openlayers/releases), but I don't know how to integrate that with cdnjs, or if using the compiled files is even the right way. I'm happy to write a pull request for this, but I'll need a bit of guidance to get started.

**Comment by MattIPv4** [comment]
Hi there @Tugzrida,

For cdnjs auto-update, the files either need to present within an NPM package or present in a repo and tagged with a semver release.

It looks like the GH repo doesn't actually contain the compiled versions in the tag, only in the published GitHub release, so we won't be able to use that.

The best thing here might just be to update `openlayers` to target the new `ol` NPM package and update the filemap used in the auto-update config so that we pull in all the module files within the package.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by Tugzrida** [comment]
As far as I can tell, all files from the NPM package are required except `README.md`, `package.json` and the whole `src/` folder. There's a vast number of these files, and they aren't minified, so the better option may be manual updates from the release compiled files. If going ahead with the package is ok, then I haven't been able to figure out a glob that works taking into account the above exclusions.

**Comment by MattIPv4** [comment]
Unfortunately we are no longer supporting manual updates to cdnjs, all updating must be done through auto-update configs and the bot.

Yeah, I'm also not sure about the needed glob here. `*@(.css|.js)?(.map)` would match all files needed at the root of the package, but I'm not sure about a way to use globstar whilst excluding `src`.

**Comment by Tugzrida** [comment]
Yes, excluding `src` was the problem that I had, as there are multiple other subfolders that are required.

Additionally, all of the files in NPM appear to be unminified. Having a look at the compiled files provided in the releases, it looks like they're made with Webpack. I'm not very familiar with modular js, but I'm guessing there's not really a way to integrate that in cdnjs. Is it common to ask the project to provide an alternate release mechanism for cdnjs? Otherwise, I'm not really sure which way to go.

**Comment by MattIPv4** [comment]
It might be worth reaching out on their repo and seeing if they could include bundled versions of the library in their NPM releases.

**Comment by Tugzrida** [comment]
Well openlayers/openlayers#10790 was closed pretty quickly. Apparently, use of the full build is now discouraged. The openlayers-provided jsDelivr links use the [openlayers website repo](https://github.com/openlayers/openlayers.github.io/tree/master/en), but this repo doesn't have releases. I can't really see a way forward to get Openlayers on CDNJS, so unless there are any other ideas, I'll close this issue. Might be worth adding a message to openlayers and ol3 in CDNJS about this if possible so people don't start using old versions.

**Comment by MattIPv4** [comment]
Yeah, I think given the situation we don't really have a way to provide new versions on cdnjs via auto-update. As such, I am going to close this issue for now.

We don't currently have a way to provide custom messaging on libraries on the website, though I will consider this during the redesign.

**Comment by xtuc** [comment]
Maybe we can add a note in the package's description?
