### ISSUE TITLE
How can i request the add of a .js library?

### ISSUE THREAD

**Issue by NervenCid** [cdnjs/cdnjs#13715]
Hello:

I'm working on mqtt.js: 

https://github.com/mqttjs/MQTT.js

And i found that it can be used from the client side:

https://github.com/mqttjs/MQTT.js#browser

And it seems that it already have a Cdn version:

https://unpkg.com/mqtt@3.0.0/dist/mqtt.min.js

I wonder if it is possible to upload this library to your search engine

Thank you and sorry for the english

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
