### ISSUE TITLE
New Library Request: loading-bar

### ISSUE THREAD

**Issue by bernd-wechner** [cdnjs/cdnjs#13717]
There is beautiful self contained library here:

https://github.com/loadingio/loading-bar

Which meets your requirements (over 200 github stars, can't see npm downloads)

You already host:

https://cdnjs.com/libraries/progressbar.js
https://cdnjs.com/libraries/angular-loading-bar

but to be honest loading-bar looks a lot better and likely to take off.  It has an MIT license, and has no external dependencies. It's not large 14kB unzipped, but large enough to benefit from the grace of CDN hosting so that as it gains popularity clients aren't all reloading it from individual servers but using cached copies of CDN provided copies (you can tell I'm a CDN fan for better UX).

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
