### ISSUE TITLE
Update Request: Add AngularJS 1.7.9

### ISSUE THREAD

**Issue by nepa** [cdnjs/cdnjs#13719]
AngularJS 1.7.9 was released on 2019-11-19 and is still missing at cdnjs.

Please update the library. Thank you. :-)

https://github.com/angular/angular.js/blob/master/CHANGELOG.md

I tried to provide a pull request last time, but it miserably failed due to the mere size of the repository, so we are probably better of, if somebody takes care of the update, who is more proficient in the entire update process.

**Comment by nepa** [comment]
A similar request was closed in December 2019:
https://github.com/cdnjs/cdnjs/issues/13648

The ticket states that the problem will solve itself and something about an 'ETA', but I have no idea what that is and obviously the problem did not solve itself yet. ;-)

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Looking at the issue referenced, it was stated that the library is not configured to auto-update and so it has not auto-updated.

Someone will need to create a PR to add a valid auto-update configuration to Angular.js, so that our auto-update bot can load in new versions.

**Comment by heathergh** [comment]
I've added a npm hook (hopefully I did it correctly) to the Angular library, so it can auto-update :)

**Comment by nepa** [comment]
I just noticed that AngularJS 1.7.9 is now available at cdnjs.

Thank you very much for the effort @heathergh and @MattIPv4.

Unfortunately, some of the sub-modules (such as angular-animate) are now missing in version 1.7.9.

But this issue, at least, is resolved. 👍

**Comment by MattIPv4** [comment]
As mentioned in https://github.com/cdnjs/cdnjs/pull/13724#issuecomment-597868457, each submodule will need to be added as its own package to cdnjs.
