### ISSUE TITLE
Add echarts-gl

### ISSUE THREAD

**Issue by epaezrubio** [cdnjs/cdnjs#13729]
From their README:

> ECharts-GL is an extension pack of echarts, which providing 3D plots, globe visualization and WebGL acceleration.

Echarts, the base library, is already added in the CDN (latest update: https://github.com/cdnjs/cdnjs/commit/86f819c4d3b2d602b640e9aeb683c2077e69a067). This official extension has enough popularity to be added too (~2k starts on Github, ~4k weekly downloads on npm).

GitHub: https://github.com/ecomfe/echarts-gl
NPM: https://www.npmjs.com/package/echarts-gl

I'll be happy to submit a PR.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
