### ISSUE TITLE
acorn-loose and acorn-walk are missing

### ISSUE THREAD

**Issue by Pok-Pok** [cdnjs/cdnjs#13728]
AcornJS is present in the repository (https://cdnjs.cloudflare.com/ajax/libs/acorn/7.1.1/acorn.js) but the dependent acorn-loose and acorn-walk are not.
Should/could those also be added?

**Comment by xtuc** [comment]
Feel free to add them. See the contributing.md files in the repo

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
