### ISSUE TITLE
[Request Update] request: interactjs

### ISSUE THREAD

**Issue by wreiske** [cdnjs/cdnjs#13758]
https://interactjs.io/ is on 1.9.7, CDNJS only has 1.2.9 and it causes errors with their latest documentation.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by MattIPv4** [comment]
Looks like we're currently using git auto-update for this library and the structure of the repo has changed: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/interact.js/package.json / https://github.com/taye/interact.js/tree/v1.9.7

Probably worth looking at moving this lib to auto-updating via npm instead: https://www.npmjs.com/package/interactjs
