### ISSUE TITLE
Add @indexeddbshim/indexeddbshim

### ISSUE THREAD

**Issue by brettz9** [cdnjs/cdnjs#13757]
Hi,

You were previously kind to add indexeddbshim. As the original maintainer appears unreachable, I have created a fork which I plan to maintain (and which I am doing for other reasons such as being able to update the project settings to put our demo on Github Pages and accepting sponsorships).

I am hoping you can also add this new package `@indexeddbshim/indexeddbshim` so that users who wish to migrate to the latest version may do so.

Thank you!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
