### ISSUE TITLE
Need help converting my GitHub code to CDN library

### ISSUE THREAD

**Issue by thehitechpanky** [cdnjs/cdnjs#13760]
How can the following code be converted to CDN and be published on cdnjs? https://github.com/thehitechpanky/js-bootstrap-tables

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
