### ISSUE TITLE
[Request] Add bs-custom-file-input

### ISSUE THREAD

**Issue by arman-h** [cdnjs/cdnjs#13784]
**Library name**: bs-custom-file-input
**Library description**: A little plugin for Bootstrap 4 custom file input
**Git repository url**: https://github.com/Johann-S/bs-custom-file-input
**npm package name or url (if there is one)**: https://www.npmjs.com/package/bs-custom-file-input
**License (List them all if it's multiple)**: MIT
**Official homepage**: https://bs-custom-file-input.netlify.com/

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
