### ISSUE TITLE
Newly added (NPM) packages doesn't update versions

### ISSUE THREAD

**Issue by Glennmen** [cdnjs/cdnjs#13840]
I am not sure what the process is but I am noticing strange behaviour for newly added (NPM autoupdate) packages.

For example I added `amcharts4` and it was merged yesterday but the update bot hasn't fetched the available versions from NPM:https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/amcharts4

Maybe I am being impatient but an other example is this package `codeflask` that was added and merged by @MattIPv4 6 days ago and also here the update bot hasn't fetched any available versions. https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/codeflask

6 days seems a lot for the bot to kick in.

**Comment by MattIPv4** [comment]
New packages won't be picked up by the old auto-update bot due to how it's designed. If there are any high priority ones, we can look to expedite them over to the new auto-update bot (cdnjs/packages).

We are continuing to work on getting the new automation ready for auto-updating both NPM & git libraries, at which point we'll carry out a major migration from this repo to cdnjs/packages.

**Comment by Glennmen** [comment]
So there are now a lot of packages being added, many by you I see, that won't be available on cdnjs. Not even with their latest/current version. 

When this migration will happen will the new bot go through each package.json and download all (all missing) versions? 

I know that an ETA is hard 😅 and it won't be within a couple of days. But are we looking at weeks or months?

**Comment by MattIPv4** [comment]
Yeah, once the bot discovers a new package it backfills every version it can find, so that'll be fine.

@xtuc do you have any rough ETA you can share for the new bot?

Is the NPM updating logic in a state where we could migrate over every NPM package (including schema migration?) and then continue working on the new Git updating bot after?

**Comment by xtuc** [comment]
amcharts4 has been migrated to the new bot and should push new versions

**Comment by MattIPv4** [comment]
@xtuc don't all the migrated libs need `.donotupdate` files added in this repo?

**Comment by xtuc** [comment]
The bot added them: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/codeflask and https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/amcharts4. it also added the `.do_not_update` files

**Comment by MattIPv4** [comment]
Amazing, thank you!
