### ISSUE TITLE
Git auto-update: vanilla-lazyload not updating

### ISSUE THREAD

**Issue by verlok** [cdnjs/cdnjs#13903]
vanilla-lazyload script users [found](https://github.com/verlok/lazyload/issues/444) that this script is stuck to 12.3.0 on CDNJS.
Please pull in the newer versions (current is 15.1.1).

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by verlok** [comment]
Hey @MattIPv4 ,
thank you for the reply.

Not sure of what to do there because the process seems extremely complicated to me, and I'm not sure if I need to do that, since I don't want to add a new library but update an existing one.

**Comment by xtuc** [comment]
@verlok could you please check in the configuration (ajax/libs/vanilla-lazyload.json) and if it's make sense based on the contributing.md files. usually auto-update using npm works better, please switch if you are using git

**Comment by verlok** [comment]
Hey @xtuc ,
I hope I did the right thing, here #13943

**Comment by MattIPv4** [comment]
I’ll take a look at that tomorrow and port it over to cdnjs/packages for you :)

**Comment by verlok** [comment]
Thanks @MattIPv4 ,
the PR is merged now, but I can't see any new version of LazyLoad on CDNJS.
Did I do something wrong or is it just a matter of time?

**Comment by MattIPv4** [comment]
It should update whenever the git auto-update bot next runs, and then will be available on the website when the website next deploys after that.

**Comment by verlok** [comment]
Thanks man

**Comment by verlok** [comment]
Hey @MattIPv4, do you know how frequently the git auto-update bot runs?
And the website deploy starts right after? How long does it take?

**Comment by verlok** [comment]
Hey @MattIPv4 ,
the version of vanilla-lazyload is still stuck at 12.3 on the CDNJS website.

How can I fix that?

**Comment by MattIPv4** [comment]
@xtuc Want to investigate what's going on with the old git auto-update bot, or better to just leave it and wait until we've built the new one?

**Comment by xtuc** [comment]
I moved the package to the new bot
![Screenshot from 2020-05-28 14-39-51](https://user-images.githubusercontent.com/1493671/83148629-20701400-a0f1-11ea-975f-b268448726e4.png)

**Comment by verlok** [comment]
Solved. Thanks!
