### ISSUE TITLE
[Request][Author] Add react-markdown-editor-lite

### ISSUE THREAD

**Issue by sylingd** [cdnjs/cdnjs#13935]
**Library name:** react-markdown-editor-lite
**Library description:** A light-weight Markdown editor of React component
**Git repository url:** https://github.com/HarryChen0506/react-markdown-editor-lite
**npm package name or url (if there is one):** https://www.npmjs.com/package/react-markdown-editor-lite
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/HarryChen0506/react-markdown-editor-lite

---
This library currently has 2,448 weekly downloads at npm and 271 stars at GitHub, I hope CDNJS can add it, thank you

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by sylingd** [comment]
> Hi there!
> 
> Thank you for making a new library request issue on cdnjs! 📦
> Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.
> 
> **To help us with this, you can create the pull request to add the library yourself!** 📥
> 
> **Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**
> 
> Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

I imitated your commit and submitted a PR #13940

**Comment by MattIPv4** [comment]
Added via https://github.com/cdnjs/packages/pull/10
