### ISSUE TITLE
[Request Update] request: vue-router

### ISSUE THREAD

**Issue by benleilei** [cdnjs/cdnjs#13952]
https://github.com/vuejs/vue-router is on 3.1.6, CDNJS only has 3.1.3 and it causes errors with their latest documentation. CDNJS missing 3.1.4 and 3.1.5 and 3.1.6 three versions.

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
