### ISSUE TITLE
[Request Update] Update Font-Logos

### ISSUE THREAD

**Issue by leoherzog** [cdnjs/cdnjs#13955]
The library that was added in #9217 has been renamed and moved to `https://github.com/Lukas-W/font-logos`, so it is currently no longer getting updates.

Also, this project uses the public domain Unlicense:
https://github.com/lukas-w/font-logos/blob/master/LICENSE
which isn't specified on [the cdnjs page for the project](https://cdnjs.com/libraries/font-linux).

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by leoherzog** [comment]
Thank you!
