### ISSUE TITLE
[Request] Add pdf-lib

### ISSUE THREAD

**Issue by fastily** [cdnjs/cdnjs#13950]
Could [pdf-lib](https://github.com/Hopding/pdf-lib) be added to cdnjs?

* Stars: 976
* [npmjs](https://www.npmjs.com/package/pdf-lib): 25k pulls a week

Thanks!

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄
