### ISSUE TITLE
Add Library “vue-router-tab”

### ISSUE THREAD

**Issue by benleilei** [cdnjs/cdnjs#13969]
Library Name: vue-router-tab
Repositoy URL: https://github.com/bhuh12/vue-router-tab
NPM Package URL: https://www.npmjs.com/package/vue-router-tab

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
