### ISSUE TITLE
can't load jquery

### ISSUE THREAD

**Issue by ww156** [cdnjs/cdnjs#14091]
https://www.xiaochushuo.com/
in this site, the jquery.js can't load

but http://www.xiaochushuo.com/

then jquery.js can load

is something wrong in my site?

anyone can help me, thanks very much.

**Comment by MattIPv4** [comment]
`window.jQuery` is available for me when I access https://www.xiaochushuo.com/ -- I see jQuery loading just fine.

**Comment by ww156** [comment]
![图片](https://user-images.githubusercontent.com/16057055/145315746-89200b74-cb9f-4ba7-aa32-93568a59cd9f.png)
this is the https://www.xiaochushuo.com/

![图片](https://user-images.githubusercontent.com/16057055/145315905-40e36bcc-1c7b-46c3-b7a2-0c79033aae1a.png)
this is the http://www.xiaochushuo.com/

**Comment by MattIPv4** [comment]
It is loading completely fine for me:

![image](https://user-images.githubusercontent.com/12371363/145316618-bfc283de-696f-418e-9458-714dfc4ed551.png)

I would suggest trying an alternate browser to avoid this being a cache issue etc. If it persists, please upload a HAR of the failing network request so that we can investigate further (be sure to scrub any private info from the HAR data)

**Comment by ww156** [comment]
OK，it resolved, thank you!
