### ISSUE TITLE
Some versions of devextreme are missed

### ISSUE THREAD

**Issue by timbset** [cdnjs/cdnjs#14198]
Hi. I see that some of devextreme versions are absent. Here is a list of them:

```
22.2.7-build-23148-0308
22.1.10-build-23148-0308
23.1.2-beta.2
22.1.10-build-23141-0309
22.2.7-build-23141-0309
23.1.2-beta
22.2.7-build-23134-0310
22.1.10-build-23130-0308
22.2.7-build-23128-0308
22.2.7-build-23123-0308
22.1.10-build-23123-0308
23.1.2-alpha-23114-0308
22.1.9
22.2.6
21.2.14-build-23115-0306
```

**Comment by MattIPv4** [comment]
I see quite a few [log commits](https://github.com/cdnjs/logs/commit/00772621bfce2e0b1ee54a0524146f149abddfea) for 20.1.17, which makes me think the update processing logic is stuck on that version. @xtuc any ideas?

**Comment by MattIPv4** [comment]
(looking at the commit log to the logs repo, it does look like quite a few libraries are in the same position, where they've got empty `new-version` commits repeatedly happening)

**Comment by timbset** [comment]
Any news about that? Maybe, if it's broken to be published automatically, there is a way to make it manually to resolve the problem?

**Comment by MattIPv4** [comment]
Yes -- you can see repeat empty commits to the logs repo where it is failing to process a version of this library.

> it looks like new version sources are not pushed into repository from which files are distributed though Cloudflare

Files are not distributed based on being preset in this repository.

**Comment by timbset** [comment]
Alright, thank you for your response. Hope, the problem will be resolved very soon, because it's really important for us. I would even say critical.

**Comment by xtuc** [comment]
is this still an issue? All versions of devextreme have been published since:

- https://cdnjs.com/libraries/devextreme/22.2.7-build-23148-0308
- https://cdnjs.com/libraries/devextreme/22.1.10-build-23148-0308
- https://cdnjs.com/libraries/devextreme/23.1.2-beta.2
- https://cdnjs.com/libraries/devextreme/22.1.10-build-23141-0309
- https://cdnjs.com/libraries/devextreme/22.2.7-build-23141-0309
- https://cdnjs.com/libraries/devextreme/23.1.2-beta
- https://cdnjs.com/libraries/devextreme/22.2.7-build-23134-0310
- https://cdnjs.com/libraries/devextreme/22.1.10-build-23130-0308
- https://cdnjs.com/libraries/devextreme/22.2.7-build-23128-0308
- https://cdnjs.com/libraries/devextreme/22.2.7-build-23123-0308
- https://cdnjs.com/libraries/devextreme/22.1.10-build-23123-0308
- https://cdnjs.com/libraries/devextreme/23.1.2-alpha-23114-0308
- https://cdnjs.com/libraries/devextreme/22.1.9
- https://cdnjs.com/libraries/devextreme/22.2.6
- https://cdnjs.com/libraries/devextreme/21.2.14-build-23115-0306

**Comment by xtuc** [comment]
I'm going ahead and closing the issue. Please let us know if you see more missing versions.
