### ISSUE TITLE
create a formal removal process

### ISSUE THREAD

**Issue by nitriques** [cdnjs/cdnjs#3035]
So I think this should now be clear and documented some how.

What's the actual process for removing, temporarly and/or permanentaly for files and folder ? Should contributor be notifier ? Should person with accounts be notified ?

Are the libs really hosted forever ? Or could they be removed for some exceptions ?

I think this kind of SLA is required, both for devs and consumer. I did experience some troubles regarding this and want to avoid the problems in the future, for the sake of the community.

**Comment by AmNotADev** [comment]
This needs to be readdressed by org members like @PeterDaveHello @ryankirkman @MattIPv4 and myself. 

I'm working on new docs, including legal docs, and have been networking with Cloudflare's T&S department. Until we get this figured out, we can't properly finalize any org documentation.

**Comment by xtuc** [comment]
as mentioned already, we are not planning to remove any files distributed by cdnjs.com because it would be a breaking change.

Files that needs to be taken down must be handled by Cloudflare's T&S and it outside cdnjs.com's scope anyway.

Feel free to reach out to sven (at) cloudflare.com if you need anything
