### ISSUE TITLE
Tips/tricks for dealing with large repository size

### ISSUE THREAD

**Issue by kevinburke** [cdnjs/cdnjs#3616]
The cdnjs repository on my computer is 4.2GB, which is large, and makes git operations slow: 9.76 seconds to run "git status" for example.

Is there a better/faster way to do this? Can I add my changes without checking out the entire repository? How would this work?

It would be nice if this information was added to the README or the CONTRIBUTING file.

**Comment by VictorBjelkholm** [comment]
Is there any work being done to change the current architecture? I'm pretty sure Git was not made with this use case in mind. Would it make sense to have the libraries stored somewhere else and just have the application specific parts here? 

I'm asking because I would like to get cdnjs to use IPFS but cloning and managing a repo of this size sucks.

**Comment by MattIPv4** [comment]
We are working to split how cdnjs works so that there is a much smaller repository for humans to work with. Keep an eye on cdnjs/pacakges.
