### ISSUE TITLE
ember.js and ember-data.js are missing files

### ISSUE THREAD

**Issue by gerry3** [cdnjs/cdnjs#4539]
For ember.js (e.g. 1.11.1), cdnjs includes

• ember.js
• ember.min.js
• ember.prod.js

However, [ember.js 1.9.0 included renaming release files](http://emberjs.com/blog/2014/12/08/ember-1-9-0-released.html#toc_renaming-release-files) and `ember.js` was deprecated in favor of `ember.debug.js`.

I would think any ember.js version 1.9.0 and after ought to include the `ember.debug.js` file and future versions probably shouldn't even have an `ember.js` at all.

Also, ember-data.js should include `ember-data.js.map` as loading `ember-data.js` (e.g. 1.0.0-beta.16.1)  expects that file to exist. I'm not sure in what version that file was first expected.

Thoughts? Thanks for any help.

@PeterDaveHello @rwjblue

**Comment by PeterDaveHello** [comment]
Oh, thanks, I'll fix it.

**Comment by PeterDaveHello** [comment]
Fixed in those commits below, thanks.
* cab302d add missing ember.debug.js in ember.js v1.11.x Peter Dave Hello 59 seconds ago
* 284731c update git auto-update config of ember-data.js Peter Dave Hello 3 hours ago
* 216c462 update git auto-update of ember.js Peter Dave Hello 3 hours ago
* c202400 update ember-data.js Peter Dave Hello 3 hours ago
* db756d3 add ember-data.js.map in ember-data.js Peter Dave Hello 3 hours ago
