### ISSUE TITLE
Update the versions after publishing the new version

### ISSUE THREAD

**Issue by IonicaBizau** [cdnjs/cdnjs#4598]
It would be nice to update the version on CDNJS right after doing `npm publish`.

I'm not sure, but there should be way to *listen* when a new version is published (something like GitHub hooks).

If that's not possible, maybe you can implement a button to check for updates.

**Comment by PeterDaveHello** [comment]
We already have rss, I don't think this is needed, cc @thomasdavis @ryankirkman @drewfreyling for comments

**Comment by ryankirkman** [comment]
@IonicaBizau Would the RSS feed suit your needs?

Interested in your use case :)

**Comment by IonicaBizau** [comment]
The use case is:

 1. I'm releasing a new version of the `foo` library.
 2. Before publishing on NPM, I update the CDN url (actually the version) in the readme file.
 3. After publishing, the url is still a 404 error, until the version is updated in CDNJS.

It would be nice that right after publishing, to update the version on CDNJS.

**Comment by PeterDaveHello** [comment]
But we not make sure the next update will contain your lib, rss can.

**Comment by IonicaBizau** [comment]
@PeterDaveHello So, will you find a solution for this case?

**Comment by PeterDaveHello** [comment]
So what you need is to confirm that cdnjs now serving a new version of a lib?

**Comment by IonicaBizau** [comment]
@PeterDaveHello No, I want the feature that after the moment of `npm publish` the cdnjs update script to run for that library (so, it will update the version).

**Comment by PeterDaveHello** [comment]
Oh, seems I misunderstood, so you want to trigger our updater?

**Comment by IonicaBizau** [comment]
@PeterDaveHello Exactly! I'm not sure how it runs but I guess it's a cron job or so.

**Comment by PeterDaveHello** [comment]
But even if we support this feature, we still need to audit each new versions, and then it'll be committed, so it won't be on the list faster, as readme document said, many libs change their structure in the new versions, even they don't they may not provide the minified files, and this process can not be automatically, because there is no **standard** for the naming style, each lib will use the style they want, program can not easily make sure if it needs to be minified ... that's the reason why we still need human here, directly commit them will make the repo mess ...

**Comment by PeterDaveHello** [comment]
@IonicaBizau we now have a smart bot and it works hard, as you can see here: https://github.com/PeterBot

I wonder if we still need this feature? Or you have some other idea? Even we implement a listener to wait  for the trigger, should better make sure it's triggered by its author. Thanks.

**Comment by IonicaBizau** [comment]
Ah, great! :+1:
