### ISSUE TITLE
Extra directory in bootstrap-slider file listing on cdnjs website

### ISSUE THREAD

**Issue by dbeckwith** [cdnjs/cdnjs#4684]
I added bootstrap-slider in #4661, and for some reason on the website listing at https://cdnjs.com/libraries/bootstrap-slider/4.8.3, it shows the `/css` folder as a file, which none of the other libraries do. If you try to access https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/4.8.3/css, you get a 403 (bootstrap-slider has this extra listing for every version). I'm not sure if it's intentional or something wrong with the package.json or what, but I thought it was strange.

**Comment by IonicaBizau** [comment]
This happens because of [this `npmFileMap`](https://github.com/cdnjs/cdnjs/pull/4661/files#diff-03a7061079b714b2f18e718cdc01a4b7R12). I noticed the same issue in [medium-editor](https://cdnjs.com/libraries/medium-editor).

I'm not sure what could be the solution here: fix the file map or ignore the directories in listing? I would choose the second one.

Thanks for bringing this in attention, btw! :sparkler:

**Comment by dbeckwith** [comment]
Just as a random example, [backbone-forms](https://cdnjs.com/libraries/backbone-forms) has the same [`npmFileMap`](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/backbone-forms/package.json#L22), but directories don't show up. Weird. Anyway, I think you're right though, directories should just be ignored in the listing.

**Comment by IonicaBizau** [comment]
Hmm, good point. :+1: 

/cc @PeterDaveHello

**Comment by dbeckwith** [comment]
Actually now that I'm looking around a lot of other libraries have this.

**Comment by PeterDaveHello** [comment]
Fixed, but for the performance reason, current building process will use the already exist data instead of re-scaning the whole directory(and in fact we don't need to rebuild the old version everytime), rebuild the whole meta data will take longer time, I'll do it later manually. And that's see if this fix will broken something else, I hope not.

**Comment by dbeckwith** [comment]
That's fine, thanks!
