### ISSUE TITLE
coffeescript from cdnjs is unusable

### ISSUE THREAD

**Issue by eliot-akira** [cdnjs/cdnjs#4869]
https://github.com/jashkenas/coffeescript/issues/4001

**Comment by humbletim** [comment]
@PeterDaveHello -- Here's a dump of cdnjs coffee-script versions and working status:

version | size | output | status
--------- | ---------- | ------ | -------
**1.1.2** | *172K* | **CoffeeScript.VERSION == 1.1.2** | :coffee:
**1.1.3** | *16K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.2.0** | *176K* | **CoffeeScript.VERSION == 1.2.0** | :coffee:
**1.3.0** | *16K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.3.1** | *180K* | **CoffeeScript.VERSION == 1.3.1** | :coffee:
**1.3.2** | *16K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.3.3** | *184K* | **CoffeeScript.VERSION == 1.3.3** | :coffee:
**1.4.0** | *184K* | **CoffeeScript.VERSION == 1.4.0** | :coffee:
**1.5.0** | *16K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.6.0** | *16K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.6.1** | *16K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.6.2** | *204K* | **CoffeeScript.VERSION == 1.6.2** | :coffee:
**1.6.3** | *204K* | **CoffeeScript.VERSION == 1.6.3** | :coffee:
**1.7.0** | *24K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.7.1** | *212K* | **CoffeeScript.VERSION == 1.7.1** | :coffee:
**1.8.0** | *24K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.9.0** | *24K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.9.1** | *24K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.9.2** | *24K* | *Error: Cannot find module './lexer'* | :paw_prints:
**1.9.3** | *24K* | *Error: Cannot find module './lexer'* | :paw_prints:

note: the above table markdown can be reproduced using:
```sh
[cdnjs]# for version in ./ajax/libs/coffee-script/*/ ; do printf "**%s** | *%s* | %s\n" $(basename $version) $(du -h $version | cut -f1) "$(node -e "try { console.log('**CoffeeScript.VERSION == %s** | :coffee:', require('$version/coffee-script.min').CoffeeScript.VERSION) } catch(e) { console.log('*'+e+'* | :paw_prints:') }" )" ; done
```

Also since file size currently works as way to detect status, a report that groups non-working/working versions together is roughly:
```sh
[cdnjs]# du -hs ajax/libs/coffee-script/*/ | sort -n
16K     ajax/libs/coffee-script/1.1.3/
16K     ajax/libs/coffee-script/1.3.0/
16K     ajax/libs/coffee-script/1.3.2/
16K     ajax/libs/coffee-script/1.5.0/
16K     ajax/libs/coffee-script/1.6.0/
16K     ajax/libs/coffee-script/1.6.1/
24K     ajax/libs/coffee-script/1.7.0/
24K     ajax/libs/coffee-script/1.8.0/
24K     ajax/libs/coffee-script/1.9.0/
24K     ajax/libs/coffee-script/1.9.1/
24K     ajax/libs/coffee-script/1.9.2/
24K     ajax/libs/coffee-script/1.9.3/
172K    ajax/libs/coffee-script/1.1.2/
176K    ajax/libs/coffee-script/1.2.0/
180K    ajax/libs/coffee-script/1.3.1/
184K    ajax/libs/coffee-script/1.3.3/
184K    ajax/libs/coffee-script/1.4.0/
204K    ajax/libs/coffee-script/1.6.2/
204K    ajax/libs/coffee-script/1.6.3/
212K    ajax/libs/coffee-script/1.7.1/
```

**Comment by PeterDaveHello** [comment]
@jashkenas @eliot-akira Would you like to +1 here? Thanks!

**Comment by eliot-akira** [comment]
Yes, I confirm that pull request cdnjs/pull/4927 includes the correct build of the CoffeeScript compiler that runs in the browser. As mentioned in the pull request, the issue is that CoffeeScript's npm package and the github repo do not include the browser build.

Thank you for the swift response. Having a working compiler via CDNJS will be useful for prototyping, examples, and simple tests.

**Comment by youurayy** [comment]
Guys, same issue with the latest 1.10.0 - not usable in browser.

Steps to produce a browser usable library:

```bash
git clone https://github.com/jashkenas/coffeescript.git
cd coffeescript.
npm update
cake build:browser
# generated file is in -> extras/coffee-script.js
```

Please fix or let us know what help is needed exactly.

**Comment by PeterDaveHello** [comment]
Sorry for the late reply. So what #4927 did that fetching file under the `extras` folder in git repository is for browser usage, is this correct? Thanks.

**Comment by youurayy** [comment]
@PeterDaveHello #4927 does the same but adds a non-minified version of the file (so that's the approach you need to take if you want both minified and non-minified). Thanks.

**Comment by humbletim** [comment]
In the meantime here are some fallback cdn links to the browser build of CoffeeScript (courtesy of fellow github project https://github.com/rgrove/rawgit): 

https://cdn.rawgit.com/jashkenas/coffeescript/1.10.0/extras/coffee-script.js
https://cdn.rawgit.com/jashkenas/coffeescript/1.9.3/extras/coffee-script.js

**Comment by PeterDaveHello** [comment]
Let's make the file in #4927 be the same as upstream, and I'll merge that PR, thanks.

**Comment by robocoder** [comment]
How is it this issue has been open for 2+ years and the bot continues to upload b0rked versions to cdnjs? The latest working versions in cdnjs appear to be 1.6.3 and 1.7.1.

**Comment by robocoder** [comment]
These are the b0rked versions:
```
1.1.3
1.3.0
1.3.2
1.5.0
1.6.0
1.6.1
1.7.0
1.8.0
1.9.0
1.9.1
1.9.2
1.9.3
1.10.0
1.11.0
1.11.1
1.12.0
1.12.1
1.12.2
1.12.3
1.12.4
1.12.5
1.12.6
1.12.7
1.12.8
```

**Comment by robocoder** [comment]
Starting with 1.12.0, there's no longer an `extras` folder, so #4927 won't work anymore.
