### ISSUE TITLE
[Request] angularjs-nvd3-directives,  angular-bacon.js,dataTables.tableTools.min.js,angular-datatables,jquery.table2excel.js,ng-table.js

### ISSUE THREAD

**Issue by byunru** [cdnjs/cdnjs#5002]
http://cdn.jsdelivr.net/angularjs.nvd3-directives/v0.0.7/angularjs-nvd3-directives.js
http://rawgit.com/lauripiispanen/angular-bacon/master/dist/angular-bacon.js
http://cdn.datatables.net/tabletools/2.2.3/js/dataTables.tableTools.min.js
http://rawgit.com/l-lin/angular-datatables/master/dist/angular-datatables.js
http://rawgit.com/rainabba/jquery-table2excel/master/src/jquery.table2excel.js
http://cdn.jsdelivr.net/angular.ngtable/0.5.4/ng-table.js

**Comment by Piicksarn** [comment]
@byunru would you please provide the **git repository url **  or  **npm package url**, so that we could add libraries efficiently.

**Comment by byunru** [comment]
Here are their git repository url:

https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives
https://github.com/lauripiispanen/angular-bacon
https://github.com/DataTables/TableTools
https://github.com/maktouch/datatables-angular-directive
https://github.com/rainabba/jquery-table2excel
https://github.com/esvit/ng-table

**Comment by maruilian11** [comment]
@byunru  thank you for your contribution, but seems that we can only add `angularjs-nvd3-directives`, `angular-bacon`, `TableTools` and `ng-table`.

* `ng-table` doesn''t have enough popularity, tags for each version and package.json.
* `jquery-table2excel` doesn''t have enough popularity, either.
please read our README.md about the request popularity.

@cdnjs/intern i need your help add `angularjs-nvd3-directives`, `angular-bacon`, `TableTools` and `ng-table`. thank you！

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by Amomo** [comment]
Hi @byunru ,

We have added
- [angularjs-nvd3-directives](https://cdnjs.com/libraries/angularjs-nvd3-directives)
- [angular-bacon](https://cdnjs.com/libraries/angular-bacon)
- [datatables-tabletools](https://cdnjs.com/libraries/datatables-tabletools)
- [ng-table](https://cdnjs.com/libraries/ng-table)

Because `datatables-angular-directive` and `jquery-table2excel` doesn't have enough popularity.
Currently, we won't add it. Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you open an issue again when the libraries has more popularity.
Thanks for your contribution. :-)

**Comment by maruilian11** [comment]
@byunru this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add these libs, we may discuss to add them.
