### ISSUE TITLE
[bug] `**` and `*` should not be parsed in test's output

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5084]
`**` will be parsed as highlight syntax in test output, `*` seems to be missing, will misleading users, especially the test try to print the correct `package.json` of a lib.

**Comment by LuisRBarreras** [comment]
I am going to work on this one

**Comment by PeterDaveHello** [comment]
@LuisRBarreras Cool, thanks!

**Comment by LuisRBarreras** [comment]
@PeterDaveHello Could you give more details, which test is one you are referring to?

**Comment by PeterDaveHello** [comment]
@LuisRBarreras You can try to mess up indent in jquery package.json, npm test will return the correct indent, but wrong *

**Comment by PeterDaveHello** [comment]
@LuisRBarreras this could be an example: https://circleci.com/gh/cdnjs/cdnjs/5817

**Comment by LuisRBarreras** [comment]
This is a bug caused by the npm package [vows-si](https://www.npmjs.com/package/vows-si) 
A confirmed bug already exists [https://github.com/vowsjs/vows/issues/208](https://github.com/vowsjs/vows/issues/208)

The problem is with a regex, where there is  conflict between format output and *.
https://github.com/vowsjs/vows/blob/master/lib/vows/console.js#L47

Solution:
1. Make a fork of **vows repo** and change the regex.
2. Run the test in verbose mode and do a console.log of the format expected()

Both solution doesn't looks good but I will vote for the first one.

**I want to know your thoughts on which approach is better**
## Note:
The lack of progress on **vows testing library** makes me recommend to switch to another tool, maybe [mocha](https://mochajs.org/).
_This should be in another issue._

**Comment by PeterDaveHello** [comment]
Hi @LuisRBarreras,

Thanks for your report in detail, personally I prefer not to fork and maintain our own `vows`.

Though the testing library issue is not directly related with this one, but if `mocha` is confirmed that it doesn't have this problem, we can evaluate the pros and cons to move to `mocha`, and maybe can leave this one alone.

**Comment by LuisRBarreras** [comment]
## Migrate from Vows to Mocha
A combination of **Mocha/Chain** can providers BDD that Vows give us.

Vows claims to make test run faster specially on I/O (I believe, it's not going to be a big difference)

### Props
- Bigger community(Will lead to more people be able to work on the test suite) 
- Will remove the bug[**CONFIRMED**]
- Due of lack of progress on vows, we could encounter others bugs and ended up in the same situation.

### Cons
- Effort to make the migration(**Could break CI and test suite**)

**Comment by PeterDaveHello** [comment]
Thanks @LuisRBarreras and sorry for the late response, it looks good to me 👍

**Comment by LuisRBarreras** [comment]
If you want, Create an issue for the migration from vows to Mocha assigned for me.

**Comment by PeterDaveHello** [comment]
cc @dakshshah96 @IonicaBizau @petrgazarov

**Comment by dakshshah96** [comment]
@LuisRBarreras I've created a new issue for the same. #11345
