### ISSUE TITLE
[Request] famo.us engine

### ISSUE THREAD

**Issue by melbourne2991** [cdnjs/cdnjs#5134]
famo.us
https://github.com/Famous/engine
famo.us

**Comment by maruilian11** [comment]
@PeterDaveHello this lib seems just include many other lib, do we add it, too?
please take a look at https://github.com/Famous/engine/blob/v0.7.1/index.js

**Comment by PeterDaveHello** [comment]
cc @cdnjs/intern @cdnjs/team-cdnjs

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by maruilian11** [comment]
@cdnjs/intern i need your advice. thanks~

**Comment by LeaYeh** [comment]
i'm not real sure, but i think we need to add all of them.

**Comment by drewfreyling** [comment]
@maruilian11 What do you get when you `npm install famous` with regards to your question about including other libs. We should try to mirror what is included in their distributable i feel.

**Comment by maruilian11** [comment]
@drewfreyling thank you for your reminding. after i read their [getting start guides](http://famous.org/get-started.html)
i think we can add [FamousEngine.js](https://github.com/Famous/engine/blob/v0.7.1/core/FamousEngine.js)
what do you think? guys

**Comment by Amomo** [comment]
@maruilian11 the file **FamousEngine.js** is a node module, I don't think we should add it.
 
After `npm install famous`, under "node_modules/famous/"
we need `npm install` and `npm run build-debug && npm run build-min` to build files in `dist/`.

As @drewfreyling said, we should add files "famous.js" and "famous.min.js" which were built after the command.

**Comment by maruilian11** [comment]
i did the `npm install famous`, but i didn't do `npm run`
thank you @Amomo

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
