### ISSUE TITLE
[Request] jshashtable

### ISSUE THREAD

**Issue by ch3tanp** [cdnjs/cdnjs#5985]
**Library name:jshashtable** 
**Git repository url:https://github.com/timdown/jshashtable**
**npm package url(optional):https://www.nuget.org/packages/jshashtable.js 
*_License(s):https://github.com/timdown/jshashtable/blob/master/license.txt
*_Official homepage: http://www.timdown.co.uk/jshashtable/index.html*
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ch3tanp** [comment]
Accidentally closed.

**Comment by Amomo** [comment]
Hi @ch3tanp ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
We suggest you open an issue again when the library has more popularity.

Or, I found that it is a repo exporting from Google Code.
Do you have other ways to show its popularity?

Thanks for your contribution. :-)

**Comment by PeterDaveHello** [comment]
I thought nuget has download counters, hope I didn't remember it wrong.

**Comment by PeterDaveHello** [comment]
Ping @Amomo

**Comment by PeterDaveHello** [comment]
Ping @Amomo

**Comment by maruilian11** [comment]
>I thought nuget has download counters, hope I didn't remember it wrong.
@PeterDaveHello https://www.nuget.org/packages/jshashtable.js This status doesn't have the info requirement(downloads per month) ask for. Can we add this lib?

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
