### ISSUE TITLE
[Request] Add jscolor

### ISSUE THREAD

**Issue by EastDesire** [cdnjs/cdnjs#6172]
**Library name:** jscolor
**Git repository url:** https://github.com/EastDesire/jscolor
**npm package url(optional):** 
**License(s):** Dual licensing: Commercial or GNU GPL v3
**Official homepage:** http://jscolor.com
**Wanna say something? Leave message here:** Thank you (-:

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@EastDesire,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.

**Comment by ajmas** [comment]
@EastDesire - how do we get into contact with you? There are no issue pages or contact information for this project. While waiting for the project to get enough popularity, you could consider a linkable minified JS on gh-pages as an option? Not being contactable in any form, is not going to help popularity, IMHO. My 2c.

@Piicksarn using this page, since I have no idea what other options there are.

**Comment by PeterDaveHello** [comment]
@dannyxx001 please help me add this library.
