### ISSUE TITLE
[Request] Add spinners

### ISSUE THREAD

**Issue by Zerrossetto** [cdnjs/cdnjs#6213]
**Library name:** Spinners
**Git repository url:** https://github.com/staaky/spinners
**npm package url(optional):** 
**License(s):** Apparently no license
**Official homepage:** http://projects.nickstakenburg.com/spinners/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
@zavoloklom we already open an [issue](https://github.com/staaky/spinners/issues/7) that ask author about lost tags.
let's wait author's response :)

**Comment by maruilian11** [comment]
@staaky could you please consider adding tags for each version? thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello seems no response for a month. how can we do for this issue?

**Comment by PeterDaveHello** [comment]
Can just add the tagged version.

**Comment by staaky** [comment]
I'm the author, thanks for considering the script but I wouldn't recommend putting it on a CDN.

The script creates loading icons through Canvas, something you couldn't do with CSS years ago, at least not in every browser. But browsers have caught up, you can easily create loading icons with just a few lines of CSS these days. Since Canvas is no longer a best practice, I'd avoid pushing it.

**Comment by PeterDaveHello** [comment]
@Zerrossetto What do you think?

**Comment by PeterDaveHello** [comment]
Close due to no response.
