### ISSUE TITLE
[Enhancement] Add dependencies section

### ISSUE THREAD

**Issue by KeithBohler** [cdnjs/cdnjs#6269]
For many frameworks and other packages that are posted on CDNJS, their are numerous dependencies for them to work properly. Having to navigate around and find the dependencies can be time consuming and inconvenience the user. Thus, I must suggest that their be a dependencies section to projects on CDNJS.

**Comment by PeterDaveHello** [comment]
Yes, so we don't drop `dependencies` in package.json from upstream, but haven't show it on the website, and also it's hard to maintain that info, I haven't figure out a good method.
cc @cdnjs/team-cdnjs

**Comment by PeterDaveHello** [comment]
Hi @KeithBohler, we finally decided to drop that since there are so many libs there and there are so many not really follow the conventions about how to use dependencies, devDependencies, and we don't update dependency info at all, their dependency may even not on CDNJS, due to these reasons, we dropped that, if you do have some specific suggestion, feel free to discuss with us, thanks!
