### ISSUE TITLE
[Request] isteven-multi-select

### ISSUE THREAD

**Issue by AmitMY** [cdnjs/cdnjs#6398]
isteven-multi-select:
https://github.com/isteven/angular-multi-select
License(s): MIT
http://isteven.github.io/angular-multi-select/#/main

Great library, should realy have a cdn

**Comment by isteven** [comment]
@AmitMY , @PeterDaveHello , 

My bad.. Some users already asked me in the past to add this into CDNJs, but due to the way submission is added (user submitted pull request etc) and my hectic schedule, I keep forgetting it. 

Thanks for adding this library into CDNJs. I hope more users will benefit from this.

**Comment by PeterDaveHello** [comment]
Added it here, https://github.com/cdnjs/cdnjs/commit/af624abd270c5d1f4820eb3697ff40e363efa5d9 closed a wrong issue :smile:

**Comment by PeterDaveHello** [comment]
@isteven maybe you can add some words in readme to let the users know :+1:

**Comment by isteven** [comment]
@PeterDaveHello 

LOL.. Cheers for the hard work maintaining things in CDNJs :+1: 

Sure thing, will update my readme & manual.
