### ISSUE TITLE
[Request] x2js

### ISSUE THREAD

**Issue by mortein79** [cdnjs/cdnjs#6528]
**Library name:** x2js
**Git repository url:** -
**npm package url(optional):** 
**License(s):** Apache License 2.0
**Official homepage:** https://code.google.com/p/x2js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @mortein79 

Since Google Code is going to stop service, we hope to add a library with npm/git auto-update mechanism. I found the author has mirrored x2js to [GitHub](https://github.com/abdmob/x2js).

But it seems don't have enough popularity(we suggest 100 stars or watchers on GitHub).
Could you give us some proof about its popularity?

**Comment by PeterDaveHello** [comment]
It's okay to add this lib.
https://code.google.com/p/x2js/downloads/list

**Comment by Amomo** [comment]
@PeterDaveHello should I add every versions of this library from Google Code by manual?
Or should I add it from GitHub repo with auto-update?

**Comment by PeterDaveHello** [comment]
both fine
