### ISSUE TITLE
[Request] Add jquery.twentytwenty

### ISSUE THREAD

**Issue by evyatar** [cdnjs/cdnjs#6594]
jquery.twentytwenty
https://github.com/zurb/twentytwenty
**npm package url(optional):** 
MIT Open Source License
http://zurb.com/playground/twentytwenty

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@evyatar ,
The lib would be considered to added in cdnjs as the tags be used.
We need tags for confirming the version.
Thank you! :smiley:

Piicksarn

**Comment by mhayes** [comment]
Hey @Piicksarn thanks for reaching out. I don't have access to the original repo anymore as I have since left ZURB, but have created another fork that contains the necessary release tag here:

https://github.com/mhayes/twentytwenty/

It also contains support for AngularJS (currently in beta until I get more time to ensure it works on all the popular browsers ok).

Will that work?

**Comment by PeterDaveHello** [comment]
@mhayes the tags are used for auto-update, we should set auto-update upstream to be an official repo.
