### ISSUE TITLE
[Request] bp-mentions, 

### ISSUE THREAD

**Issue by navinachettri** [cdnjs/cdnjs#6714]
**Library name:** mentions.min.js
**Git repository url:**https://github.com/buddypress/BuddyPress-build/blob/master/bp-activity/js/mentions.min.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**buddypress.org
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@navinachettri ,
This library doesn't have notable popularity(100 watch or star is a good example).
Would you mind to open an issue again when the library has more popularity?
**`This issue will be closed if there is no any response in next 7 day.`**

thank you!
Piicksarn

**Comment by PeterDaveHello** [comment]
Looks okay with the source repo: https://github.com/buddypress/BuddyPress, so let's add this.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
