### ISSUE TITLE
[Request] Add script.min.js

### ISSUE THREAD

**Issue by kofifus** [cdnjs/cdnjs#6728]
**Library name:** 
script.js
**Git repository url:**
https://github.com/ded/script.js/
**npm package url(optional):** 
**License(s):**
github
**Official homepage:**
https://github.com/ded/script.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We have it for many years!

* dc2056d add missing author info in package.json PeterDaveHello 4 weeks ago
* 26415ad clean up package.json of libs via tools/fixFormat.js Peter Dave Hello 6 weeks ago
* a922f16 update description of libs by tools/addMissingLicense.js Peter Dave Hello 7 weeks ago
* 9f52604 add script.js v2.5.8 Peter Dave Hello 4 months ago
* 65d5b22 use repository instead of repositories in package.json Peter Dave Hello 4 months ago
* 59801a7 add script.js v2.5.7 Peter Dave Hello 1 year, 6 months ago
* 4bf9bd7 manually fix the eof newline issue Peter Dave Hello 1 year, 6 months ago
* 4ada1a2 Updated packages via auto-update.js Thomas Davis 1 year, 6 months ago
* 3c39346 Updated packages via auto-update.js Thomas Davis 1 year, 7 months ago
* 6aefb3b Updated packages via auto-update.js Thomas Davis 1 year, 7 months ago
* d10ec2e Updated packages via auto-update.js Thomas Davis 1 year, 7 months ago
* d6ec1ad Updated packages via auto-update.js Thomas Davis 1 year, 7 months ago
* 4ec1f75 auto update Thomas Davis 1 year, 9 months ago
* 69a2914 The following libs were updated:    cookies-js, accounting, jquery-autosize, bespoke, cannon, idb-wrapper, lunr, numeral, scriptjs, stompjs Misha Koryak 1 year, 9 months ago
* 195394d Add script.js v2.4.0 CodeAnimal 2 years, 4 months ago
* b55fd5e Added script.js 1.3 Han Lin Yap 4 years, 8 months ago
* b597a0e Popular scripts samot 4 years, 11 months ago
* e8c5026 Added a new descriptor and fixed a bug with versions -> version samot 4 years, 11 months ago
* 1a3e01c Added require.js descriptor, andy chung is a champion, asians ftw samot 4 years, 11 months ago
* eaa6318 Added script.js descriptor by Dustin Diaz, Cameron Diaz is hot as samot 4 years, 11 months ago

**Comment by PeterDaveHello** [comment]
See https://cdnjs.com/libraries/script.js
