### ISSUE TITLE
[Request] Add ember-localforage-adapter

### ISSUE THREAD

**Issue by jansegre** [cdnjs/cdnjs#7134]
**Library name:** ember-localforage-adapter
**Git repository url:** https://github.com/genkgo/ember-localforage-adapter
**npm package url:** https://www.npmjs.com/package/ember-localforage-adapter
**License(s):** MIT

I'll try to get my way around a pull request, but I don't guarantee anything.

**Comment by jansegre** [comment]
I'm having trouble figuring how to add generated to autoupdate (because there are no precompiled files distributed). And also how that would work with ember, which I'm maybe not familiar enough.

That aside, is 1.2GiB normal for a shallow sparse clone? I was expecting about half of that.

Anyway this is not critical for me, I have other priorities right now. I'm leaving this open to tackle another day maybe.

**Comment by maruilian11** [comment]
hi @jansegre, I'm happy to add this lib for you, could you please tell me which files should be hosted on cdnjs? thank you!

**Comment by jansegre** [comment]
hi @maruilian11, it should be every file under `dist` after building, which can be done with `npm build` IIRC. It's very similar to other `ember-*` packages, [ember-data-model-fragments](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/ember-data-model-fragments/package.json) is an example.

**Comment by PeterDaveHello** [comment]
@jansegre Thanks.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
