### ISSUE TITLE
[Request] Add jquery.soulmate.js

### ISSUE THREAD

**Issue by sachinsudheendra** [cdnjs/cdnjs#7187]
**Library name:** jquery.soulmate.js
**Git repository url:** https://github.com/mcrowe/soulmate.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
Soulmate.js is a jQuery plugin front-end for soulmate, an excellent auto-suggestion gem built for speed on sinatra and redis. 
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
There is no [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) in that repository, **git tag** is what our git auto-updater relys on, is there is no any valid tag, the updater can not recognized what are the correct versions we can use, and also, you can not make sure the specific versions. So please discuss with its author about that, thanks.

References:
 - https://git-scm.com/book/en/v2/Git-Basics-Tagging
 - https://help.github.com/articles/creating-releases/
 - https://help.github.com/articles/working-with-tags/

**Comment by sachinsudheendra** [comment]
Thank you for looking into this @PeterDaveHello. I'll follow up with the author about this.

**Comment by PeterDaveHello** [comment]
@sachinsudheendra no probs

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
