### ISSUE TITLE
[Request] Kudos Please

### ISSUE THREAD

**Issue by selrond** [cdnjs/cdnjs#7269]
**Library name:** Kudos Please
**Git repository url:** https://github.com/TimPietrusky/KudosPlease
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://kudosplease.com/
**Wanna say something? Leave message here:**
# Kudos please! 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@selrond would you please tell me what are the files need to be hosted? Thanks.

**Comment by selrond** [comment]
well AFAIK, kudosplease-min.js (kudosplease.js respectively) and kudosplease.css (scss source - kudosplease.scss)

**Comment by PeterDaveHello** [comment]
@TimPietrusky would you please help us confirm that if we want to host your lib on CDNJS? Thanks.

**Comment by TimPietrusky** [comment]
Yes, the [mentioned files](https://github.com/cdnjs/cdnjs/issues/7269#issuecomment-210448158) are all you need. 

Thanks for adding them ❤

**Comment by PeterDaveHello** [comment]
Thanks @TimPietrusky

**Comment by PeterDaveHello** [comment]
hmmm ... got a problem here, seems there is no any version info, @TimPietrusky is it possible to add that? Thanks.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
