### ISSUE TITLE
[Request] Add number-polyfill

### ISSUE THREAD

**Issue by TheWebTech** [cdnjs/cdnjs#7282]
**Library name: Number-Polyfill** 
**Git repository url: https://github.com/jonstipe/number-polyfill**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 Suggest to close due to no reponse from author on issue of add git tag to repo and time passed sinse the request to add lib was opened

**Comment by TheWebTech** [comment]
Were you expecting a response from me? or the developer of this polyfill?

**Comment by sashberd** [comment]
@TheWebTech No response [here ](https://github.com/jonstipe/number-polyfill/issues/29)more the an year

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
