### ISSUE TITLE
[Question] is it possible to switch the source repository?

### ISSUE THREAD

**Issue by ducin** [cdnjs/cdnjs#7513]
Dear CDN.JS team,

Thank you for all your work!
We did setup the integration with cdn.js some time ago and we are experiencing similar problems with repository size as you are (growing very big because of the sizes of the packages), we want to split our repo into 2:
- source only repo (npm package is registered here)
- packages only repo (only build would get here)

Our repo is [json-schema-faker](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/json-schema-faker).

Where do you get the packages for cdn.js from? Is it defined in [those lines](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/json-schema-faker/package.json#L18-L25)? If I leave the [npm package name](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/json-schema-faker/package.json#L2) as it is and I just change [the repository](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/json-schema-faker/package.json#L20) to our _package only repo_ - would this work?

Thank you in advance for your help!
_CC json-schema-faker/json-schema-faker#133_

**Comment by PeterDaveHello** [comment]
@ducin it's fine to change the source repo! Sorry for the late reply.

**Comment by PeterDaveHello** [comment]
Hi @ducin, I'm tring to transfer this lib to use npm auto-update instead of git auto-update, however, seems there is no `dist` folder in npm package, and we don't support building the artifacts by ourselves, do you have any idea about this? Is it possible to put the `dist` files to npm package? So that you can feel free to remove them from the repo, and CDNJS still can update the new versions automatically, thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t please help me take care of this issue, thanks.

**Comment by MattIPv4** [comment]
No progress, closing.
