### ISSUE TITLE
CDNjs vs JSdelivr

### ISSUE THREAD

**Issue by ricardopolo** [cdnjs/cdnjs#7715]
Why should I go to CDNJs over JSDelivr, in fact they offer CloudFlare as backend too and another CDNS (so more POPs including all in the CDNJs).

Are there any reason to preffer CDNJs over JSDelivr, or am I missing something?

I am not trying to compete or something, just trying to understand a comparison.

**Comment by PeterDaveHello** [comment]
@ricardopolo Yes they use multi CDN provides, which is more complex, relys on upper layer DNS service provide, though we only use cloudflare currently, but cloudflare is is the only CDN service with support both spdy + http/2.0 protocols, which can support both legacy and modern devices, also, we have more libraries, if you want to benifit from http/2.0 or spdy, you should try to load resources from the same place, so they can be started parallel, and we provide more libs so if may help users use as much as possible lib from our public cdn. Even you don't load many libs as dependencies, as you can see here: https://twitter.com/PeterDaveHello/status/724957631538970625 CDNJS has more users, using CDNJS can have higher probability to share the cache on client side, if a user have loaded highlight.js v9.1.0 from other sites before, if you are also using it on your website, so there will be a cache hit on local, totally speed up the performance, though my English is not so good, I guess you can understand.

In fact, I am not saying CDNJS is better in all parts, we also have our problems, if you like our service, you are also welcome to join us and contribute, than make this service better.

**Comment by ricardopolo** [comment]
They say the support HTTP/2 and SPDY too. 
The number of libraries would be bigger in the project with more time resources and contributors.  So I cannot see a very clear advantance in this point, thinking about the feature.

Would be completely crazy if think that sometimes, you would merge in the same project?
Both projects are great but have limited time resources... 

As a user is very difficult to choice in which contribute.  If both project has the same goals and the same constrains, thinking about a merge would be the better for the Global Internet :)

**Comment by PeterDaveHello** [comment]
Let me answer your last comment first:

> They say the support HTTP/2 and SPDY too. 

Yes, they support HTTP/2 and SPDY too, but not like Cloudflare does, if you are served by a non-Cloudflare pop, there is only HTTP/2 **or** SPDY, it's not depend on your client, but there CDN pop, and if your client didn't support HTTP/2 but SPDY, it can't fallback to SPDY, they can't support HTTP/2 100% due to multiple CDN provider, Cloudflare support both HTTP/2 and SPDY **at the same time**, and it's depends on your clients' support, not the server side.

> The number of libraries would be bigger in the project with more time resources and contributors. So I cannot see a very clear advantance in this point, thinking about the future.

We have more libs about 12% than jsDelivr, and cdnjs has minimun requirement about the library popularity, which means the probability of sharing cache is higher by using CDNJS.

> Would be completely crazy if think that sometimes, you would merge in the same project?
Both projects are great but have limited time resources...

Currently, I don't think so ...

> As a user is very difficult to choice in which contribute. If both project has the same goals and the same constrains, thinking about a merge would be the better for the Global Internet :)

You still can if you like to contribute FOSS projects, as you can see, I'm also a contributor of jsdelivr:
https://github.com/jsdelivr/jsdelivr/graphs/contributors
https://github.com/jsdelivr/bot/graphs/contributors

If you contribute both, I think you can find out which one you like better, it's your own feeling and decision.

I would like to talk about more than the service its self if you don't mind, in fact, during the library adding process, we founds many issues from the upstream, the out-dated npm pacakge, the inconsistent structure/version, etc, I don't know what other people, at least, CDNJS always report to upstream and help solve the issues, in fact, as you can see, there are two teams called @cdnjs/intern & @cdnjs/intern2, they are some students that accepted my training about using GitHub, git, nodejs, npm and some other related techs, they are also asked to do so, what I want is to also contribute to upstreams, not only the single project, so I can say: we are trying to make the world better. What do you think?

At last, I still have to say, there are many problems and issues waiting to be solved, CDNJS is not so good or good enough, I'm not begging that we didn't do it good enough because we are students(most of the current contributors and members), but I want to say that we are trying to do better with our limited time, I can promise that you'll see this project become better and better, though we'll need a longer time.

**Comment by PeterDaveHello** [comment]
@cdnjs/team-cdnjs

**Comment by ricardopolo** [comment]
You have very good arguments. I'll wait a couple of days for more respones and then I'll close this issue.
