### ISSUE TITLE
[Request] Add freqdec datepicker

### ISSUE THREAD

**Issue by Etheliene** [cdnjs/cdnjs#7898]
**Library name:** freqdec datepicker
**Git repository url:** https://github.com/freqdec/datePicker
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://freqdec.github.io/datePicker/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
