### ISSUE TITLE
[Request] Add uize 

### ISSUE THREAD

**Issue by ghost** [cdnjs/cdnjs#7960]
**Library name: UIZE**
**Git repository url: https://github.com/UIZE/UIZE-JavaScript-Framework/**
**License(s): MIT**
**Official homepage: www.uize.com**

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
