### ISSUE TITLE
[Request] Add selectonic 

### ISSUE THREAD

**Issue by ruimelodev** [cdnjs/cdnjs#8129]
**Library name:** selectonic
**Git repository url:** https://github.com/anovi/selectonic.git
**npm package url(optional):** 
**License(s):** MIT https://github.com/anovi/selectonic/blob/master/LICENSE-MIT
**Official homepage:** http://anovi.github.io/selectonic/

**Comment by Amomo** [comment]
Hi @ruimelodev 

We have received your request, but sorry this lib __doesn't have enough popularity.__ 
(for example,100 stars/watchers on GitHub or 500 times download per month on npm)
You can take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you opening an issue again when the repo has enough popularity.
Or, if there is any other proof of popularity, we may discuss to add it.

Thank you for your contribution. 

> This issue will be closed if there is no any response in next 7 days.

**Comment by Amomo** [comment]
closed due to no response.

**Comment by PeterDaveHello** [comment]
Let's add this lib.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
