### ISSUE TITLE
[Request] Add three-orbit-controls

### ISSUE THREAD

**Issue by terencechow** [cdnjs/cdnjs#8189]
**Library name: three-orbit-controls** 
**Git repository url: https://github.com/mattdesl/three-orbit-controls**
**npm package url(optional):** 
**License(s): **
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @terencechow,

Thanks for your suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

Best,
Peter

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by PeterDaveHello** [comment]
Re-open because the popularity looks good enough to be hosted now.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
