### ISSUE TITLE
[Request] Add parallaxify by hwthorn

### ISSUE THREAD

**Issue by golman** [cdnjs/cdnjs#8221]
**Library name:** parallaxify
**Git repository url:** https://github.com/hwthorn/parallaxify
**npm package url(optional):** nope
**License(s):** Released under the MIT license. http://hwthorn.mit-license.org
**Official homepage:** http://hwthorn.github.io/parallaxify/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Because it has no tag and no response for a long time but I can trace commit log to find out it has two version `v0.0.1`, `v0.0.2`
https://github.com/hwthorn/parallaxify/commit/da67338e1ecbfd75259f66006bffd7dfae8a14bb#diff-9e1a7db63605440b0fdc61611347bbf5R2
https://github.com/hwthorn/parallaxify/commit/993793fd318b379a6ed4ec5db05948d04f6ce426#diff-9e1a7db63605440b0fdc61611347bbf5R2
Should I add it without git tag?
Thanks!

**Comment by PeterDaveHello** [comment]
Just do it :+1:

**Comment by hwthorn** [comment]
let me know and we can add the tag

**Comment by PeterDaveHello** [comment]
@hwthorn didn't see the tag yet, would be good to have it! Is there any plan on this?
@kennynaoh @pvnr0082t please take care of this.
