### ISSUE TITLE
[Request] Add js-rich-marker

### ISSUE THREAD

**Issue by giovannipds** [cdnjs/cdnjs#8242]
**Library name:** js-rich-marker
**Git repository url:** https://github.com/googlemaps/js-rich-marker
**npm package url(optional):** 
**License(s):** Apache 2.0
**Official homepage:** https://github.com/googlemaps/js-rich-marker
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄

**Comment by giovannipds** [comment]
@MattIPv4 Hahaha, hi there! Of course it doesn't, you're answering a 4 years old issue, kkkk it does not even make any sense anymore right now. In fact, when I've created, the PR template didn't even exist yet. Besides that, I thank you for answering. Keep up the good work cleaning the issues. Best regards.

**Comment by MattIPv4** [comment]
Sorry for such a delay on our end with these! There are a surprising number of requests from 0216 that are still valid and maintained. I'm slowly working through all issues we have open and creating PRs where we can. :)
