### ISSUE TITLE
formvalidation is not released under a free license

### ISSUE THREAD

**Issue by legoktm** [cdnjs/cdnjs#8278]
The license terms for the formvalidation library link to <http://formvalidation.io/license/>, which is not a free license.

CC @PeterDaveHello who added the library in 7d1e4d58c95a1510b63da06adaeb40e62e094371.

This was originally reported at <https://phabricator.wikimedia.org/T128841>.

**Comment by PeterDaveHello** [comment]
Sorry that I didn't notice that formvalidation doesn't have free or open source license, will you want me to remove it? Thanks.

**Comment by legoktm** [comment]
Yes, I think removal is the best option.

**Comment by PeterDaveHello** [comment]
Okay, that's really a special case, my fault, sorry.

**Comment by PeterDaveHello** [comment]
The website will also be removed later, since there is cache and deploy delay, thanks.

**Comment by legoktm** [comment]
No worries, thank you very much! :)

**Comment by PeterDaveHello** [comment]
@legoktm Thanks.

**Comment by jwater7** [comment]
FormValidation ([formerly BootstrapValidator](https://github.com/nghuuphuoc/bootstrapvalidator/tree/0c96659eda586269c02a45948744ac135676ff0d)) was originally released under the MIT license ([up to version 0.5.2](https://github.com/nghuuphuoc/bootstrapvalidator/releases/tag/v0.5.2)).  Then, it was changed to a free to use in non-commercial projects under CC BY-NC-ND 3.0 [until 0.6.0](https://github.com/formvalidation/formvalidation/commit/c19ea0a262abab9705f6b61a573bb902eb31ac14).  It has since been [changed to a commercial license](https://github.com/formvalidation/formvalidation/commit/da7b34e8815787cbbce55c7d9bb4f5300f8e0bb9).

That being said, taking this version (0.6.1) down was probably appropriate, but want to let people who are interested that there ARE releases that are free to use and could be posted back on to the CDN.
