### ISSUE TITLE
[Request] Add Live.js

### ISSUE THREAD

**Issue by viankakrisna** [cdnjs/cdnjs#8326]
**Library name:** Live.js
**Git repository url:** https://github.com/Q42/LiveJS
**npm package url(optional):** 
**License(s):** unknown
**Official homepage:** http://livejs.com/
**Wanna say something? Leave message here:**
# this is a drop in replacement for quick browser-sync alternative without creating any build system, really hope they have a https hosting support

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@viankakrisna 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
This lib is cool and the big problem is the versioning.

**Comment by sashberd** [comment]
@PeterDaveHello May we could add it manually by version [4.0](https://github.com/Q42/LiveJS/blob/bf827065509878eeb989b4a229428fb9b3bba24e/livejs.js#L5) . What do you think?

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
