### ISSUE TITLE
[Request] Add ng-jsoneditor

### ISSUE THREAD

**Issue by balihoo-dengstrom** [cdnjs/cdnjs#8720]
**Library name:** ng-jsoneditor
**Git repository url:** https://github.com/angular-tools/ng-jsoneditor
**License(s):** The Artistic License 2.0
**Wanna say something? Leave message here:**
This is the Angular directive for the already-hosted [jsoneditor](https://cdnjs.com/libraries/jsoneditor).

**Comment by Piicksarn** [comment]
Hi @balihoo-dengstrom :
There isn't enough notable popularity of the library.
 `(ex: more than 100 stars on GitHub or 500 downloads per month on npm)`
please take a look on our **[README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md)** for detail.
Would you mind to open a new issue again when there is notable popularity of library? :grinning: 
Thanks for your request! 

***`The issue would be closed due to no response after 7 days`***

**Comment by balihoo-dengstrom** [comment]
Hi, @Piicksarn. That's sounds good. Feel free to close this request.

**Comment by PeterDaveHello** [comment]
Let's give this one a month and see if it can reach the popularity!

**Comment by Piicksarn** [comment]
@PeterDaveHello, it's  been a month after.
Should we add the library?

**Comment by PeterDaveHello** [comment]
Let's add this
