### ISSUE TITLE
[Request] Add ng-notify 

### ISSUE THREAD

**Issue by Opvolger** [cdnjs/cdnjs#8803]
**Library name:** ng-notify
**Git repository url:*https://github.com/matowens/ng-notify/*
**npm package url(optional):** 
**License(s):*The MIT License (MIT)*
**Official homepage:*http://matowens.github.io/ng-notify/#demo*
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello this lib seems need multi-filemap support in git auto-updater, its `.css` files are in `src/styles` and `.js` files are in both `dist` and `src/scripts`.

the author also mention jsdelir CDN link on git repo, do we need to add this lib soon and add it without multi-filemap(set `src` as basepath).

**Comment by PeterDaveHello** [comment]
npm not working here ?

**Comment by maruilian11** [comment]
@PeterDaveHello 
yes, npm works. but there are only two versions on npm and they are two versions behind the latest version(v0.8.0), which means the author may not push version to npm usually.

there are some ways we can try:

1. ask the author if he can put the latest version to npm and keep it latest so that we can use multi-filemap function of npm auto-update.
2. use `src` as basepath of git auto-update rather than dist folder.
3. write multi-filemap function for git auto-update.

**Comment by PeterDaveHello** [comment]
Try to contact with the author first, thanks.

**Comment by PeterDaveHello** [comment]
Ping.
