### ISSUE TITLE
[Request] Add hsimp-jquery 

### ISSUE THREAD

**Issue by xlsdg** [cdnjs/cdnjs#8955]
**Library name:** hsimp-jquery
**Git repository url:** https://github.com/howsecureismypassword/jquery
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/howsecureismypassword/jquery
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @xlsdg :
There isn't enough notable popularity of the library.
(ex: more than 100 stars on GitHub or 500 downloads per month on npm)
please take a look on our README.md for detail.
Would you mind to open a new issue again when there is notable popularity of library? :grinning:
Thanks for your request!

The issue would be closed due to no response after 7 days

**Comment by Piicksarn** [comment]
**Closed due to no response**
