### ISSUE TITLE
Add Enforce-CT header

### ISSUE THREAD

**Issue by indolering** [cdnjs/cdnjs#8972]
I noticed you are moving to HSTS and even submitted yourself for the browser preload list and thought I would suggest adding key pinning as well.

There are ~1.5K entities that can issue an HTTPS certificate for any website and even Comodo was hacked by a script kiddie. Certificate authorities issue certs based on the ability to receive an email, create a DNS record, or embed some HTML in a page ... so you also have to trust every network operator for every certificate authority.

Key pinning (ala HPKP) mitigates the issue by binding trust to a specific key.  There is also an HPKP browser preload list.  Cloudflare appears to have HPKP turned on for their main site, but not for their API servers....

**Comment by PeterDaveHello** [comment]
@indolering We have enabled HPKP for cdnjs.com recently, api.cdnjs. com and cdnjs.cloudflare.com is the next step, the issue is that we should at least pin two keys there, keys and the timing info need to be very precise, to prevent break the site and service, currently, cdnjs.com only ping the key of COMODO, to balance the security and maintenance convenience, since we do not directly control the certs as we use CloudFlare as the reverse proxy as the CDN, I am not sure if directly ping the key for the domains is a good idea. 

cc @terinjokes @ryankirkman

**Comment by terinjokes** [comment]
Thanks for this ticket @indolering. At this point I don't think we'll be adding HPKP for cdnjs.cloudflare.com. There's also intent from Chrome to remove support.

We do plan on supporting the "Enforce-CT" header soon, likely first in "report" then in "enforce" modes. I've retitled this ticket to reflect this work.

**Comment by MattIPv4** [comment]
Given that HPKP was removed from Chrome a while back, as was Expect-CT, and Enforce-CT never seems to have become a thing (Chrome now requires CT on all public sites), I'm going to close out this issue. Let me know if I've missed something.
