### ISSUE TITLE
[Request] Add ngPrint

### ISSUE THREAD

**Issue by prabhum07** [cdnjs/cdnjs#9020]
**Library name:** ngPrint
**Git repository url:** https://github.com/gilf/ngPrint.git
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:**https://github.com/gilf/ngPrint
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @prabhum07  :
There isn't enough notable popularity of the library.
`(ex: more than 100 stars on GitHub or 500 downloads per month on npm)`
please take a look on our README.md for detail.
Would you mind to open a new issue again when there is notable popularity of library? :grinning:
Thanks for your request!

The issue will be closed due to no response after 7 days

**Comment by prabhum07** [comment]
Okay thank you!
