### ISSUE TITLE
[Request] Add SheepIt!

### ISSUE THREAD

**Issue by arwebz** [cdnjs/cdnjs#9032]
**Library name:** SheepIt!
**Git repository url:**https://github.com/wongalus/sheepit
**npm package url(optional):** 
**License(s):**SheepIt is free software and you can distribute it and/or modify it under the terms of MIT
**Official homepage:**http://www.mdelrosso.com/sheepit/
**Wanna say something? Leave message here:**This is forked from mdelrosso/sheepit
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @wongalus ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can host the origin one: https://github.com/mdelrosso/sheepit

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
