### ISSUE TITLE
[Request] Add react-bootstrap-select  

### ISSUE THREAD

**Issue by heramerom** [cdnjs/cdnjs#9062]
**Library name:** react-bootstrap-select 
**Git repository url: https://github.com/tjwebb/react-bootstrap-select**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @heramerom  :
There isn't enough notable popularity of the library.
 `(ex: more than 100 stars on GitHub or 500 downloads per month on npm)`
please take a look on our **[README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md)** for detail.
Would you mind to open a new issue again when there is notable popularity of library? :grinning: 
Thanks for your request! 

***`The issue would be closed due to no response after 7 days`***

**Comment by PeterDaveHello** [comment]
There must be something wrong, this lib looks very good to be added.

**Comment by heramerom** [comment]
Thanks

**Comment by PeterDaveHello** [comment]
Let's host this lib?

**Comment by PeterDaveHello** [comment]
ping
