### ISSUE TITLE
[Request] Add lorenzbaum/roboto-and-material-icons-fonts

### ISSUE THREAD

**Issue by kokeksibir** [cdnjs/cdnjs#9260]
**Library name: lorenzbaum/roboto-and-material-icons-fonts** 
**Git repository url: https://github.com/lorenzbaum/roboto-and-material-icons-fonts.git**
**npm package url(optional):** 
**License(s): Apache 2.0**
**Official homepage:**
*_Wanna say something? Leave message here: It is not my own library, but I find it very useful and would like to use it by CDNJS. *_
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @kokeksibir  :
There isn't enough notable popularity of the library.
`(ex: more than 100 stars on GitHub or 500 downloads per month on npm)`
please take a look on our **README.md** for detail.
Would you mind to open a new issue again when there is notable popularity of library? :grinning:
Thanks for your request!

The issue will be closed due to no response after 7 days

**Comment by sashberd** [comment]
@PeterDaveHello I suggest to close this issue. The lib did not get enough popularity since the issue was opened
FYI
