### ISSUE TITLE
[Request] Add essoduke/jQuery-tinyMap

### ISSUE THREAD

**Issue by DualNibs** [cdnjs/cdnjs#9270]
**Library name:** essoduke/jQuery-tinyMap
**Git repository url:**https://github.com/essoduke/jQuery-tinyMap
**npm package url(optional):** 
**License(s):**MIT License
**Official homepage:**https://code.essoduke.org/tinyMap/ (chinese?)
**Wanna say something? Leave message here:**I using this on my projects and wish I can use it on cdnjs. Thanks!
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@DualNibs 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. Also there is no git tag on this repo and the lib doesn't have enough popularity. 
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@sufuf3 please help confirm if its author would like to add git tags for it, I think we can host this one.

**Comment by PeterDaveHello** [comment]
(And maybe also this one: https://github.com/essoduke/jQuery-TWzipcode)

**Comment by sufuf3** [comment]
There is a git tag on these library.
Thanks.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
