### ISSUE TITLE
https://cdnjs.cloudflare.com/ajax/libs/formvalidation/0.6.1

### ISSUE THREAD

**Issue by erictansh** [cdnjs/cdnjs#9293]
I was using it for a while.... recently I just found out that it now returns 404. Can you please put it back?

**Comment by erictansh** [comment]
I have switched over to https://www.jsdelivr.com/projects/jquery.formvalidation

Will prefer to keep all my js with cdnjs. Do let me know when it is back online.

**Comment by PeterDaveHello** [comment]
@erictansh What's is the full URL please?

**Comment by erictansh** [comment]
The files I used are:-
https://cdnjs.cloudflare.com/ajax/libs/formvalidation/0.6.1/js/formValidation.min.js
https://cdnjs.cloudflare.com/ajax/libs/formvalidation
/0.6.1/css/formValidation.min.css
https://cdnjs.cloudflare.com/ajax/libs/formvalidation
/0.6.1/js/framework/bootstrap.min.js

You can download them at
https://cdn.jsdelivr.net/jquery.formvalidation/0.6.1/js/formValidation.min.js
https://cdn.jsdelivr.net/jquery.formvalidation/0.6.1/css/formValidation.min.css
https://cdn.jsdelivr.net/jquery.formvalidation/0.6.1/js/framework/bootstrap.min.js

**Comment by PeterDaveHello** [comment]
@erictansh formvalidation is not released under any free or open source license, the add of it is a mistake made my me, and been reported by @legoktm in #8278, so I removed it a few months ago, sorry about that, I think the copy on jsDelivr may have the same license issue.

**Comment by erictansh** [comment]
ok noted with thanks

Regards,

**Comment by PeterDaveHello** [comment]
@erictansh Thanks.

**Comment by jwater7** [comment]
FormValidation ([formerly BootstrapValidator](https://github.com/nghuuphuoc/bootstrapvalidator/tree/0c96659eda586269c02a45948744ac135676ff0d)) was originally released under the MIT license ([up to version 0.5.2](https://github.com/nghuuphuoc/bootstrapvalidator/releases/tag/v0.5.2)).  Then, it was changed to a free to use in non-commercial projects under CC BY-NC-ND 3.0 [until 0.6.0](https://github.com/formvalidation/formvalidation/commit/c19ea0a262abab9705f6b61a573bb902eb31ac14).  It has since been [changed to a commercial license](https://github.com/formvalidation/formvalidation/commit/da7b34e8815787cbbce55c7d9bb4f5300f8e0bb9).

That being said, taking this version (0.6.1) down was probably appropriate, but want to let people who are interested that there ARE releases that are free to use and could be posted back on to the CDN.

**Comment by PeterDaveHello** [comment]
Thanks @jwater7
