### ISSUE TITLE
[Request] img-slider

### ISSUE THREAD

**Issue by lewisclement** [cdnjs/cdnjs#9322]
img-slider
https://github.com/kavyasukumar/imgSlider
https://www.npmjs.com/package/img-slider
The MIT License (MIT)
http://kavyasukumar.com/apps/imgSlider/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @lewisclement 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by kennynaoh** [comment]
close due to no response.
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Let's push this lib.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
