### ISSUE TITLE
[Request] Add behave.js 

### ISSUE THREAD

**Issue by seigler** [cdnjs/cdnjs#9411]
**Library name:** behave.js
**Git repository url:** https://github.com/jakiestfu/Behave.js
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://jakiestfu.github.io/Behave.js/
**Wanna say something? Leave message here:**
This is a lightweight library to give `textarea` tags IDE-like keyboard shortcuts including indenting behavior.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by PeterDaveHello** [comment]
See if we'll get response here: https://github.com/jakiestfu/Behave.js/issues/29#issuecomment-348704368

**Comment by jakiestfu** [comment]
Added `1.5.0` and also published on `npm` 😬

**Comment by PeterDaveHello** [comment]
Thanks @jakiestfu 👍

**Comment by PeterDaveHello** [comment]
@sashberd as you can see if no anyone tagged in the issue, sometimes it won't be noticed, just politely ping its author will help, same on the other issues, no need to directly close them :)

**Comment by seigler** [comment]
Thanks @jakiestfu :tada:

**Comment by sufuf3** [comment]
We can add this lib because there is a git tag and this lib has enough popularity.
Reopen this issue again.
Thanks.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
