### ISSUE TITLE
[Request] jquery.appear

### ISSUE THREAD

**Issue by mblum24** [cdnjs/cdnjs#9525]
Library name: jquery.appear
Git repository url: https://github.com/bas2k/jquery.appear/
License(s): MIT

**Comment by extend1994** [comment]
@pvnr0082t the author added the tag five days ago!

**Comment by pvnr0082t** [comment]
@extend1994 Thanks for reminding

**Comment by sashberd** [comment]
@extend1994 I found [this ](https://github.com/morr/jquery.appear)repo is similar to this one. What we should host?

**Comment by sufuf3** [comment]
@sashberd CDNJS host morr/jquery.appear as https://cdnjs.com/libraries/jquery.appear with `jquery.appear` folder name.
So we can use `bas2k-jquery.appear`as the folder name.
Thank you. 😃

**Comment by sashberd** [comment]
@sufuf3 I mean the library is the same with their goal and development, thus should we host both of them or the one with bigger stars number?

**Comment by sufuf3** [comment]
The content of the file(`jquery.appear.js`) are different from those libs.
I think it's good to host, because the lib has enough popularity.
What do you think?

**Comment by PeterDaveHello** [comment]
@sashberd We host anyone meets our requirement, otherwise, there are many libraries have the same gaol.

**Comment by sashberd** [comment]
@sufuf3 OK 
maybe we could use jquery-appear instead of jquery.appear?

**Comment by sufuf3** [comment]
I prefer to use `bas2k-jquery.appear` but actually `jquery-appear` is fine because CDNJS website support algolia search engine.
IMO, when people search the libs from CDNJS website, if the folder name can be more identified, it will good for people.

Whatever, I think you can choose the folder name which you want to name. 😃 
Because the lib still can be searched.

Thank you.
