### ISSUE TITLE
[idea] Add latest link for scripts

### ISSUE THREAD

**Issue by alimd** [cdnjs/cdnjs#987]
Thank you for create this useful cdn
Do you agree with this idea
add latest (in file name) for last version or link without version
for example:
`//cdnjs.cloudflare.com/ajax/libs/jquery/latest/jquery.min.js`
or
`//cdnjs.cloudflare.com/ajax/libs/jquery/1/jquery.min.js`

like google cdn
`//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js`

if you agree with this useful idea i will fork and change all links.

**Comment by AliMD** [comment]
Any progress after 9 years?

**Comment by MattIPv4** [comment]
👋 The short answer is no.

Adding support for tags such as `latest` on libraries would go against many of the principles that cdnjs operates on -- we ensure that all assets we serve are immutable, they will never change, so that they can be as efficiently cached as possible, and will never break for any website using them. Changing assets under a tag would make this not possible.

We also strive to encourage users to use SRI hashes when importing libraries from cdnjs, which performs an integrity check on the asset for security, ensuring it has not been modified. Having assets on the CDN that change, such as those under tags, would mean that the SRI hashes would be continually changing and serve no real purpose to an end-user of the service.
